### ISSUE TITLE
Testing on NT Commercial 2950 treadmill 

### ISSUE THREAD

**Issue by victorypoint** [cagnulein/QZCompanionNordictrackTreadmill#1]
Adb logcat output after apk install and launch:

[logcat.txt](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/8834130/logcat.txt)

**Comment by cagnulein** [comment]
this is the issue Attempt to read from null array
06-03 13:09:56.404  7962  8153 E AndroidRuntime: 	at org.cagnulein.qzcompanionnordictracktreadmill.QZService.pickLatestFileFromDownloads(QZService.java:173)

**Comment by victorypoint** [comment]
Wireshark capture of treadmill UDP port 8002:

[apk-test.zip](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/8835150/apk-test.zip)

**Comment by victorypoint** [comment]
Wireshark capture of treadmill UDP port 8002 while running workout with speed and incline changes:

[apk-test-workout.zip](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/8835198/apk-test-workout.zip)

**Comment by victorypoint** [comment]
Adb logcat output after new apk install and launch:

[logcat.txt](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/8835218/logcat.txt)

**Comment by cagnulein** [comment]
Great news! It's perfect! I'm gonna to importing this in QZ!
