### ISSUE TITLE
Proform10 with IFIT screen, trying to install QZ Companion : ADP not working

### ISSUE THREAD

**Issue by Tangosteve** [cagnulein/QZCompanionNordictrackTreadmill#10]
Have turned on USB Debug but ADP did not work on wifi (with IP address) or via USB to USB connection.
In USB/USB connection the device is not being recognized but ADP is working.
I Tried to a reset of android screen but no pinhole for resetting. The only option is to clear memory and data, then log in again.

**Comment by cagnulein** [comment]
@victorypoint any other idea?

**Comment by victorypoint** [comment]
> @victorypoint any other idea?

The bike must have a reset pinhole. Maybe this will help? https://www.reddit.com/r/iFit/comments/sj2d10/proform_t10_reset_button/

**Comment by Tangosteve** [comment]
> 

I checked all around casing, and no pin hole. I did read on another thread that because I have USB and HDMI connections my model does not have a rest button (not too sure if this statement is correct)

**Comment by victorypoint** [comment]
> > 
> 
> I checked all around casing, and no pin hole. I did read on another thread that because I have USB and HDMI connections my model does not have a rest button (not too sure if this statement is correct)

Is there any mention in the manual on how to reset? What is the exact model and year?

**Comment by Tangosteve** [comment]
Pro Form Smart Power 10.0 Cycle .. you are correct .. the manual shows a reset in the usb recess. So I am resetting now

**Comment by Tangosteve** [comment]
rest and privileged mode activated tried and adb still does not work via wifi or usb

**Comment by Tangosteve** [comment]
its android 5.1.1 .. not too sure if too old

**Comment by cagnulein** [comment]
@Tangosteve what do you see in the Windows Device Manager about the usb connection to the tablet?

**Comment by cagnulein** [comment]
@Tangosteve also check this https://github.com/fawazahmed0/Latest-adb-fastboot-installer-for-windows

**Comment by Tangosteve** [comment]
@cagnulein I cant see any connection to the tablet
@cagnulein

**Comment by cagnulein** [comment]
@Tangosteve if so means that the usb port is not a data port but only a power...it sounds really strange to me. Do you hear the classic "windows storage sound" when you put the cable on your pc? are you sure that the cable is a data cable?

**Comment by Tangosteve** [comment]
@cagnulein I dont hear a sound when I plug in ... I have a cheap usb tio usb cable .. but it does say data cable on packaging

**Comment by Tangosteve** [comment]
@cagnulein when i run the wifi batch file it pings the address and sees it ..

**Comment by Tangosteve** [comment]
@cagnulein i did run the fast boot file above too. That seemed to work but then the adb stuff did not

**Comment by cagnulein** [comment]
@Tangosteve ip it's ok, but if the android version doesn't have the wifi capabilites for adb we are fried.

can you try to run a console in the tablet itself

```
su
setprop service.adb.tcp.port <port>
stop adbd
start adbd
```

accordingly to this you should be able to enable the adb over wifi https://stackoverflow.com/questions/2604727/how-can-i-connect-to-android-with-adb-over-tcp/3623727#3623727

**Comment by Tangosteve** [comment]
@cagnulein how do you get into console mode

**Comment by cagnulein** [comment]
you need to use an app for it, for example terminal or similar to the store (you can download the apk)

**Comment by victorypoint** [comment]
Assuming qz-companion.bat file was run? Has qz-companion-log.txt, ADB logcat file, and dumpsys package log files been uploaded?

**Comment by cagnulein** [comment]
@victorypoint no, he can't connect to the adb wirelessy

**Comment by Tangosteve** [comment]
Need to pop off now ... will check again tomorrow

**Comment by victorypoint** [comment]
Also wondering if companion can be installed via web browser assuming there is one factory installed?

**Comment by cagnulein** [comment]
@victorypoint nice idea! I guess so since you can download if from the github page

**Comment by victorypoint** [comment]
> @victorypoint nice idea! I guess so since you can download if from the github page

And toggling on installing APK from unsigned source should be doable.

**Comment by cagnulein** [comment]
@Tangosteve because probably you need to login first on github in the tablet browser
Anyway you can send to your google drive and use a link from google drive directly

**Comment by Tangosteve** [comment]
Ok .. I’ll look into that . Thanks Sent from my iPhoneOn 27 Oct 2022, at 16:49, Roberto Viola ***@***.***> wrote:﻿
@Tangosteve because probably you need to login first on github in the tablet browser
Anyway you can send to your google drive and use a link from google drive directly

**Comment by Tangosteve** [comment]
Put in Google drive .. and started download on tablet .. but does not get passed Queued .. Sent from my iPhoneOn 27 Oct 2022, at 16:49, Roberto Viola ***@***.***> wrote:﻿
@Tangosteve because probably you need to login first on github in the tablet browser
Anyway you can send to your google drive and use a link from google drive directly

**Comment by victorypoint** [comment]
@cagnulein , how about https://tinyurl.com/app?

**Comment by cagnulein** [comment]
@victorypoint you need to upload it anyway because the url from github will not work directly. but yes tinyurl could be helpful

**Comment by cagnulein** [comment]
@Tangosteve check the new documentation https://github.com/cagnulein/QZCompanionNordictrackTreadmill It should fix your issue! Let us know!
@victorypoint did a awesome job!

**Comment by cagnulein** [comment]
@Tangosteve did you fix it? try also the last build
