### ISSUE TITLE
Incline works but not resistance on S22i

### ISSUE THREAD

**Issue by Esya** [cagnulein/QZCompanionNordictrackTreadmill#100]
Hi, first of all - thanks for the amazing project, I've been looking for something like this for a long time!

I moved my s22i to privileged mode and installed the companion app through ADB using the latest release (3.3.44)
I set my bike as s22i in the companion app.

In the settings : 

- I've set my bike's IP in `TDF Companion IP` 
- I've enabled ADB Remote : If I don't do this, incline does not work either, I just get read-only data

I then tried both with the QZ Desktop and Android version to connect to the nordictrack s22i, and in both cases :

I get the correct data coming in (Resistance, inclination, speed, etc...) but, when I start a manual workout, I can only set the incline, not the resistance

Side note: My resistance and inclination sliders are on and visible during this process

Any ideas ?

Thanks!

**Comment by cagnulein** [comment]
Yes that's right, qz controls only the inclination since the inclination affects also the resistance on your bike

**Comment by Esya** [comment]
The documentation states that I should be able to later use autoresistance
for use with zwift , I suppose to use erg mode, does that mean that while
on a flat road in zwift, if the expected power increases, Qz will increase
the incline instead of increasing the resistance?

If the companion app is able to programmatically manipulate sliders,
shouldn't it be able to manipulate the resistance slider too ?

**Comment by cagnulein** [comment]
Yes as I implemented now QZ handles directly the inclination in order to have ERG mode and free ride with one slider handling. Of course I can change this, but this is the state of the art.
Let me know!

**Comment by cagnulein** [comment]
by they way the erg handling for s22i is in the qz version 2.16, i don't know if you are already using this version.
let me know

**Comment by cagnulein** [comment]
you can join the beta for android here https://play.google.com/apps/testing/org.cagnulen.qdomyoszwift

handling the resistance only is possible, but since it would change the behaviour i have to create also another setting to don't break the compatibility with the rest of the people so i would like to keep the thing as they are if possible.

for erg, just enable the erg mode in qz (there is also a button in the tile setting for this)

Let me know!

**Comment by cagnulein** [comment]
@Esya any news?
