### ISSUE TITLE
App lets me select treadmill via radio button and leaves no way to click submit/next. Stuck on that page.

### ISSUE THREAD

**Issue by tedtninety** [cagnulein/QZCompanionNordictrackTreadmill#101]
**Describe the bug**
After selecting the correct Nordic model via radio button, that's where it remains.
There is no option to go next or any other way to proceed.

**To Reproduce**
1. Installed the app via Github:
_QZ Installation Method 2: Via the treadmill or bikes build-in web browser._
2. Installed App. Made sure that USB Debugging was enabled.
3. Switched over  nd Opened IFit and logged in
4. Opened QZ App, selected my Nordic Track model via click on radio button.
Then stuck there. No other way to advance and finish setup. No buttons, no menu. Just the radio buttons.

**Expected behavior**
Completion of set-up, via next button or submit.

**Screenshots**

**Desktop (please complete the following information):**
Nordic Track Android Tablet

**Smartphone (please complete the following information):**
Nordic Track i22

  
  
**Additional context**
I am hoping to have QZ App let KinoMap work with my  Nordic Track i22 since Nordic Track does not show in the equipment selection.

Thank you for your brilliant work.
I am real excited to make it work.
Grazie!

**Comment by cagnulein** [comment]
hi, there is  no next button, just select the right device and you are good
to go. now you have  to continue the setup on your phone with the qz app
there

let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 16 lug 2024 alle 00:22 ted ***@***.***> ha
scritto:

**Comment by tedtninety** [comment]
Hi an thank you for your reply.
I am confused. I did not know that I must have the QZ app running on the Nordic Track and also another QZ app on the iPhone?

**1st question:** How do I know if I installed the QZ App on the Nordic Track successfully?
**2nd question**: So all the configuration is actually done via the iPhone ( or PC, iPad ) via the QZ App?
and lastly, this works with Zwift will this also work with KinoMap?

Grazie Millie,
ted

**Comment by tedtninety** [comment]
Thank you @cagnulein . I will try the setup with my iphone ( with QZ app installed).'

>  you can run zwift on the same device of qz if you are running qz on android or pc, otherwise you need a second device for zwift and kinomap<

I am not sure what you mean.
My goal is to have KinoMap and/or Zwift installed on my Nordic Track.
Ultimately being able to enjoy KinoMap terrain while running and have KinoMap automatically change the incline levels
As a bonus, use Zwift for variety.

With QZ App, I should be able to do this, yeah?
BTW, Would I need IFit to be open always when using either of these apps when using QZ app?
Grazie!
ted

**Comment by cagnulein** [comment]
> I am not sure what you mean. My goal is to have KinoMap and/or Zwift installed on my Nordic Track.

> you can't. zwift and kinomap must be running on a separate device

> Ultimately being able to enjoy KinoMap terrain while running and have KinoMap automatically change the incline levels As a bonus, use Zwift for variety.

yes you can do this, but you need: 1 device for qz, 1 device for kinomap or zwift and of course ifit and qz companion on your treadmill

> 
> With QZ App, I should be able to do this, yeah? BTW, Would I need IFit to be open always when using either of these apps when using QZ app? Grazie! ted

yes

**Comment by tedtninety** [comment]
Hi. I was watching the [video](https://www.youtube.com/watch?v=_KRMSHxo5AQ). Which app is this?
How do I install it if it is not the one I installed on my NordicTrack? 
Please see attached picture.
![ffwefwef](https://github.com/user-attachments/assets/15bc3add-002d-46bb-a317-848e21f42d78)

I used QZ Installation Method 2: Via the treadmill or bikes build-in web browser so I am a little confused.

Grazie,
ted

**Comment by tedtninety** [comment]
Nevermind the question prior.I understand.
Apologies. I will get the app from App Store. 
I will try to get it to work. :)

I see and have read the wonderful reviews form others that Zwift works with auto incline via QZ Companion. Does the incline feature also work with KinoMap?
Grazie Mille!
ted

**Comment by cagnulein** [comment]
yes also kinomap it's supported!

**Comment by tedtninety** [comment]
Hi Roberto. I thought I was making progress but I found that my Nordic Track model is not in the QZ  App dropdown. It is the NordicTrack Commercial X22i .

![x22i](https://github.com/user-attachments/assets/0f21bbba-f68e-471a-96aa-4e8c580c9991)

Also when I tap on the screen the side measurements do not show.
![294722315-d9191fb8-0942-4db4-bb96-21db94a74fe7](https://github.com/user-attachments/assets/ed93c08d-32fa-4fdd-b0cd-c13b678aac99)

At some point while trying many ways with the app, I saw numbers on the they did not match what was on my treadmill.

Grazie,
ted

**Comment by cagnulein** [comment]
@tedtninety you have to select the x22i in the companion app. in the qz app instead you have just to set the ip address of the treadmill
let me know

**Comment by tedtninety** [comment]
Hi! 
But what do I select here?
![349286060-15bc3add-002d-46bb-a317-848e21f42d78](https://github.com/user-attachments/assets/bda1388f-ecf1-4a8d-b325-3126679f60d4)

Also on the apps like KinoMap or Zwift what device to select if Nordic Track is not there?

Grazie!

**Comment by cagnulein** [comment]
it's useless that selection, it is only for bluetooth treadmill.
In kinomap you have to select the ftms device and you will see the phone name on kinomap
On zwift you will see the phone name and also the wahoo virtual device from qz

**Comment by tedtninety** [comment]
I'm sorry what is the  ftms device  ?
There is bluetooth on treadmill, it is not needed?
I'm sorry I am confused.

Also, I saw numbers on the tiles but they did not match the treadmill  
After I rebooted, the numbers stopped showing.

**Comment by tedtninety** [comment]
OK I looked up ftms device:

The FiTness Machine Service protocol, better known as FTMS, is the latest Bluetooth standard used to control fitness equipment including treadmills.

I'm sorry but on KinoMap it requests I choose a device to get anything started.  I do not see phone name. What did I miss perhaps.

Thank you again.

**Comment by cagnulein** [comment]
In kinomap, you have to select in the pairing screen, FTMS device, there you will see the QZ phone device (kinomap on a device, qz on another must be).



> Also, I saw numbers on the tiles but they did not match the treadmill After I rebooted, the numbers stopped showing.

create a debug log and I will check it https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by tedtninety** [comment]
Thank you again Robert. YOU Are as amazing as I keep reading from many places online :)
I will start from scratch and let you know.
Grazie! So talented, so dedicated, and so good. 
How rare.

**Comment by tedtninety** [comment]
Hi Roberto.
I tried everything , but it won't work for me.
I cannot get the information from my treadmill to show on phone app. The tiles on the app show no info.

What I have done:
- On the treadmill - USB Debug - enabled.

- QZ Companion App installed on Treadmill.
- On the app, I selected my treadmill model, and then tried others just in case.

- My Nordic Track is the x22i. There is a checkbox for it on the QZ Companion App  on the treadmill -  but my treadmill model does not show on the QZ Phone App.
That was confusing, but I followed what you suggested and selected any Nordic Track model on the phone app even though it didn't match the one entered on the QZ app on the treadmill
- I entered the treadmill's IP address on the phone app, but still nothing.

I checked KinoMap to see if my phone as you had mentioned would show up as a selection,  but it did not.
I am not sure what else to do.

![Nordic1](https://github.com/user-attachments/assets/fc5e85ce-68d0-4da6-9a77-c911bd569b78)


Grazie,
ted

**Comment by cagnulein** [comment]
hi Ted, first of all we have to fix the metrics on qz before going on kinomap.

in order to do so, let's start with a debug log

https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

I'm currently on vacation so I will check it tomorrow

**Comment by tedtninety** [comment]
Sorry the treadmill and my network has been acting odd. I need to spend time to reset the treadmill and find out what is wrong with my network.

**Comment by cagnulein** [comment]
No problem, take your time.
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 8 ago 2024 alle ore 06:41 ted ***@***.***> ha
scritto:
