### ISSUE TITLE
NordicTrack S15i won’t connect 

### ISSUE THREAD

**Issue by Donverlong** [cagnulein/QZCompanionNordictrackTreadmill#102]
I conducted the install of the companion app to the S15i which is successful. The app connected once (last night) and I managed to ride Zwift, although the incline response was very slow and didn’t match Zwift on the uphill sections (2% instead of 5% and slow to adapt). Now the app won’t connect at all. Debug attached from todays attempt. 
[debug-Wed_Jul_31_12_22_57_2024.log](https://github.com/user-attachments/files/16441674/debug-Wed_Jul_31_12_22_57_2024.log)

**Comment by cagnulein** [comment]
beta software of ifit? i don't know anything about it. Anyway what did you do yesterday? did you start from a factory reset? is it possible that myabe yesterday you restore the factory settings and then, later after your ride updates itself losing the connectivity? if it so I strongly suggest to DON'T update ifit after a restore.
Let me know

**Comment by Donverlong** [comment]
Ok, yes after factory reset. Then it updated. Regards Jez On 31 Jul 2024, at 13:40, Roberto Viola ***@***.***> wrote:﻿
beta software of ifit? i don't know anything about it. Anyway what did you do yesterday? did you start from a factory reset? is it possible that myabe yesterday you restore the factory settings and then, later after your ride updates itself losing the connectivity? if it so I strongly suggest to DON'T update ifit after a restore.
Let me know

**Comment by Donverlong** [comment]
It was the beta. Working. Will get back to you on the issue of incline being slow to respond and incorrectly responding.

**Comment by Donverlong** [comment]
Yeah incline not working at all now.

**Comment by cagnulein** [comment]
ok that's great! by default qz is changing inclination every 4 seconds due to don't overstress the inclnation engine. you can change it by changing the Inclination Delay seting under the advanced setting

**Comment by cagnulein** [comment]
> Yeah incline not working at all now.

create a debug log with the issue. did you enable the sliders in ifit app?

**Comment by Donverlong** [comment]
Yes sliders are working.

**Comment by Donverlong** [comment]
[debug-Wed_Jul_31_12_22_57_2024.log](https://github.com/user-attachments/files/16442200/debug-Wed_Jul_31_12_22_57_2024.log)

**Comment by cagnulein** [comment]
ok i guess it's always about the ifit update. you should try to restore the factory reset and don't update it since yesterday was working and I guess it's all due to this

**Comment by cagnulein** [comment]
> [debug-Wed_Jul_31_12_22_57_2024.log](https://github.com/user-attachments/files/16442200/debug-Wed_Jul_31_12_22_57_2024.log)

this is the same file of the first one sent

**Comment by Donverlong** [comment]
Has a different time stamp in the files app

**Comment by cagnulein** [comment]
because probably you didn't close the qz app previously. anyway i can't see anything there, there is no connection at zwift at all.
anyway check my previous message



> ok i guess it's always about the ifit update. you should try to restore the factory reset and don't update it since yesterday was working and I guess it's all due to this

and also try to use the inclination tile on qz with the plus button to see if you can manipulate the inclination on the bike: you should see a fake touch event when you press the plus button.

**Comment by Donverlong** [comment]
I'll try a reset and reinstall. 🤞
