### ISSUE TITLE
What is AccessibilityService needed for?

### ISSUE THREAD

**Issue by IzzySoft** [cagnulein/QZCompanionNordictrackTreadmill#104]
The IoD scanners just reported

```
! repo/org.cagnulein.qzcompanionnordictracktreadmill_133.apk declares intent-filter(s): android.accessibilityservice.AccessibilityService
```

As there are no changelogs I couldn't find out what that might be needed for. Could you please clarify? Thanks in advance!

**Comment by cagnulein** [comment]
I'm trying to handle swipes directly from accessibility rather than adb

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 2 ago 2024 alle 23:26 Izzy ***@***.***> ha
scritto:

**Comment by IzzySoft** [comment]
Thanks! How to explain that to a non-techy user? It shows up as "sensitive" with the app listing at IzzyOnDroid. And while I'd not exactly describe myself as non-techy: what swipe does need accessibility? Guess I'd need to dig into the "construct" again here. You do the "physical swipe" on one device, and want the effect on another? Could you put that into a short line, so I can add it to your app's "green list" – like it's done with the permissions here?

![image](https://github.com/user-attachments/assets/670b16ed-b60e-4299-a4ce-a6c5498e9f0d)

**Comment by cagnulein** [comment]
yes, when the qz app on a device wants to increase speed or inclination, it sends an intent to the companion to do a physical swipe over the ifit app to change it. 

so basically swipe over other apps in order to control bike and treadmill

**Comment by IzzySoft** [comment]
Thanks – yes, that was what I thought but could not get phrased :see_no_evil: Now let me see how I can phrase that for the green list, as the above would be a little long:

```yaml
android.accessibilityservice.AccessibilityService: needed to allow the qz app on a device to swipe over the ifit app to change e.g. speed or inclination
```

Would that (i)fit?

**Comment by cagnulein** [comment]
lol this sounds perfect! thanks!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 3 ago 2024 alle 12:55 Izzy ***@***.***> ha
scritto:

**Comment by IzzySoft** [comment]
Thanks! Added, saved, published – LIVE :smiley:
