### ISSUE TITLE
3.4.7 Crashes on Samsung Tab S9+

### ISSUE THREAD

**Issue by Olorin92** [cagnulein/QZCompanionNordictrackTreadmill#107]
Hi there,

As per the title - I've installed the 3.4.7. version of the APK onto my Samsung Tab S9+, but when opening it just crashes immediately. I've done the pre-requisite setup on my Nordictrack treadmill and all appears to be running properly, so not sure what I should do here.

Any help would be greatly appreciated!

**Comment by Olorin92** [comment]
Seems to be not just limited to my tablet, my Pixel phone also has the same problem. Both are running Android 14 which could be the issue I guess?

**Comment by cagnulein** [comment]
you don't have to install this apk on a regular android but only on the
nordictrack tablets :)
which nordictrack device do you have?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 25 ago 2024 alle 08:26 Olorin92 ***@***.***> ha
scritto:

**Comment by Olorin92** [comment]
So I ended up getting the QZ app from the app store and that worked perfectly!

One question - I'm guessing the speed/incline control from within the QZ companion app is essentially just mapping to touches on the treadmill tablet UI (not directly sending some sort of backend request to increase speed/incline)?

And I'm terms of compatibility - I have a T9.5s but I've just done T7.0 as that was the closest I could find. I assume this only matters for the previously mentioned speed/incline adjustment?

**Comment by cagnulein** [comment]
yes qz uses the touch screen event to map inclination and speed changes.

you can use the adb screenshot batch file to collect the manual workout window of ifit so i can add the compatibility of your treadmill too

let me know!

**Comment by Olorin92** [comment]
However I just get the following:

`List of devices attached
192.168.1.111:5555     device product:argon2 model:MalataMediatekArgon2 device:argon2 transport_id:1


Waiting for 0 seconds, press a key to continue ...
adb.exe: no devices/emulators found
adb: error: failed to get feature set: no devices/emulators found
adb.exe: no devices/emulators found`

**Comment by cagnulein** [comment]
did you enable the adb setting in the developer settings on your treadmill?

**Comment by Olorin92** [comment]
All good - was because I don't have 'adb' in my path (just modified it to use .\adb.exe instead). Here is the screenshot!
![t9 5s screenshot](https://github.com/user-attachments/assets/d133f8f9-308f-4758-91a8-40dfdf9bd860)

**Comment by cagnulein** [comment]
perfect, i will add it tomorrow

**Comment by cagnulein** [comment]
@Olorin92 done
https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.4.8/QZCompanionNordictrackTreadmill.apk
select the t9.5s new device and restart the treadmill

let me know!

**Comment by Olorin92** [comment]
Awesome thank you!

Sorry to sidetrack with another question - but I noticed overnight that the app that gets installed on the treadmill had crashed, and took a couple of times to start it up successfully. Is that normal behavior?

**Comment by cagnulein** [comment]
are you able to provide me a adb logcat of the crash? it shouldn't happen
of course

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 26 ago 2024 alle 11:30 Olorin92 ***@***.***> ha
scritto:

**Comment by Olorin92** [comment]
So finally got around to installing the updated companion - set the treadmill to the model you added 😄 

One thing I realized though - doesn't something like Zwift or the companion app (the one that actually goes on the tablet or phone, NOT the treadmill) also need to be aware of the T9.5s button locations?

**Comment by cagnulein** [comment]
Nope only qz needs to know the buttons locations

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 2 set 2024 alle 14:09 Olorin92 ***@***.***> ha
scritto:

**Comment by Olorin92** [comment]
So I did do that and then used the companion app, but the speed change and incline didn't do anything 😢

**Comment by cagnulein** [comment]
Ok this means that the coordinates for inclination are not right. Can you share a debug log showing the issue? https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by Olorin92** [comment]
So just to make sure - I've got the QZ companion app installed on my treadmill and have the T9.5s treadmill selected in there.

On my tablet I've installed the QZ app from here: https://play.google.com/store/apps/details?id=org.cagnulen.qdomyoszwift. In the settings for this app I can't see the T9.5s so just picked what was closest (T8.5s).

Is this all setup correctly?

If so - should I be getting the dump above from my phone or the treadmill?

**Comment by cagnulein** [comment]
Yes you did correctly. Just a confirm : you can see speed and inclination
on qz, you can also control speed but not inclination from qz, right?
If so the log is required from the qz app on your phone

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 2 set 2024 alle 14:34 Olorin92 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Ok share a debug log so I will check it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 2 set 2024 alle 14:53 Olorin92 ***@***.***> ha
scritto:

**Comment by Olorin92** [comment]
Will do! So from the phone or the treadmill?

**Comment by cagnulein** [comment]
From the phone

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 2 set 2024 alle 15:06 Olorin92 ***@***.***> ha
scritto:

**Comment by Olorin92** [comment]
[debug-Mon_Sep_2_23_09_33_2024.log](https://github.com/user-attachments/files/16837952/debug-Mon_Sep_2_23_09_33_2024.log)
Here's a log from the phone - I started a run on the treadmill then hit the speed and incline buttons up and down in the QZ app but nothing happened

**Comment by cagnulein** [comment]
do you see any touch event on the treadmill when you are pressing the plus button on the speed or incline tile on qz?
if not could you please select the profile x22i no adb in the companion, restart the treadmill and check if you can see them? 
probably you will see them in a wrong position, but if it's so, it's easy to fix

let me know!

**Comment by Olorin92** [comment]
I don't think so - I didn't notice anything happening on the screen.

I'll test that out and let you know how I go, thanks again for your help!

**Comment by Olorin92** [comment]
Yep so confirming changing to that treadmill in the QZ app on the treadmill does make clicks happen (although as you said, they're not quite in the right spot)

**Comment by cagnulein** [comment]
That's perfect! I will align them today

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 3 set 2024 alle 04:50 Olorin92 ***@***.***> ha
scritto:

**Comment by Olorin92** [comment]
Perfect let me know when I should retest 😁

**Comment by cagnulein** [comment]
done
https://github.com/cagnulein/QZCompanionNordictrackTreadmill/actions/runs/10679183964/artifacts/1884910107

select again the t 9.5s (no adb) device and restart it-
Let me know if it's better!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 3 set 2024 alle ore 08:11 Olorin92 ***@***.***>
ha scritto:

**Comment by Olorin92** [comment]
So I did this - it sort of worked once (I pressed plus and it took speed down to 1.6 when it was 2) but then doesn't do anything else after I click buttons again 🥲

**Comment by cagnulein** [comment]
does the speed updates in qz as well? enable the touch shadow in the developer settings of the treadmill tablet so we can see what it's doing when "it doesn't do anything else". i guess it's swiping with a wrong coordinates

**Comment by Olorin92** [comment]
It updated in QZ for the first time, but not after that 😃 I'll enable the show touches option and send through the result

**Comment by Olorin92** [comment]
Here you go! It seems to swipe down for going up with speed. Inclination seems to just tap and not really swipe

https://photos.app.goo.gl/yPF5RS3iupMoubCh8

**Comment by cagnulein** [comment]
ok so it's just a matter of coordinates. i will check this later

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 4 set 2024 alle 07:09 Olorin92 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
ok let's see first for the inclination. does your treadmill handles also the 0.5% step? otherwise set the incliantion step in the treadmill settings in qz from 0.5 to 1 and try again

**Comment by Olorin92** [comment]
So just confirming it does do 0.5 increments for incline so I guess I shouldn't need to adjust that right?

**Comment by cagnulein** [comment]
ok so let's try this
https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.4.12/QZCompanionNordictrackTreadmill.apk
don't change anything on the qz side so

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 4 set 2024 alle ore 09:39 Olorin92 ***@***.***>
ha scritto:

**Comment by Olorin92** [comment]
Ok speed seems to work now with two caveats - it seems to vary how much it increases and decreases. I did one increase from the QZ companion and that added .4kmh, then a decrease which deducted 0.1kmh then another decrease which deducted 0.2kmh. it's also a bit laggy to respond from the QZ companion app but maybe that's expected.

Incline doesn't do anything still though

**Comment by cagnulein** [comment]
ok so i guess the best way to calibrate this is to fix the offset yourself trying. let's start from the inclination

the actual code of it is

```
                        x1 = 76;
                        y1Inclination = 823 - (int) ((lastInclinationFloat) * 46.0);
                        y2 = y1Inclination - (int) ((reqInclination - lastInclinationFloat) * 46.0);

```

where the lastInclinationFloat is the current inclination value in %
the reqInclination is the requested one in %

then you can use these using the adb on your mac with

adb shell input swipe x1 y1Inclination x1 y2 200 (of course replace the variable with the numbers)

you have to find the right offset to match the inclination values.

Let me know!

**Comment by Olorin92** [comment]
Ok thanks! Have you got the numbers for speed too?

**Comment by cagnulein** [comment]
yes

```
                            x1 = 1845;
                            y1Speed = 817 - (int) (((QZService.lastSpeedFloat * 0.621371) - 1) * 42.5);
                            y2 = y1Speed - (int) (((reqSpeed * 0.621371) - (QZService.lastSpeedFloat * 0.621371)) * 42.5);
```

same concept of above. the 0.621371 constant is the conversion from miles to km/h because qz is always working on km/h

**Comment by Olorin92** [comment]
Perfect thanks! So if I understand right, I should effectively plug all these values in and calculate the required variables for the input swipe command, and the value I should be adjusting is the 46 for incline and 42.5 for speed?

**Comment by cagnulein** [comment]
exactly! or the 817 and 823 if needed too

**Comment by Olorin92** [comment]
Ok I will have a play. Is there any methodology to doing it? I.e. should I start with a fixed increment of say going from 2 to 2.5 speed, get that working, then see how other speeds work?

Also - what exactly does the QZ companion app send for the plus/minus buttons? It doesn't actually tell me how much it's trying to incrementing by

**Comment by Olorin92** [comment]
Trying to figure out how to translate this into the function above - for speed I took screenshots at 2kmh at .1 increments up to 2.5kmh, the Y pixel change from the speed before it was as follows
2kmh - N/A (base speed)
2.1kmh - -3px change
2.2kmh - -4px change
2.3kmh - -3px change
2.4kmh - -3px change
2.5kmh - -3px

So obviously the 0.1km/h increment is adjusting the slider on average around 3px up each time. Any ideas how to translate that into your function?

**Comment by cagnulein** [comment]
If you want we can create a lookup table. I just need the perfect
coordinates for each speeds value

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 4 set 2024 alle 12:05 Olorin92 ***@***.***> ha
scritto:

**Comment by Olorin92** [comment]
Ah I was hoping to avoid that given I'd need to pull out 17*10 lots of speeds to capture everything 🥲

Was hoping you might have a better idea of how to translate a 0.1kmh increase equalling a 3 pixel effect on the y pixel coordinate into the function you provided

**Comment by cagnulein** [comment]
yes if it's a constant 3px for each speed increment i can do a simply
equation. what about the inclination?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 4 set 2024 alle 12:13 Olorin92 ***@***.***> ha
scritto:

**Comment by Olorin92** [comment]
Yep definitely seems that way from my samples!

I'll check incline shortly and come back to you 😁

**Comment by cagnulein** [comment]
the starting Y for the speed was right so?

**Comment by Olorin92** [comment]
Assuming 817 was the base - yep that seems correct!

So from the incline screenshots I had I got:


870 0%
821 0.5%
798 1%
775 1.5%
752 2%

So other than 0% to 0.5%, the increments seem to be 23 pixels. I can see in the screenshots from 0 to 0.5 there is a more noticeable visual jump, so I guess that's just how they've got it setup 😄

**Comment by cagnulein** [comment]
perfect, i will do the modifications tomorrow!
thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 4 set 2024 alle 12:41 Olorin92 ***@***.***> ha
scritto:

**Comment by Olorin92** [comment]
Thanks again for your efforts!

Can I just check too - assuming we get this all fixed, does Zwift auto adjust incline for treadmills too? Or is that something QZ can do through Zwift? Or just not an option currently?

**Comment by cagnulein** [comment]
yes it will do then!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 5 set 2024 alle 05:12 Olorin92 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
> Trying to figure out how to translate this into the function above - for speed I took screenshots at 2kmh at .1 increments up to 2.5kmh, the Y pixel change from the speed before it was as follows 2kmh - N/A (base speed) 2.1kmh - -3px change 2.2kmh - -4px change 2.3kmh - -3px change 2.4kmh - -3px change 2.5kmh - -3px
> 
> So obviously the 0.1km/h increment is adjusting the slider on average around 3px up each time. Any ideas how to translate that into your function?

one queston, so you set your treadmill to km/h now? so i don't have to translate to miles again?

**Comment by Olorin92** [comment]
That's right I do

**Comment by cagnulein** [comment]
ok i tried to did them.
https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.4.13/QZCompanionNordictrackTreadmill.apk
let me know if it's better
i'm unsure about the inclination because with the coordinates inside the
code it should already work

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 6 set 2024 alle ore 10:23 Olorin92 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
@Olorin92 any news?
