### ISSUE TITLE
No Communication between T8.5s and Android App

### ISSUE THREAD

**Issue by TomD87** [cagnulein/QZCompanionNordictrackTreadmill#117]
Hey, My QZ setup has not been used for some time.
There was no data being sent to my QZ app on Android.

I have reset everything and installed the latest version of the Companion on the treadmill, but still no data.
Logs attached.

Its a T8.5s with that selected in the Companion and QZ App.
Happy to try another treadmill profile if you can recommend something.

[logcat.log](https://github.com/user-attachments/files/17295443/logcat.log)
[logcat.txt](https://github.com/user-attachments/files/17295444/logcat.txt)

**Comment by cagnulein** [comment]
did you maybe get a new ifit update?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 8 ott 2024 alle 17:18 TomD87 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
does adb work on your setup? if so , if you run a 

adb logcat | grep Changed

on your pc do you see the metrics on the pc?

**Comment by TomD87** [comment]
That's a great command, I will remember that.
Yes, I can see data.
![image](https://github.com/user-attachments/assets/d2faf142-cf81-4fa1-bff9-4a13c4ca4395)

**Comment by cagnulein** [comment]
https://github.com/cagnulein/qdomyos-zwift/issues/1591#issuecomment-1664105559

**Comment by TomD87** [comment]
Thanks, I have ran the command and restarted the companion app.
I assume ADB Debug is the toggle in the developer options?
Still no output to the mobile device.

**Comment by TomD87** [comment]
Sorry R, I now have speed with the Grand Tour, but no incline.

**Comment by cagnulein** [comment]
> That's a great command, I will remember that.
> 
> Yes, I can see data. I guess its my Phone\Tablet settings that need amended?
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/d2faf142-cf81-4fa1-bff9-4a13c4ca4395)
> 
> 

here i can see only speed changes indeed. do you see inclination as well?

**Comment by TomD87** [comment]
Here is an updated one with incline.

![image](https://github.com/user-attachments/assets/575af7bb-7f3b-4a89-994a-eb75744cf40f)

**Comment by TomD87** [comment]
Sorry, its me note looking correctly again.
I think it is all working.
Adjustment from the app is not but i can live without that for now.

**Comment by cagnulein** [comment]
yes i was saying this :)

for writing incline and speed, did we handle this in the past?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 8 ott 2024 alle 19:21 TomD87 ***@***.***> ha
scritto:
