### ISSUE TITLE
How to Download

### ISSUE THREAD

**Issue by Promtber** [cagnulein/QZCompanionNordictrackTreadmill#12]
How do you download on your PC? I cant figure how to download and open. Can you please advise a step by step.

**Comment by cagnulein** [comment]
are you the same YT user?

**Comment by Promtber** [comment]
I got it all downloaded on the treadmill, the QZ fitness app runs on the iPad and reads speed and incline. I set all the setting as stated in the directions. Zwift picks up my treadmill and cadence sensors. But my avatar doesn't run. Any suggestions?

**Comment by cagnulein** [comment]
ok please just use this channel :)
are you using 2 devices? one for zwift and one for qz?

**Comment by Promtber** [comment]
No, just the one.

On Nov 6, 2022, at 11:27 AM, Roberto Viola ***@***.***> wrote:

﻿

ok please just use this channel :)
are you using 2 devices? one for zwift and one for qz?

**Comment by cagnulein** [comment]
you have to use 2 :) at least for now

**Comment by Promtber** [comment]
Ok, just got it to work, iPhone the app and iPad for zwift. Now I can run but incline won’t match the zwift on the treadmill. Thank you for all the help.

On Nov 6, 2022, at 11:36 AM, Roberto Viola ***@***.***> wrote:

﻿

you have to use 2 :) at least for now

**Comment by cagnulein** [comment]
@Promtber zwift doesn't control the incline on ANY treadmill in the world :) it's how zwift works. I have a workaround here https://www.youtube.com/watch?v=KTQ2n7yeDbo but for the moment QZ doesn't support writing inclination on your specific treadmill. You have to change it manually for the moment

**Comment by Promtber** [comment]
I’m sure this is a no, but I figured I would ask. Is there a way to download zwift on the treadmill and use it on the treadmill android screen? That would be really nice.

On Nov 6, 2022, at 11:47 AM, Roberto Viola ***@***.***> wrote:

﻿

@Promtber<https://github.com/Promtber> zwift doesn't control the incline on ANY treadmill in the world :) it's how zwift works. I have a workaround here https://www.youtube.com/watch?v=KTQ2n7yeDbo but for the moment QZ doesn't support writing inclination on your specific treadmill. You have to change it manually for the moment

**Comment by cagnulein** [comment]
i don't think the tablet itself has the hardware capabilites to do so. Of course you can try :)

**Comment by Promtber** [comment]
I tried almost worked! Got zwift loaded, sensors picked up the treadmill on zwift.  Opened iFit and started a manual run set the speed at 4mph. Qz fit read the treadmill at that speed on my iPhone. Went back to zwift, my avatar was running on the course, increased the speed, the treadmill speed increased, but the qz app stayed at the 4mph and didn’t increase, and the zwift stayed at the qz speed. Was so close! Wish there was a way, since I have such a big screen on my treadmill.

On Nov 6, 2022, at 12:30 PM, Roberto Viola ***@***.***> wrote:

﻿

i don't think the tablet itself has the hardware capabilites to do so. Of course you can try :)

**Comment by cagnulein** [comment]
are you sure that when you changed the speed the qz companion was still running on the background?

**Comment by Promtber** [comment]
Yes it was running in the background. When I started iFit and put the speed up the qz read the exact speed. As soon as I opened zwift on the treadmill screen, it read that speed and my avatar was off running. As in increased the speed, the tear mill picked up speed, but the qz stayed at the old speed and the zwift stayed at the old speed. Seem like it’s so close to all work in the nordictrac treadmill. Would be really cool if it did.

On Nov 7, 2022, at 12:52 AM, Roberto Viola ***@***.***> wrote:

﻿

are you sure that when you changed the speed the qz companion was still running on the background?

**Comment by cagnulein** [comment]
are you able to share a adb log while you're doing this thing? probably I'm able to try something about this (if it's not a problem on the ifit app itself)

**Comment by Promtber** [comment]
What is the adb log? I’m not that tech savvy, but can figure stuff out if instructed

On Nov 7, 2022, at 7:48 AM, Roberto Viola ***@***.***> wrote:

﻿

are you able to share a adb log while you're doing this thing? probably I'm able to try something about this (if it's not a problem on the ifit app itself)

**Comment by cagnulein** [comment]
@Promtber try to follow this https://stackoverflow.com/questions/3707880/using-adb-logcat-with-a-real-phone-and-not-the-emulator and let me know if you have any issues

**Comment by Promtber** [comment]
I’m not on an android, I’m on a iPhone.

On Nov 7, 2022, at 8:15 AM, Roberto Viola ***@***.***> wrote:

﻿

@Promtber<https://github.com/Promtber> try to follow this https://stackoverflow.com/questions/3707880/using-adb-logcat-with-a-real-phone-and-not-the-emulator and let me know if you have any issues

**Comment by cagnulein** [comment]
@Promtber android is the tablet. You need a PC or a Mac to do so

**Comment by Promtber** [comment]
Is this the program with the black screen, I used on the PC to put the program on the treadmill?

On Nov 7, 2022, at 8:33 AM, Roberto Viola ***@***.***> wrote:

﻿

@Promtber<https://github.com/Promtber> android is the tablet. You need a PC or a Mac to do so

**Comment by cagnulein** [comment]
yes

**Comment by cagnulein** [comment]
@Promtber did you try the last build?
