### ISSUE TITLE
Request - S40 - Change speed and elevation from QZ not working

### ISSUE THREAD

**Issue by rubenrleyva** [cagnulein/QZCompanionNordictrackTreadmill#120]
Hello again, after a long time off due to illness that I have been able to spend time on the treadmill again, I have found that QZCompanionNordictrackTreadmill is not working, that is, it seems that it does not take the coordinates of the treadmill screen correctly, also if in qdomynos I change the speed by pressing plus or minus the treadmill changes speed and the change is shown on the treadmill screen, however in the app itself the value does not change, the incline does not work either. Could we do something to remedy this? Thank you very much :)

https://github.com/cagnulein/QZCompanionNordictrackTreadmill/issues/22

**Comment by cagnulein** [comment]
Do you see a reaction on the touchscreen of the treadmill  when you are pushing the inclination or speed plus buttons?

**Comment by rubenrleyva** [comment]
Hi, sorry for the delay in responding. When I press speed plus in QZ, the screen on my treadmill changes to a different screen, the speed on the treadmill does not increase, nor does the speed value change in QZ. For the incline, pressing plus does nothing on either the treadmill or QZ. It seems that the values ​​are not correct, https://docs.google.com/spreadsheets/d/10MpKnmfoq5UO3qgdWikRFha4mwgP3ecu8o3qDXphegM/edit?usp=sharing thanks!

**Comment by cagnulein** [comment]
Thanks I will try to implement these next week

**Comment by cagnulein** [comment]
@rubenrleyva the s40 device on the companion app should be already ok for this. did you try? if it wasn't set before you need to set it and then restart the treadmill
let me know!

**Comment by rubenrleyva** [comment]
Yes, everything is set up for S40. I have tried installing everything from scratch several times and no luck.

**Comment by cagnulein** [comment]
But are you still seeing a reaction in the touchscreen when you are pressing the speed buttons in qz? If so are you able to collect a adb logcat from your treadmill so I can check it?

**Comment by rubenrleyva** [comment]
Hi, with the latest version of QZCompanionNordictrackTreadmill QZ Fitness does nothing, however with 'https://github.com/cagnulein/QZCompanionNordictrackTreadmill/issues/22#issuecomment-1364953935' it works but not correctly when pressing on the QZ Fitness buttons, I leave a video where you can see it, it happens on both Android and Windows. Thanks :)

https://github.com/user-attachments/assets/a1444c09-9b19-4ed7-9841-db07a597c604

**Comment by cagnulein** [comment]
@rubenrleyva these logs are from the old one or the newest one?

**Comment by rubenrleyva** [comment]
@cagnulein I have been able to do this in some tests from scratch,
old: [logcat.txt](https://github.com/user-attachments/files/17984027/logcat.txt)
newest: [logcat.txt](https://github.com/user-attachments/files/17984070/logcat.txt)

**Comment by cagnulein** [comment]
hi @rubenrleyva unfortunately in both logs there is no trace of qz at all (instead on your previous one was fine). Did you collect them while the manual workout was running on ifit? because when you stop the workout, ifit will clear the logs

**Comment by rubenrleyva** [comment]
@cagnulein newest: 
[logcat.txt](https://github.com/user-attachments/files/18023725/logcat.txt)

**Comment by cagnulein** [comment]
ok in this log i can see qz for 3 minutes with a fixed speed of 1.5km/h
i don't see any control from qz, at least not from the companion. what was you see too? or did you see random touch event? if you saw soo maybe you have the adb remote setting enabled in qz under the nordictrack settings?
Let me know
