### ISSUE TITLE
Proform 2000 Treadmill

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/QZCompanionNordictrackTreadmill#18]
> Hi,I was able to get the coordinates. These are as accurate is I could get.  If there is an easier way to do this via a log/dump etc let me know. Speed Lowest viable on slider is 1 & highest is 19Tap increments by button increase it by .1 & actual highest is 19.3X is 1195 & y changes as I slide it up1 y is 5983 is 631.2 19 is 255.618 is 289.16 is 318.614 348.613 is 378.511 is 402Inc line how’s from -3 to 12Default is 0Y is 79.3-3 is 595.2-2 562.20 is 522.21 is 489.32 is 465.34 is 439.511 is 289.612 is 252.5

originally posted here https://github.com/cagnulein/QZCompanionNordictrackTreadmill/commit/fb4ff40d7a0587a883f8cd2e17469f02011867ee#commitcomment-91666555

**Comment by cagnulein** [comment]
@Majorswigs let me try to understand your message.

Speed:
Min value: 1 km/h
Max value: 19.3 km/h

Inclination:
Min value: -3
Max value: 12

In your message i don't understand all your "is" number "is" number "is" number. what do you mean?

I need an X coordinate for speed and incline and a miny and maxy for both inclination and speed.
Let me know these and I will implement it!

**Comment by Majorswigs** [comment]
![A0F2845A-DA8A-4E5B-AAD0-A579A8E0F0B6](https://user-images.githubusercontent.com/118655153/205085760-15791d64-447c-4887-ac34-025dd9cf5b1b.jpeg)

**Comment by cagnulein** [comment]
ok perfect, let me build a equation

**Comment by cagnulein** [comment]
ok so speed equation 
X = 1195
![image](https://user-images.githubusercontent.com/48216/205088897-ce657ac5-a4f3-49db-bcb0-388813289e07.png)

inclination equation
X= 79
![image](https://user-images.githubusercontent.com/48216/205088982-755b6ac8-c672-4d79-a275-2c7e58736954.png)

[proform2000.xlsx](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/10133556/proform2000.xlsx)

does it sound ok to you @majorswigs ?

**Comment by cagnulein** [comment]
@Majorswigs done! New release ready https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/tag/3.0.6 for you! Let me know how it goes!

**Comment by Majorswigs** [comment]
I was able to test it 

> Incline works as expected for increments 

> Negative incline is not working

>  Speed control works but is not accurate. I have some more measurements below that should help. 
![highest value 19 3, difference in vertical y direction from location… png](https://user-images.githubusercontent.com/118655153/205219276-2f4ae5a3-8999-41e0-bee4-8d2adba8e4d1.png)

For speed control 1 & 3 I have mentioned two numbers & they signify  where each number box starts and ends on screen.   You should be able to plot the remaining in excel as the delta would be same. Other value are updated too if you need them.  

Also when you start the workout the default speed is 2 which be causing the speed to not update correctly. 

> I changed the speed manually from the control as the app seemed to be frozen the speed came down to 1 but then again increased to 9.  I think this is because there is some lag between update from app interface and actual screen controls. 

> Are the start and stop button supposed to work for the treadmill?

**Comment by cagnulein** [comment]
Hah ok I'm fixing these today!
About the negative incline it's something that I already fixed in the qz beta. Are you on android or iOS? @Majorswigs

**Comment by Majorswigs** [comment]
I am on iOS.

**Comment by cagnulein** [comment]
ok new chart for speed
![image](https://user-images.githubusercontent.com/48216/205234147-f809bc44-c52c-4f08-a7c7-8c587ef18475.png)
[proform2000.xlsx](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/10138824/proform2000.xlsx)

**Comment by cagnulein** [comment]
@Majorswigs new qz companion released https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/tag/3.0.8?notification_referrer_id=NT_kwDNvFiwNDk3OTQ2NzA4Mzo0ODIxNg

**Comment by cagnulein** [comment]
@Majorswigs for the new ios build 
send me an email to roberto.viola83 at gmail.com indicating this ticket. Thanks

**Comment by Majorswigs** [comment]
![highest value 19 3, difference in vertical y direction from location… png](https://user-images.githubusercontent.com/118655153/205369172-41a19c3f-fd29-455c-940d-5f6a9b555121.png)

It works ok for most part other than the change described above

**Comment by cagnulein** [comment]
ok i will change this tomorrow but i don't understand if you're refering to inclination or speed. could you please change directly the excel file? thanks @Majorswigs
