### ISSUE TITLE
adb remote on both ios and android could replace the companion?

### ISSUE THREAD

**Issue by cagnulein** [cagnulein/QZCompanionNordictrackTreadmill#19]
Hi @victorypoint 
  i just discovered and tested this https://github.com/wsvn53/adb-mobile
Along with the actual adb remote implementation that I did in the companion, we should be able to add to the QZ app (not the companion, I mean the QZ app directly) the ability to read the log and write the swipe from the QZ app itself.

What do you think? It could help the users not so tech savvy?

**Comment by cagnulein** [comment]
@victorypoint I guess it should be faster because there is a step less. Don't you think? The adb connection should be already established...
My only concerns are:
1) maybe this module is against the iOS rules?
2) all the treadmill/bike accepts an adb remote connection from the outside via IP? I'm quite sure that somebody tell us that it can only use adb via USB, am I remembering right?

**Comment by cagnulein** [comment]
> I think it was an older Android version on the bikes tablet if I recall. That's the problem.. no ADB, no QZ control.

so this companion app will be always a sense to exist, at least for this old android devices.
My TDF4 has also android 4 I believe without adb remote (never tried), but it has a websocket to share/write the metrics. I'm wondering if on these old android devices, we could have the same websocket port open too. Something to keep in mind.

**Comment by victorypoint** [comment]
> > I think it was an older Android version on the bikes tablet if I recall. That's the problem.. no ADB, no QZ control.
> 
> so this companion app will be always a sense to exist, at least for this old android devices. My TDF4 has also android 4 I believe without adb remote (never tried), but it has a websocket to share/write the metrics. I'm wondering if on these old android devices, we could have the same websocket port open too. Something to keep in mind.

That's good to know. So if equipment doesn't support Bluetooth, then try wifi websocket, then finally try wifi adb.
