### ISSUE TITLE
Having Zwift control Elevation and speed

### ISSUE THREAD

**Issue by doublejj0321** [cagnulein/QZCompanionNordictrackTreadmill#20]
I'm all set up with my 2950 but unsure on how I can have Zwift control these items?

**Comment by cagnulein** [comment]
hi @doublejj0321 first of all, double check that qz is controlling the companion: are you able to change the speed of the treadmill using the plus and minus buttons in the speed tiles in qz?

if so follow this https://www.youtube.com/watch?v=KTQ2n7yeDbo

**Comment by doublejj0321** [comment]
I’m not able to control it via the app with the plus or minus buttons

**Comment by cagnulein** [comment]
ok @doublejj0321 are you seeing the metrics from qz app on your phone?

**Comment by cagnulein** [comment]
did you select in the companion the "2950" option @doublejj0321 ?

**Comment by doublejj0321** [comment]
Yes and put in the correct IP address

**Comment by cagnulein** [comment]
@doublejj0321 are you leaving the ifit app always on foreground?

are you able to provide adb logcat using the adb logcat button from the companion? it's important that
- you're recreating the issue
- without stopping the workout you're pressing the button

then append the file generated here

**Comment by jjeremia** [comment]
I have the same equipment and problem with controlling the threadmill from the app. Live data is working ok. Did you find any solution to this?

**Comment by cagnulein** [comment]
@jjeremia i can add it! i just need the coordinates of your ifit screen. you can use the screenshot batch to provide me it

let me know if you need help

**Comment by doublejj0321** [comment]
I believe I may have figured out the problem. My treadmill is a 2450 2023 model which I don't believe is on the list... yet?

**Comment by cagnulein** [comment]
yes @doublejj0321 as i said before i just need the coordinates of your screen :)
