### ISSUE TITLE
Request - T8.5s - Change speed and elevation from QZ

### ISSUE THREAD

**Issue by TomD87** [cagnulein/QZCompanionNordictrackTreadmill#21]
Please merge if there is an existing thread, was have talked about this before but lost track.

I have T8.5s

At the moment, with the X11i profile selected within the companion and this gives inputs to iFit, just not the correct movement.
The X coordinate is accurate but Y is not.

I'm not sure how to give you the correct movements for Y but happy to help.

Inline is from 0% to 12% in .5 increments.
Speed is from 1.0kph to 22.0kph in 0.1 kph increments.

It may be the controls are the same size, it just needs the size of the movement adjusted.

Appreciate your help with this.

**Comment by cagnulein** [comment]
Hi @TomD87 I will implement for sure! I just need the coordinates of your tabelt like did for (for example) https://github.com/cagnulein/QZCompanionNordictrackTreadmill/issues/18

you can use this file https://github.com/cagnulein/QZCompanionNordictrackTreadmill/blob/master/InstallPackage/adb-screenshot.bat to generate the screenshot (thanks to @victorypoint )

Let me know!

**Comment by cagnulein** [comment]
hah by the way, for me today and tomorrow are travel day, so I will implement this on xmas day probably

**Comment by TomD87** [comment]
I do not expect you to do this on Christmas day, there is no rush.
See attached showing min \ max. Let me know what else you need.
![23-12-2022@13-48-14 26](https://user-images.githubusercontent.com/116304449/209346802-bac676c3-7a4b-431f-9412-8b882a896889.png)
![23-12-2022@13-48-30 59](https://user-images.githubusercontent.com/116304449/209346805-8553e5f2-6552-406f-acff-84639f50c978.png)

**Comment by cagnulein** [comment]
[t85s.xlsx](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/10295517/t85s.xlsx)
done @TomD87 you can download the new install package. Let me know if it's working. Be sure to select the new radio button that I created for your treadmill.

**Comment by TomD87** [comment]
Thank you, Incline works perfectly.
KPH jumps a little, I will try and get you some Y data over the break.

**Comment by jasonweaver** [comment]
Hi @cagnulein. I'm using the same treadmill. App on treadmill is sending all data to app on phone, but phone is not controlling speed or incline on treadmill. What logs can I share for help?

**Comment by cagnulein** [comment]
hi @jasonweaver first of all send me a debug log from qz following this https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

also did you select the right treadmill in the qz companion app?

**Comment by jasonweaver** [comment]
[debug-Sat_Jan_28_14_07_07_2023.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/10528170/debug-Sat_Jan_28_14_07_07_2023.log)

You can see that I was adjusting the speed on the device directly, but when I used the tiles for +/- speed or incline there was no change.

Thanks a ton for looking!

**Comment by cagnulein** [comment]
hi @jasonweaver are the privileged permission still enabled on the treadmill tablet?

**Comment by jasonweaver** [comment]
@cagnulein I've tried both ways, with and without privileged = true

**Comment by cagnulein** [comment]
are you able to collect adb logcat form your tablet while you're doing a speed changing from qz?

**Comment by jasonweaver** [comment]
[logcat.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/10528269/logcat.log)

**Comment by cagnulein** [comment]
got the issue @jasonweaver it seems that adb wasn't working. How do you grab this log? using the button from qzcompanion itself? is the adb setting in the developer settings enabled?

**Comment by jasonweaver** [comment]
Thanks @cagnulein , I noticed that as well, so tried a couple times. The device appears to loose the USB debugging each reboot. One attempt, I rebooted, entered privileged mode, went back to iFit and was able to control somewhat, but responses were inconsistent. I'll call that problem part two.

For problem part one, I just installed the apk from the browser on the treadmill directly. Is that incorrect to get it to retain USB debug permission?

**Comment by cagnulein** [comment]
> For problem part one, I just installed the apk from the browser on the treadmill directly. Is that incorrect to get it to retain USB debug permission?

you need explicity to enable the adb setting in the developer settings. I don't remember the exact name of the setting, maybe @victorypoint could help on this

**Comment by cagnulein** [comment]
@jasonweaver i guess debug usb and debug wireless must be on

**Comment by victorypoint** [comment]
Yep. It's I'll explain in the install documentation - https://github.com/cagnulein/QZCompanionNordictrackTreadmill

**Comment by jasonweaver** [comment]
Thanks guys. I think the issue is Method 2 on T8.5S doesn't work because USB Debugging doesn't persist after reboot. I restarted and used Method 1 and USB Debugging and privilege mode both persist. Problem one resolved.

My problem two is that - decline does not work. The other tile options do.

**Comment by cagnulein** [comment]
> My problem two is that - incline does not work. The other tile options do.

so speed forcing now works?

**Comment by jasonweaver** [comment]
Yep. Speed +/- and Incline + each work after using Method 1

**Comment by cagnulein** [comment]
wow great! for decline - send me a new debug log . 11pm here so i will check tomorrow!

**Comment by jasonweaver** [comment]
No problem. You want the logcat from the qz companion or the debug from the qz app?

**Comment by cagnulein** [comment]
both are better
