### ISSUE TITLE
Request - S40 - Change speed and elevation from QZ

### ISSUE THREAD

**Issue by rubenrleyva** [cagnulein/QZCompanionNordictrackTreadmill#22]
Hello, I would like to be able to control my S40 with QZ, is it possible?

Inline is from 0% to 12% in .5 increments.
Speed is from 1.0kph to 22.0kph in 0.1 kph increments.

![25-12-2022@21-43-25,28](https://user-images.githubusercontent.com/23198133/209482160-dfa29170-56e9-4d17-a673-3c150736bdc6.png)
![25-12-2022@21-43-37,37](https://user-images.githubusercontent.com/23198133/209482162-a3c1dbc1-9135-4ea8-974f-829ae84c48b1.png)

Thank you :)

**Comment by cagnulein** [comment]
equation done @rubenrleyva https://docs.google.com/spreadsheets/d/10MpKnmfoq5UO3qgdWikRFha4mwgP3ecu8o3qDXphegM/edit?usp=sharing
I'm adding the code!

**Comment by cagnulein** [comment]
apk ready @rubenrleyva https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/tag/3.0.14
let me know!

**Comment by rubenrleyva** [comment]
Hello again, after a long time I have been able to spend time on the treadmill again, I have found that QZCompanionNordictrackTreadmill is not working, that is, it seems that it does not take the coordinates of the treadmill screen correctly, also if in qdomynos I change the speed by pressing plus or minus the treadmill changes the speed and the change is shown on the treadmill screen, however in the app itself the value does not change, the incline does not work either. Could we do something to remedy this? Thank you very much :)
