### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by IzzySoft** [cagnulein/QZCompanionNordictrackTreadmill#23]
First thanks for making your app available openly and freely! May I ask which license it falls under? I couldn't find any details in the repo here. If you didn't decide yet, I suggest checking with [SPDX](https://spdx.org/licenses/) for a fitting one approved by OSI/FSF.

**Comment by cagnulein** [comment]
Hi @IzzySoft , yes i didn't decide yet :) 
Also i'm planning to add this project also directly built in qz via this pr https://github.com/cagnulein/qdomyos-zwift/pull/1094

Anyway I will keep your suggestion in mind! Thanks :)

**Comment by IzzySoft** [comment]
Thanks for your fast response! Good to know you have it on your list :smiley: Please let me know once you've decided, so I can add your app to [my repo](https://apt.izzysoft.de/fdroid), to make it easier to find, install and keep updated – without the need of any walled gardens.

**Comment by cagnulein** [comment]
Sure, thanks!

**Comment by IzzySoft** [comment]
No pressure, just a heads-up: any chance for a decision in the nearFuture™? :smiley:

**Comment by cagnulein** [comment]
you're right, i didn't check the license terms yet. please keep me pinged on this :)

**Comment by IzzySoft** [comment]
Will do. Shall I, to give you some incentive, shorten the interval between the pings each time? :see_no_evil: :dash:

**Comment by cagnulein** [comment]
@IzzySoft probably https://spdx.org/licenses/GPL-3.0-or-later.html will be one, what do you think?

**Comment by IzzySoft** [comment]
Totally fine, yes! If a server component is affected and you want to prevent some "big tech" from "consuming" (think "?aaS"), maybe AGPL instead (only difference is AFAIR that AGPL requires to publish changes even if you just use them with a "service"). But if that doesn't matter, your choice sounds excellent!

**Comment by cagnulein** [comment]
thanks @IzzySoft so AGPL would be better! In order to "use" it, i just need to put the license file in the root of the project? sorry but i'm completely out of the license world, i'm just writing code :)

**Comment by IzzySoft** [comment]
That's basically the thing, yes. Especially as long as you are the sole contributor (you then could even change the license any time, affecting the code from that point on but not before). Only if you had other contributors and want to change the license, you'd technically need to ask each of them if they agree – as they agreed to the terms at the time of their contributions.

So far for "legal" – for "technical" it *should* suffice to add the file to the root of your project, giving it the name `LICENSE` (Github should then detect it fine). It's quite common to also reference it from the header of each code file (a la "under the terms of the AGPL, see the LICENSE file in the project root" or similar) – but that's no strict requirement. To make clear you mean "or-later", pick the corresponding phrase in your Readme (see the "standard license header" at the end of https://spdx.org/licenses/AGPL-3.0-or-later.html). Without that it'd be "AGPL-3.0-only" – depends on your preference (personally, I always choose "only" as I don't like to bind myself to something I couldn't read before signing :wink:).

**Comment by cagnulein** [comment]
thanks @IzzySoft !
@victorypoint as co parent of this project, are you ok with this?

**Comment by cagnulein** [comment]
@IzzySoft ok I guess I did this right https://github.com/cagnulein/QZCompanionNordictrackTreadmill/commit/789daa202d151048586002a68ac85a7cf735d2c3

**Comment by IzzySoft** [comment]
If it shall be AGPL-3.0-only it looks perfect, yes – thanks a lot!

A few short questions: Did I understand correctly your app is going to be installed on the mill – and there's another app to be used as "counter-part" on the smartphone/tablet? Is the latter also available open-source – and are there some screenshots (and a dedicated icon) for your app? And last but not least: could I install "any" Android app on such a thread mill?

**Comment by cagnulein** [comment]
> If it shall be AGPL-3.0-only it looks perfect, yes – thanks a lot!

yes :)

> A few short questions: Did I understand correctly your app is going to be installed on the mill 

yes

> – and there's another app to be used as "counter-part" on the smartphone/tablet? 

yes 

> Is the latter also available open-source – and are there some screenshots (and a dedicated icon) for your app? 

yes also open source https://github.com/cagnulein/qdomyos-zwift

> And last but not least: could I install "any" Android app on such a thread mill?

as far as i know yes, but on this i will leave the microphone to @victorypoint 

also @IzzySoft a question for you: how can the user download this apk from your repository? do you have have a quick howto?

are you updating the apk automatically?

**Comment by IzzySoft** [comment]
Phantastic all! Let me go top-down:

* yes, yes, yes, yes: yeah, yeah, yeah, picked-as-well :rofl:
* maybe: OK, I'll wait – that one was just out of curiosity. I was thinking whether it would be possible to install an F-Droid client on the mill as well.
* download & install with an F-Droid client (directly on the device) – or as here, use a web browser to download the APK. URLs (become valid in about an hour with the next sync): [QZ Companion Nordictrack Treadmill](https://apt.izzysoft.de/fdroid/index/apk/org.cagnulein.qzcompanionnordictracktreadmill), [qdomyos-zwift](https://apt.izzysoft.de/fdroid/index/apk/org.cagnulen.qdomyoszwift) (both link to each other to make it easier for the interested folks to find the counter-part). Does this need a howto? I certainly can find one for you then :smiley:
* auto-update: for this app here it is enabled (as soon as you tag a new release and attach an APK to it, my updater will find and pull it within 24h). For the other one: Will there be updates? The last one was 2020. I'd then need the APK attached to releases I can recognize (you have different ones there for MacOS etc), e.g. `android-<versionCode>`. Btw, the ZIP of the latest release suggests a v1.1.0, but the APK says 1.0.

**Comment by victorypoint** [comment]
> > And last but not least: could I install "any" Android app on such a thread mill?
> 
> as far as i know yes, but on this i will leave the microphone to @victorypoint

Technically yes if you can access the treadmill OS and/or ADB she'll. User support and possibly warranty will likely be void if the machine OS fails and can't be recovered or reset.

**Comment by IzzySoft** [comment]
> warranty will likely be void

well, wouldn't that already apply when installing this very companion here? But yes, usual disclaimer: "Dragons here!" :wink:

That said: Do you want me to open an issue with the smartphone/tablet pendant for future releases, tags, `versionName` etc? This one here has been successfully solved and can be closed I guess.

**Comment by cagnulein** [comment]
> Do you want me to open an issue with the smartphone/tablet pendant for future releases, tags, `versionName` etc?

yes sure! please go on!

**Comment by IzzySoft** [comment]
Done, thanks!
