### ISSUE TITLE
Request - EXP 7i - Change speed and elevation from QZ

### ISSUE THREAD

**Issue by jdh65** [cagnulein/QZCompanionNordictrackTreadmill#24]
Hello!

Hoping to get control of my EXP 7i treadmill. The s40 is very close, since they are both 7" screens, and actually kind of works, but my treadmill is in mph and the s40 is in kph. Here are my screenshots and my best guess formulae...

![exp7iLOW](https://user-images.githubusercontent.com/8159624/210198489-7a1f3bbd-45d1-40db-b599-b337abf39889.png)

![exp7iHIGH](https://user-images.githubusercontent.com/8159624/210198499-a705db28-d9f0-4361-8c57-0ff5b06ae8cf.png)

![exp7iScreen](https://user-images.githubusercontent.com/8159624/210198561-1de5e38c-e0ba-4c28-b818-39cb9a2c475d.png)

...at your convenience.

Thanks and Happy New Year!

**Comment by cagnulein** [comment]
Thanks @jdh65 I will add this today!

**Comment by cagnulein** [comment]
@jdh65 done https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/tag/3.0.15 !

**Comment by jdh65** [comment]
Roberto,
Thanks for the rapid implementation. I clearly misunderstood how to determine the correct data to generate the equation. Here is what I think (and hope) are the correct equations...

![exp7iScreen](https://user-images.githubusercontent.com/8159624/210301336-3e0473f6-27a9-4d6b-ae27-89419acab001.png)

Also, I built the latest version of QZ on my Mac (2.12.35), supported you on Patreon, put my email address in the QZ general settings, but am still getting timed out of the app. What am I not doing correctly in order to remove the time limitation?

![trial](https://user-images.githubusercontent.com/8159624/210301740-247761a7-d879-42f0-b60e-2580b40418df.png)


Thanks!

**Comment by cagnulein** [comment]
for the patreon membership @jdh65 send me an email to roberto.viola83 at gmail.com saying which email add!
i'm changing the coordinates

**Comment by cagnulein** [comment]
done https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/tag/3.0.16 !

**Comment by jdh65** [comment]
Roberto,

Thank you for all of the effort you are putting into these apps. QZ and the companion are making me hate my NordicTrack iFit-locked treadmill a lot less.

There is a miles/kilometers communication problem going with the exp 7i. E.g. I program my workout to run at 6.5 mph for a segment, so QZ tells the companion to set the treadmill to 10.5 kph. The companion then promptly sets the treadmill to 10.5 mph. Here is a video and the data showing what I mean...


https://user-images.githubusercontent.com/8159624/210489698-596357c8-89b5-48b2-b21c-4a89a819b0dc.mov

![exp7iControlTest](https://user-images.githubusercontent.com/8159624/210489718-56ce3163-52f9-4d48-b539-11e115c33a45.png)

**Comment by cagnulein** [comment]
hah sorry! i forgot to add the km to miles conversion to your treadmill! i'm doing this right now @jdh65

**Comment by cagnulein** [comment]
done @jdh65  https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/tag/3.0.17
Let me know!

**Comment by jdh65** [comment]
Hi Roberto,

I've been troubleshooting this for a few weeks now. The kph to mph conversion you added introduced all sorts of interesting errors. The main being that as soon as a speed change occurred, it immediately reverted back.  I couldn't figure out exactly why, but thought it had something to do with the rounding step you had in place.

So I deleted the conversion you added and moved it to occur within the y2 calculation. The equation now looks like this:

```
                        } else if (device == _device.exp7i) {
                            x1 = 950;
                            y2 = (int) (453.014 - (22.702 * reqSpeed * 0.621371));
                        }

```

I also changed the initial conditions:

```
case exp7i:
                lastReqSpeed = 1.6;
                y1Speed = 430;      //vertical position of slider at 1.0 mph or 1.6 kph
                y1Inclination = 442;    //vertical position of slider at 0.0
                break;

```
Thanks!

**Comment by cagnulein** [comment]
oh ok! Thanks! I already did the changes! Let me know

**Comment by jdh65** [comment]
Very nice! The latest changes worked. Thanks for all you have done.

**Comment by cagnulein** [comment]
Great!
