### ISSUE TITLE
S22i wattage

### ISSUE THREAD

**Issue by Dickyh1980** [cagnulein/QZCompanionNordictrackTreadmill#25]
I’ve installed as per the instructions on a Nordictrack S22i but the wattage on QZ app is not the same as the iFit app on the trainer. Is there some calibration I’m missing?

**Comment by cagnulein** [comment]
strange @Dickyh1980 i'm getting wattage directly from the ifit app. anyway you can override it using the watt gain setting in qz in the advanced settings 

let me know

**Comment by cagnulein** [comment]
@Dickyh1980 also if you want to
try, i handled auto resistance for the s22i!

**Comment by billbo001** [comment]
Hi there
Just having a little trouble with my watts. Let's say on ifit it's reading 90, qz app saying 200watts. I have tried adjusting Watt gain to .4, it brings it down but also bounces between 80 to 160 watts. What is the best setting for that pls. I have a Nordic Track 22i. Also can I set when incline on Zwift is at 2% it automatically goes to 2% incline?
Cheers all

**Comment by cagnulein** [comment]
hi @billbo001 for the wattage send me a debug log and i will check it https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
