### ISSUE TITLE
Nordictrack S27I

### ISSUE THREAD

**Issue by DrowningAquaman** [cagnulein/QZCompanionNordictrackTreadmill#28]
Hi,

I am really new to this and hopefully I am doing this right. But I've installed the companion app on the nordictrack S27i and went through the steps to enter in the IP but I am not seeing anything show on the QZ fitness app. Is this just not compatible with the S27i yet?

Thank you for any help you can provide.

**Comment by cagnulein** [comment]
Hi @DrowningAquaman , it should be compatible (at least in read mode). Could you please generate a debug log https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
Thanks!
