### ISSUE TITLE
Nordictrack X32i

### ISSUE THREAD

**Issue by Kodanen** [cagnulein/QZCompanionNordictrackTreadmill#29]
I have installed the companion app successfully and I purchased the iOS version of qdomyos-zwift which connects and can read data nicely via wifi. I did test the companion in X11i, 2950, and other modes but I am unable to adjust speed and incline from the iOS app. I mean it does adjust something (there are clicks on the screen because it makes a sound and changes to fullscreen) but apparently, the coordinates are all wrong for the bigger screen. 

Which information would be needed and how could I get it for you to be able to make the necessary changes? 

Model is X32i ETNT39221-INT.0 and I am in EU with metric system, iFit app version is 2.6.81.4158, Admin version is 2.0.5.1213

Thank you for the great work

**Comment by cagnulein** [comment]
hi @Kodanen i need the coordinates of your sliders like this post https://github.com/cagnulein/QZCompanionNordictrackTreadmill/issues/24

Let me know if you need help

**Comment by Kodanen** [comment]
Here are some screenshots
![su15 01 2023@14 36 08,87](https://user-images.githubusercontent.com/19153422/212550470-ab465e44-9366-41b1-94eb-ec88658028c9.png)
![su15 01 2023@14 35 23,29](https://user-images.githubusercontent.com/19153422/212550476-9a68de27-a2fe-4e40-9518-d701c641e962.png)
![su15 01 2023@14 36 54,26](https://user-images.githubusercontent.com/19153422/212550487-d7f31b80-dbde-4b05-8557-5cbc8b9f96b0.png)

These coordinates are to the middle of the slider in both X & Y
(I wasn't sure of the coordinate system but I tried to mimic the previous poster where 0,0 is at top left corner of the screen)
Speed equation: y = -25,9811x + 978,8794 & X = 1845
Incline equation: y = -11,8424x + 881,3421 & X = 74

I got these by using linear regression in Excel
![image](https://user-images.githubusercontent.com/19153422/212550611-1ff7d2d6-699e-43f4-952a-c979ad8dfdc3.png)

Is there anything else I can do?

**Comment by cagnulein** [comment]
Perfect @Kodanen I will add these tomorrow!

**Comment by cagnulein** [comment]
done @Kodanen !  you can get the new build !

**Comment by cagnulein** [comment]
@Kodanen be aware that i just changed something quite important for https://github.com/cagnulein/qdomyos-zwift/issues/1153

So in case let me know if you have any issues
