### ISSUE TITLE
Nordictrack S15i QZ app not connecting

### ISSUE THREAD

**Issue by ferdiretief** [cagnulein/QZCompanionNordictrackTreadmill#31]
Hi there,

I followed your instructions below and installed the QZ companion app on my S15i bike after doing a factory reset. the install was successful.

However the app on my android phone does not connect to the bike - it does not pick up any Bluetooth devices even though I can see many Bluetooth devices in the normal Android interface.

I also tried to do the manual connection under advanced but the only option listed there is "wifi" - which is not one of mine

The companion app on the bike is set to "other"

Can you help please?

**Comment by ferdiretief** [comment]
I solved the issue by installing QZ on another device - it worked straight away. 
You can close this issue 
Thanks

**Comment by cagnulein** [comment]
@ferdiretief glad to hear this! i'm adding to the compatibility list!

**Comment by nreichenbach** [comment]
Hello,
Sorry to bother you, i have an S10i and i had some problem to make companion run on it.
Could you let me know what is the Andoid version on S15 (on S10, its 5.0).
Thank you
Nicolas

**Comment by cagnulein** [comment]
@nreichenbach post the error that you're facing and i will help you
