### ISSUE TITLE
S15i manual workout jumping between pause and workout

### ISSUE THREAD

**Issue by ferdiretief** [cagnulein/QZCompanionNordictrackTreadmill#32]
I set the QZ app on my S15i cycle to S22i (the default was other). 
Zwift picked up Power Source, Cadence, and Controllable in connections.
During the manual workout, the S15i screen jumps between "pause" - like it is not picking up the rpm- and the normal workout screen - where it does pick up the rpm.
I suspect that it is because Zwift is trying to adjust the rpm on the bike (because 'controllable' was picked up in connections) - is that right?
Why would this be happening?

**Comment by cagnulein** [comment]
@ferdiretief set the device in the companion app to "other". I guess the behavior that you're seeing is about the fact qz is trying to change resistance but with a s22i tablet coordinates instead of yours
let me know

**Comment by ferdiretief** [comment]
Thanks @cagnulein 
That worked
