### ISSUE TITLE
no longer listening for UDP broadcasts

### ISSUE THREAD

**Issue by jdh65** [cagnulein/QZCompanionNordictrackTreadmill#33]
Occasionally seeing these errors:

> 01-23 14:32:42.957  1397  9077 I QZ:UDPListenerService: Waiting for UDP broadcast
> 01-23 14:32:42.998  1397  8316 I QZ:UDPListenerService: Got UDP broadcast from 192.168.1.253, message: -1;-100
> 01-23 14:32:42.998  1397  8316 I QZ:UDPListenerService: -1;-100
> 01-23 14:32:42.998  1397  8316 I QZ:UDPListenerService: requestSpeed: -1.0 0.8
> 01-23 14:32:42.998  1397  8316 I QZ:UDPListenerService: requestInclination: -100.0 0.5
> **01-23 14:32:42.999  1397  9077 I QZ:UDPListenerService: no longer listening for UDP broadcasts cause of error Socket closed**
> 01-23 14:32:43.000  1397  8316 I QZ:UDPListenerService: Waiting for UDP broadcast
> 

and 

> 01-23 14:32:43.616  1397  8316 I QZ:UDPListenerService: Waiting for UDP broadcast
> 01-23 14:32:43.621  1397  8316 I QZ:UDPListenerService: Got UDP broadcast from 192.168.1.253, message: -1;-100
> 01-23 14:32:43.621  1397  8316 I QZ:UDPListenerService: -1;-100
> 01-23 14:32:43.621  1397  8316 I QZ:UDPListenerService: requestSpeed: -1.0 0.8
> 01-23 14:32:43.621  1397  8316 I QZ:UDPListenerService: requestInclination: -100.0 0.5
> **01-23 14:32:43.624  1397  8316 I QZ:UDPListenerService: no longer listening for UDP broadcasts cause of error bind failed: EADDRINUSE (Address already in use)**
> 01-23 14:32:52.908  1397  1397 I QZ:UDPListenerService: Service started
> 01-23 14:32:52.910  1397  9446 I QZ:UDPListenerService: Waiting for UDP broadcast
> 
The first error doesn't seem to cause any interruption in the UDPListernerService, but the second one missed ~9 seconds of input. Obviously this could cause errors in a custom workout. 

Running QZ on a Mac and QZCompanion on a NordicTrack EXP7i.

Any thoughts on this and how to keep it from interfering with workouts?

Thanks!

[debugNew.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/10483596/debugNew.log)
[newcat.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/10483598/newcat.log)

**Comment by cagnulein** [comment]
@jdh65 could you try the version 3.2.6 ? i just did a patch for this
You should see the error again but not the hole of 10 seconds
Let me know
