### ISSUE TITLE
S15i Zwift 'controllable' not connecting

### ISSUE THREAD

**Issue by ferdiretief** [cagnulein/QZCompanionNordictrackTreadmill#34]
I am struggling to get all the Zwift connections to work. It seems to work intermittently but it is anyone's guess if it will work when I switch on.

After multiple restarts of the bike, app, Zwift and even laptop, I could not get it working today.

Power and cadence connects easily but controllable does not, and if it is not connected then the other two do not get the data from the app.

Can you please help with what I can do to troubleshoot?

**Comment by cagnulein** [comment]
@ferdiretief first of all describe me your setup: where QZ is running? where Zwift does?
If you are using Zwift on a PC please check this https://github.com/cagnulein/qdomyos-zwift/wiki/I-can't-connect-QZ-to-Zwift#for-zwift-pc-users

Also don't you see the Wahoo kickr virtual device from QZ to zwift?

let me know

**Comment by ferdiretief** [comment]
@cagnulein,

Thanks - I found an article with a process that seem to work (worked twice so far)
1. Turn off Bluetooth on device running QZ companion
2. Reboot device
3. Turn on S15i and wait for You to load
4. Turn on Bluetooth on QZ companion app device 
5. Start the QZ app
6. Start Zwift and it should connect

I have a galaxy S22 and watch 4 and I think the watch 4 already connected to the S22 via Bluetooth has something to do with it

**Comment by cagnulein** [comment]
great! let me know in case @ferdiretief !
