### ISSUE TITLE
Nordictrack X9i Treadmill

### ISSUE THREAD

**Issue by TryHardDev** [cagnulein/QZCompanionNordictrackTreadmill#36]
Please add support for Nordictrack X9i Treadmill, and if possible, iFit. Thanks

**Comment by cagnulein** [comment]
hi @TryHardDev first of all, did you already try to get metrics on qz?
Installing the companion app from here https://github.com/cagnulein/QZCompanionNordictrackTreadmill ?

Let me know

**Comment by TryHardDev** [comment]
Hi @cagnulein , I haven’t tried installing it yet as I thought I would check it was compatible first plus I still have an active iFit subscription. If I try to install it, is there a risk that I will break iFit and couldn’t recover it?

**Comment by cagnulein** [comment]
> If I try to install it, is there a risk that I will break iFit and couldn’t recover it?

nope, it never happens. @victorypoint can confirm this

**Comment by victorypoint** [comment]
> Okay great, I’ll give it a go then. Thanks

Right. You're iFit remains untouched and will continue to work fine. If your machine misbehaves, you can always reset and all your iFit data remains untouched (it's in the cloud).
