### ISSUE TITLE
Request: QZ to send HR data to iFIT app

### ISSUE THREAD

**Issue by onur-ie** [cagnulein/QZCompanionNordictrackTreadmill#37]
Hi,

I would like to request the ability of QZ sending the HR data to IFIT app.

Thanks in advance

**Comment by cagnulein** [comment]
@onur-ie sorry do you mean from your nordictrack/ proform device to qz? 
this is the repository of the qz companion app

**Comment by onur-ie** [comment]
My apologies, I posted to the wrong repository. It shoud have been in qdomyos-zwift.

I meant the ability of qdomyos-zwift app to transmit HR data to the iFIT app.

Should I post it again in qdomyos-zwift?

Thanks

**Comment by cagnulein** [comment]
Yes please :)
