### ISSUE TITLE
Nordictrack X22i

### ISSUE THREAD

**Issue by edpsx1** [cagnulein/QZCompanionNordictrackTreadmill#39]
Had it installed and communicating, but for some reason now the android app wont connect to the treadmill anymore.  I pushed the latest QZ via adb just now to see if I needed to reinstall the newest version and it still wont connect to it.  I double checked the IP address as well.  I set it up as the nordictrack 2950 in settings and it worked fine before.  I thought I had iFit updates disabled, but maybe they got around it and did something?  I also have the taskbar app installed to get around the home screen lockout.

**Comment by edpsx1** [comment]
I see X32i is an option on the treadmill itself.  Thats the same treadmill with a bigger screen.  Android 9 is on the tablet.

https://photos.app.goo.gl/YixTXiG4MMj3d4XMA

**Comment by cagnulein** [comment]
@edpsx1 share a debug log from qz and I will check it. Are you sure you can ping the tablet from your qz device?
