### ISSUE TITLE
Nordictrack 2450

### ISSUE THREAD

**Issue by JohnnoCO** [cagnulein/QZCompanionNordictrackTreadmill#46]
Hi - I installed on a 2450 Commercial.  Data flows fine, but incline from QZ doesnt work (up and down buttons for incline and speed do not control the treadmill at all).  Let me know how I can help enable it on this treadmill.

Also an aside - I was using an ipad as both the QZ device and for Zwift.  It disconnected after 5 seconds from Zwift consistently.  When I put the QZ app on an iphone and connected Zwift on the ipad to it it worked flawlessly.

**Comment by cagnulein** [comment]
@JohnnoCO on ipad, you need to keep qz on side view, it can't be on background 

for the incline issue, send me a debug log from qz and also a logcat from the companion. thanks!
