### ISSUE TITLE
Support for pre-2016 iFIT firmware (Android 2.2-based)?

### ISSUE THREAD

**Issue by makkonen** [cagnulein/QZCompanionNordictrackTreadmill#53]
This may be an unreasonable amount of work for a very slim userbase, so I totally understand if it's not worth it.

I just picked up a NordicTrack VR25 Recumbent Bike. It has an Android tablet built in with access to iFit, so I had hope that QZ would connect. However, when I dug into the software, it was not like any of the screenshots of iFit I had previously seen. Turns out accessing privileged mode was impossible... but also unnecessary, since a simple gesture on the settings screen will dump you to the android home screen. Yay!

Unfortunately, from there, things get disappointing. As mentioned, the underlying Android firmware is 2.2 (significantly more ancient than I expected -- I thought this device was released in 2018, but I probably got that wrong). On top of that, it looks like a pretty stripped down build, and while I can access Settings, Spare Parts, and Dev Tools, I can't actually find a way to enable ADB.

But no matter. I served up the QZ Companion APK via a local http server (the browser is so old that it can basically load no websites that use SSL, i.e. GitHub). But after downloading, I just get "Parse error: There is a problem parsing the package." I assume this means that the apk isn't built for the 2.2 target, but that's about as far as my understanding goes.

I don't know if IFit on this generation of machine even uses any of the same protocols. Is it possible to backport to this Android version? Has anyone else encountered these issues? 

Let me know if there's anything I can do to make this easier to investigate. Thanks!

**Comment by cagnulein** [comment]
hi @makkonen did you try this method first Zwift for all the Proform bikes!
https://youtu.be/QuItFYKjq_Q ?

**Comment by makkonen** [comment]
Nope! You're a wonder! I saw the NordicTrack 7950 IP entry, but didn't think to try that first --

**Comment by cagnulein** [comment]
great! let me know!
