### ISSUE TITLE
Auto Speed & Incline

### ISSUE THREAD

**Issue by scott-ainslie** [cagnulein/QZCompanionNordictrackTreadmill#56]
Not really an issue but not sure where else to put this.

It would be really great if in addition to GPX files we could upload a csv or something to make our own workouts. eg:
Time | Incline | Speed (mph)
2:00  | 3          | 5
0:45  | 10        | 8
0:30  | 8          | 5
0:45  | 10        | 8
2:00  | 2          | 5
This would then just be a playbook for a workout that we can design ourselves.

**Comment by cagnulein** [comment]
@scott-ainslie you can do this already, check as an example https://github.com/cagnulein/qdomyos-zwift/blob/master/train-programs-examples/calorie-barbara.xml

**Comment by scott-ainslie** [comment]
That looks perfect, I'll try it out. Thanks

**Comment by scott-ainslie** [comment]
This all works great with my 2950 (2019 Model - Android 7)
My only issue is that my treadmill and the app are in miles but the xml is km's so I had to manually translate all my speeds and redo the xml.

**Comment by cagnulein** [comment]
> This all works great with my 2950 (2019 Model - Android 7) My only issue is that my treadmill and the app are in miles but the xml is km's so I had to manually translate all my speeds and redo the xml.

i could add different tags, for example speed_miles to set them if you want. Please open a new ticket for this in the QZ repository. thanks
