### ISSUE TITLE
Getting auto-incline working 

### ISSUE THREAD

**Issue by TrisLumley** [cagnulein/QZCompanionNordictrackTreadmill#57]
Hi Roberto, great app, working now on Nordictrack 2950 👍 but I can't see where to enable Zwift to control the treadmill incline, or find instructions online - sorry! Any help would be very much appreciated.

Thanks
Tris

**Comment by cagnulein** [comment]
@TrisLumley hi! thanks! where are you running qz?

**Comment by TrisLumley** [comment]
On Pixel 6 phone - working great. Zwift on PC. All connected - Zwift sees WahooTread03. So it's reporting speed and incline correctly, but not controlling. Tried your meetup approach from YouTube video but no auto-incline. Thanks!

**Comment by cagnulein** [comment]
first of all, if you press the plus button on the inclination tile on qz,
the inclination changes on the treadmill?

Il giorno mer 30 ago 2023 alle 19:21 TrisLumley ***@***.***>
ha scritto:

**Comment by TrisLumley** [comment]
No, nothing happens if I press the buttons on the inclination tile

**Comment by cagnulein** [comment]
ok that's the issue
which device do you select in the companion?

Il giorno mer 30 ago 2023 alle 19:33 TrisLumley ***@***.***>
ha scritto:

**Comment by TrisLumley** [comment]
Nordictrack 2950 (22 max speed).

I just noticed that when I press the incline buttons on QZ, I hear a beep on the treadmill. So something is coming through, but not controlling

**Comment by cagnulein** [comment]
both speed and inclination doesn't work? i guess the coordinates of your
ifit tablet are different from the one that i implemented

Il giorno mer 30 ago 2023 alle 19:37 TrisLumley ***@***.***>
ha scritto:

**Comment by TrisLumley** [comment]
Yes, speed doesn't work either. I think there's a new 2950 with a screen that turns on a pivot - mine is the older 2020 version

**Comment by TrisLumley** [comment]
Can I help implement for this version?

**Comment by cagnulein** [comment]
yes there is an adb screenshot batch file on the installation folder that will help me to measure the touch area

**Comment by TrisLumley** [comment]
Do I need to run another of the batch files first? I get an adb error - no devices/emulators found

**Comment by cagnulein** [comment]
how did you install the companion in the first place? adb or browser ?

Il giorno mer 30 ago 2023 alle 20:11 TrisLumley ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
are you sure adb is still on in on the treadmill?

can you run

adb connect ip of the treadmill

first

let me know

Il giorno mer 30 ago 2023 alle 20:15 TrisLumley ***@***.***>
ha scritto:

**Comment by TrisLumley** [comment]
Got it to work by running the restart batch file. Should I email you the .PNG file?

**Comment by TrisLumley** [comment]
![30-08-2023@19-19-00 90](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/143639974/7fc98f47-d0fc-4343-a4a1-26aabd65c89e)

**Comment by cagnulein** [comment]
hi @TrisLumley i need the screenshot of your manual workout screen :) 

just a stupid question: were you in the manual workout when you tried to change the speed?

**Comment by TrisLumley** [comment]
![30-08-2023@22-05-14 32](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/143639974/d699db85-0b33-4808-a615-3b7a7c7d6a23)

**Comment by TrisLumley** [comment]
yes I was in the Manual Workout mode

**Comment by cagnulein** [comment]
ok perfect, i will compare the coordinates then

@victorypoint another tablet version?

**Comment by victorypoint** [comment]
> ok perfect, i will compare the coordinates then
> 
> @victorypoint another tablet version?

Yeah, strange that the Nordictrack 2950 (22 max speed).device doesn't work. We'll have to revisit the equations.

**Comment by cagnulein** [comment]
@victorypoint X coordinates are fine, but the Y are totally wrong...200 pixel of offset from what I saw.
@TrisLumley which ifit version do you have on the tablet?

**Comment by victorypoint** [comment]
What screen size tablet and resolution?

**Comment by cagnulein** [comment]
> What screen size tablet and resolution?

the image is the classic 1920x1080

**Comment by TrisLumley** [comment]
I will check when back home, thx for the effort guys!

**Comment by TrisLumley** [comment]
So the screen size is 22" (55cm diagonal - 475 x 270 mm)
iFit App version is 2.6.86.4458
Can't see screen resolution anywhere in the Android settings so assume is 1920x1080 as you say
It's the 2020 model of the Commercial 2950 - the existing QZ settings may be for the updated 2022 model

**Comment by TrisLumley** [comment]
Just finished a run, and now speed and incline buttons are working in QZ! I think the virtual controls on the iFit screen may have been hidden last time. So QZ is remotely controlling! But no auto-incline control by Zwift in meetup

**Comment by cagnulein** [comment]
Great News!
Did the incline work when  you were in bike mode?

Il giorno gio 31 ago 2023 alle 19:51 TrisLumley ***@***.***>
ha scritto:

**Comment by TrisLumley** [comment]
Haven't tried that - thought I was supposed to use run

**Comment by cagnulein** [comment]
yes but to validate the auto inclination is a good way .
so give it a try!

Il giorno gio 31 ago 2023 alle 19:54 TrisLumley ***@***.***>
ha scritto:

**Comment by victorypoint** [comment]
> Just finished a run, and now speed and incline buttons are working in QZ! I think the virtual controls on the iFit screen may have been hidden last time. So QZ is remotely controlling! But no auto-incline control by Zwift in meetup

Excellent news @TrisLumley. So you need to pair devices in Bike mode in order for auto-inclination to work.

- Start Zwift and go in bike mode
- Pair both Power Source and Controllable to QZ dircon (Wahoo Treadmill). Don't pair Cadence.
- Create a run meetup scheduled to start before you want to run: run meetup, default world and course, distance or duration, meetup only view, invite 1 user
- Meetups need someone to invite. You can invite Roberto or myself or create a new Zwift dummy account just for this purpose
- You can late join a meetup within 30 minutes of it's start.
