### ISSUE TITLE
Failing to connect to NordicTrack T14.0

### ISSUE THREAD

**Issue by mazatov** [cagnulein/QZCompanionNordictrackTreadmill#58]
I managed to enter privileged mode forever. I installed the app from the web.  The app on the android just allows me to barely select the model. Is that okay behavior?

In the QZ companion app I select Other as I don't see my version on the list. After setting all the options in the QZ Fitness app, it still says "Connecting" after multiple restarts. When I start the treadmill the numbers in the app don't change. 

![PXL_20230903_121439410](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/29291003/f6c71196-d5fe-4d18-80b9-37a1b9c2c12b)
![Screenshot_20230903-151609](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/29291003/29c94d7f-e3f5-47c9-8dc2-406c366cc49f)
![Screenshot_20230903-151634](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/29291003/69a07b2c-9f83-480c-bf6f-7952c6cd93f1)

**Comment by cagnulein** [comment]
could you please try this method https://github.com/cagnulein/qdomyos-zwift/issues/1591#issuecomment-1664105559 ?

**Comment by mazatov** [comment]
@cagnulein , is there a fuller guide to this? I don't even know how to start there. I bought QZ fitness app for Android and installed companion on treadmill

**Comment by cagnulein** [comment]
ok let's start from the basic, provide me a debug log so i will try to
understand which issue you have
https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

Il giorno dom 3 set 2023 alle 20:58 Mike Azatov ***@***.***>
ha scritto:

**Comment by mazatov** [comment]
Thanks! I'll get that to you tomorrow.

**Comment by mazatov** [comment]
@cagnulein , here you go. Thanks. 
[debug-Mon_Sep_4_11_06_16_2023.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/12511584/debug-Mon_Sep_4_11_06_16_2023.log)

**Comment by cagnulein** [comment]
ok the problem as I guessed it's that the companion doesn't send anything at all.
The quickest way to solve this is using the adb way.
So in order to follow you step by step, do you have a pc? if so download this https://github.com/cagnulein/QZCompanionNordictrackTreadmill/archive/refs/heads/master.zip and let me know when you have it

**Comment by mazatov** [comment]
@cagnulein , Yes I have a PC, windows 10. I downloaded the package

**Comment by cagnulein** [comment]
@mazatov perfect, 
1. decompresss the folder
2. open a windows terminal
3. go into the folder uncompressed \[InstallPackage]
4. set the grand tour pro device in the companion
5. grant the permission executing the command in the windows terminal `adb shell pm grant org.cagnulein.qzcompanionnordictracktreadmill android.permission.READ_LOGS `
6. enable adb debug for qz companion in the android setting on your bike
7. restart the companion

Let me know

**Comment by mazatov** [comment]
1,2,3 done. 
> 4. set the grand tour pro device in the companion
#4 is that on the treadmill or android app?

I don't seem to have grand tour pro in the android app

**Comment by cagnulein** [comment]
in the companion app on the bike? did you use the latest apk?

Il giorno lun 4 set 2023 alle 12:26 Mike Azatov ***@***.***>
ha scritto:

**Comment by mazatov** [comment]
@cagnulein , I got it from the [link ](https://tinyurl.com/qz-companion )in the repo. It's a treadmill, not a bike. It's ok to select still the grand tour pro?

**Comment by mazatov** [comment]
This is what the app looks like on the treadmill tablet. It looks a bit wonky and it's really hard to select your machine as the field for that selection is really small. Is that normal?
> ![PXL_20230903_121439410](https://user-images.githubusercontent.com/29291003/265263576-f6c71196-d5fe-4d18-80b9-37a1b9c2c12b.jpg) ![Screenshot_20230903-151609]

**Comment by cagnulein** [comment]
> @cagnulein , I got it from the [link ](https://tinyurl.com/qz-companion)in the repo. It's a treadmill, not a bike. It's ok to select still the grand tour pro?

yes select the grand tour pro



> This is what the app looks like on the treadmill tablet. It looks a bit wonky and it's really hard to select your machine as the field for that selection is really small. Is that normal?
> 
> > ![PXL_20230903_121439410](https://user-images.githubusercontent.com/29291003/265263576-f6c71196-d5fe-4d18-80b9-37a1b9c2c12b.jpg) ![Screenshot_20230903-151609]

yes because the other tablet are very large

**Comment by mazatov** [comment]
Thanks. Will finish the steps 1-7 later today. Not home now.

**Comment by cagnulein** [comment]
No problem, take your time.

Il giorno lun 4 set 2023 alle 13:57 Mike Azatov ***@***.***>
ha scritto:

**Comment by mazatov** [comment]
@cagnulein , I tried the steps today. 

4. Set the Grand Tour Pro in the app on the treadmill. 
5. Executed the command in windows terminal. I'm getting `adb.exe: no devices/emulators found` in the terminal. 
![PXL_20230905_092411085](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/29291003/657cf067-970d-4908-8390-4437b31fef8a)
![Screenshot 2023-09-05 122603](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/29291003/d8ccab4b-50b4-41b9-86e1-192b71158c2e)

**Comment by cagnulein** [comment]
hah sorry I missed a point, before running the adb shell command, run the 

adb connect <ipofyourtreadmill>

**Comment by mazatov** [comment]
`adb connect {IP}` ?

**Comment by cagnulein** [comment]
yes, like

adb connect 10.0.34

Il giorno mar 5 set 2023 alle 11:33 Mike Azatov ***@***.***>
ha scritto:

**Comment by mazatov** [comment]
Ok, I get the following: 

```
adb connect 10.0.0.x
cannot connect to 10.0.0.x:5555: No connection could be made because the target machine actively refused it. (10061)
```

**Comment by cagnulein** [comment]
@mazatov did you enable the adb setting in the android setting of your android tablet?

**Comment by mazatov** [comment]
I enabled USB debugging in the Treadmill tablet settings. But I still get the same message in CMD on Windows

**Comment by cagnulein** [comment]
did you try to reboot the tablet? also which android version does it have?

**Comment by mazatov** [comment]
I haven't tried rebooting yet. It's version 5.1.1

**Comment by cagnulein** [comment]
ok so the android version could be the issue.
Let's try another thing first:
in the qz companion select the c1750 device and restart the device.
Share me a fresh QZ debug log then if it doesn't work.
Thanks

**Comment by mazatov** [comment]
Here you go

**Comment by cagnulein** [comment]
@mazatov you have to attach it on the github web interface, otherwise i can't see it

**Comment by mazatov** [comment]
Sorry attached directly to the email :) 
![PXL_20230905_124806099](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/29291003/be21527e-f473-4764-a3a8-d73f2cb477d0)

**Comment by cagnulein** [comment]
did you start a workout?
can you start a workout and while you're doing the workout try to press the dump log again and share a new picture?
also can you send me the 2023-09-05.logs.txt file?

**Comment by mazatov** [comment]
@cagnulein , it worked! 

Looks like I was able to receive the data in QZ app on my phone. Phew....  So I can receive the data in QZ ( not control the treadmill). Anything else worth trying while I'm at it? :) 



![PXL_20230905_125610916](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/29291003/f6237c88-31df-44a9-8fba-fc0db9dd7c58)


![Screenshot_20230905-155446](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/29291003/66b49dce-3aa7-4959-be29-2690e32952cb)

**Comment by cagnulein** [comment]
yes in this mode we can only read data, but you unlocked it! Great!
Nope that's all :) you can now use zwift if you want :)

**Comment by mazatov** [comment]
Awesome! Dumb question about Zwift. Do I install it on my phone or treadmill tablet?

**Comment by cagnulein** [comment]
on your phone. If you use qz and zwift on the same device, remember to enable the "android notification icon" setting on qz in the experimental settings section and restart qz

Let me know

**Comment by mazatov** [comment]
Thanks! Will try Zwift out on my next run. So far seems like it found QZ

**Comment by cagnulein** [comment]
ok use the wahoo tread device in zwift

Il giorno mar 5 set 2023 alle 16:03 Mike Azatov ***@***.***>
ha scritto:

**Comment by mazatov** [comment]
Things have been working great so far! I had one question, is it possible to simultaneously sync HR from Garmin watch to QZ?

**Comment by cagnulein** [comment]
yes it depends which garmin is it. you can use both ant+ or bluetooth if
your garmin can

Il giorno dom 10 set 2023 alle 09:41 Mike Azatov ***@***.***>
ha scritto:

**Comment by mazatov** [comment]
I have an old Vivosmart HR that I sync with my Garmin connect app. How can
I tell if that would work?

**Comment by cagnulein** [comment]
ok so your only possible way is with ant+ on android device running qz

Il giorno dom 10 set 2023 alle 10:32 Mike Azatov ***@***.***>
ha scritto:

> I have an old Vivosmart HR that I sync with my Garmin connect app. How can
> I tell if that would work?
>

**Comment by cagnulein** [comment]
it seems a km to miles conversion, isn't it?

Il giorno dom 10 set 2023 alle 15:13 Mike Azatov ***@***.***>
ha scritto:

**Comment by mazatov** [comment]
Sorry what I meant was that on the treadmill I did periods of 5 min fast 1 min walk, so on IFIT you see the steps. On strava it seems to have averaged them.

**Comment by cagnulein** [comment]
check if you see it correctly on https://intervals.icu/

it could be a bug on strava (there are a lot lately)

let me know

**Comment by mazatov** [comment]
Just signed up and checked. Seems to also be the same. 

![image](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/29291003/8d9e64f6-dd8b-4431-bddb-2a222cd49d6a)

**Comment by cagnulein** [comment]
ok so i need a debug log from that session, or you need to recreate this issue with the debug log enabled to understand the issue.
Let me know

**Comment by mazatov** [comment]
Thanks,

That would be the debug log from the app on the phone or the app on the
tablet(treadmill)?

**Comment by cagnulein** [comment]
phone, this way https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by mazatov** [comment]
This is the largest file fro the day of the training. Hope this is the correct log. 

[debug-Sun_Sep_10_15_48_57_2023.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/12584397/debug-Sun_Sep_10_15_48_57_2023.log)

**Comment by mazatov** [comment]
Here you go: 
[attachments.zip](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/12584488/attachments.zip)

**Comment by cagnulein** [comment]
is the session from "Sep 10 14:50:05" ? I can only see this one

**Comment by mazatov** [comment]
That seems correct. It was a ~40-50 minute session around that time.

**Comment by cagnulein** [comment]
if so I can see only 4 speed changes, 2-3-6-8 km/h
Do you have also the ifit log from the treadmill directly?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 12 set 2023 alle ore 11:08 Mike Azatov <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
also did you see the speed changes correctly on the qz app while you were
running?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 12 set 2023 alle ore 11:09 cagnulein ***@***.***> ha
scritto:

**Comment by mazatov** [comment]
The IFIT just shows me the graph, it's the one referenced above. So the speed rose to 12km/hr. As for QZ I wasn't looking at the app while I was running so I cannot confirm that.

**Comment by cagnulein** [comment]
ok so i need the wolflog file inside of your treadmill to check if the treadmill is writing the right informations in the log that qz uses for reading the values. I guess the culript is there
Let me know

**Comment by cagnulein** [comment]
it's an hidden folder in the root of your tablet. .wolflogs directory

**Comment by mazatov** [comment]
@cagnulein , I did some more digging on this issue. I ran yesterday with intervals between 6 and 12 km/hr. Both IFIT app and QZ app show the output correctly. I was monitoring QZ app and it was changing the values on my phone as I changed them on the treadmill. However when I look at the strava app the pace graph is still very jittery. Surprisingly the watts graph on Strava is correct. So it looks like it doesn't import the graphs into Strava correctly... I also coudln't find the folder .wolflogs. 

I'm attaching all the screenshots... Sorry it looks a bit messy with images. 



Examples: 
![IFIT6](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/29291003/64212c70-cc87-4a23-a424-e5ad164130d8)

![QZ speed](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/29291003/1a55c888-cf04-4a90-b305-72059922a268)

![QZ Watts. ](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/29291003/199311d7-0ff2-470f-8afe-c542d5b6312f)

![Strava](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/29291003/6f8b6d7c-7e51-44be-bf6b-6d0a399e7bbf)


![PXL_20230918_062045526](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/29291003/26474170-21b8-4fb8-bd69-b44907edccfb)

**Comment by cagnulein** [comment]
so what about importing the fit file on http://intervals.icu ? also attach here the fit file
thanks

**Comment by mazatov** [comment]
I cannot access the file from IFIT unfortunately. I think you need to buy the membership for it. So itervals.icu is just connected with Strava.

**Comment by cagnulein** [comment]
not from ifit, the fit file generated from qz! it's inside the qz folder

**Comment by mazatov** [comment]
Ah, got it. Yeah, when I upload it to intervals it shows up correctly. 
[Downloads.zip](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/12645367/Downloads.zip)

**Comment by cagnulein** [comment]
@mazatov perfect! so it's a bug of strava! report it to them attaching also the fit file! let me know what they will say!

**Comment by mazatov** [comment]
Ok I'll email support@strava.zendesk.com

**Comment by cagnulein** [comment]
@mazatov any news?

**Comment by mazatov** [comment]
@cagnulein , nothing from strava yet. Just that they passed the ticket to their dev team 🤷

**Comment by cagnulein** [comment]
they are not fast as I am :D

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 11 ott 2023 alle ore 11:04 Mike Azatov <
***@***.***> ha scritto:

**Comment by mazatov** [comment]
Sorry, I'm on Android 14 using Files now. How do I find QZ folder? Can't
see the right folder under /android/data

Thanks

**Comment by cagnulein** [comment]
@mazatov check this app https://play.google.com/store/apps/details?id=com.marc.files

**Comment by mazatov** [comment]
Thanks, still don't see it though. An I looking in the right place?

**Comment by cagnulein** [comment]
check this https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

i'm going to bed now, it works on my pixel 6 with android 14 with that app

let me know

**Comment by mazatov** [comment]
Thanks,

I'm on Pixel 7. I enabled it to show hidden files but still don't see it. I
must be doing something wrong.

I'll dig more tomorrow

**Comment by cagnulein** [comment]
ok in case send me a video of what you are doing

Il giorno dom 12 nov 2023 alle 21:55 Mike Azatov ***@***.***>
ha scritto:

> Thanks,
>
> I'm on Pixel 7. I enabled it to show hidden files but still don't see it.
> I
> must be doing something wrong.
>
> I'll dig more tomorrow
>

**Comment by mazatov** [comment]
Here you go, I'm guessing I'm looking in the wrong folder or somehow the system files are not visible. 

https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/29291003/0ffa1a8b-acfd-4964-9863-edd1dd9c09b9

**Comment by cagnulein** [comment]
i will record the same video on the pixel this evening so we will compare it

Il giorno lun 13 nov 2023 alle 08:34 Mike Azatov ***@***.***>
ha scritto:

**Comment by mazatov** [comment]
Is the problem that I cannot see the folder, or that it's not there?

**Comment by cagnulein** [comment]
yes the folder that doesn't show there
i fixed uninstall qz, give it a try
i will also add an internal browser inside the app to avoid this

Il giorno lun 13 nov 2023 alle 20:44 Mike Azatov ***@***.***>
ha scritto:

> Is the problem that I cannot see the folder, or that it's not there?
>

**Comment by mazatov** [comment]
Ok, will I lose my files after reinstalling?

**Comment by cagnulein** [comment]
yes it's possible. if you want you can wait some days until i will add a
file browser on qz

Il giorno lun 13 nov 2023 alle 21:35 Mike Azatov ***@***.***>
ha scritto:

> Ok, will I lose my files after reinstalling?
>

**Comment by cagnulein** [comment]
Done, i'm going to test this today and then I will submit it to the google
store beta

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 13 nov 2023 alle ore 21:36 cagnulein ***@***.***> ha
scritto:

> yes it's possible. if you want you can wait some days until i will add a
> file browser on qz
>
> Il giorno lun 13 nov 2023 alle 21:35 Mike Azatov ***@***.***>
> ha scritto:
>
>> Ok, will I lose my files after reinstalling?
>>

**Comment by cagnulein** [comment]
it will be version 2.16.23

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 14 nov 2023 alle ore 09:46 cagnulein ***@***.***> ha
scritto:

> Done, i'm going to test this today and then I will submit it to the google
> store beta
>
> Roberto Viola
> Software engineer and open source enthusiast
> http://robertoviola.cloud
>
>
>
> Il giorno lun 13 nov 2023 alle ore 21:36 cagnulein ***@***.***>
> ha scritto:
>
>> yes it's possible. if you want you can wait some days until i will add a
>> file browser on qz
>>
>> Il giorno lun 13 nov 2023 alle 21:35 Mike Azatov <
>> ***@***.***> ha scritto:
>>
>>> Ok, will I lose my files after reinstalling?
>>>

**Comment by mazatov** [comment]
Hey I joined the beta testing. Did you already update it? Last one that
shows up is still from Nov 2.

**Comment by cagnulein** [comment]
@mazatov I pushed to google but they are still reviewing. they are slower than usual in the last months unfortunately :(

**Comment by mazatov** [comment]
Has it been updated in play store already? Don't see it yet:)
