### ISSUE TITLE
Proform Power T7I not connecting to QZ IOS App

### ISSUE THREAD

**Issue by activereality** [cagnulein/QZCompanionNordictrackTreadmill#60]
Hello,

  I am using this on: Proform Power T7L. It is not listed in available devices on either the Companion app - which I already installed - or the ios QZ App.

  I used the latest rev from this repot.

  I have tried a few different device selections from both sides - i.e. 'Other' from QZ-Companion (on the proform) and each of the available Proform selections in the QZ IOS app.

   For this testing I had the IP address entered into the 'Proform IP' in the QZ IOS App.

   Is this Proform device not supported by the current revision of QZ and QZ-Companion?

**Comment by cagnulein** [comment]
Hi Aaron, let's send me a debug log and i will check it!

https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F


Il giorno lun 11 set 2023 alle 19:35 Aaron Christiano <
***@***.***> ha scritto:

**Comment by activereality** [comment]
[debug-Mon_Sep_11_13_38_17_2023.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/12579353/debug-Mon_Sep_11_13_38_17_2023.log)
debug attached

**Comment by cagnulein** [comment]
ok i will check it tomorrow

Il giorno lun 11 set 2023 alle 20:43 Aaron Christiano <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
Hi, the main issue in this log is that you set the wrong setting with the ip.
Blank the "Proform IP" setting and press ok, and set instead the IP in the Nordictrack 2950 IP setting
Send me then a fresh debug log
Thanks

**Comment by activereality** [comment]
OH, Gotcha. I just updated that setting- then ran back through all selectable proform options (and left it blank) with no luck either.

Attached is the debug log.

I also noted that the Android settings screen has two IP addresses listed.  xxx.200 and xxx.201, however, the IFIT has the xxx.200 listed as its ip, so that is the one i have been using. Pics are attached of that as well.

thanks for the assistance
!
![IMG_3419](https://github.com/cagnulein/QZCompan
![IMG_3418](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/45473517/7dc01651-9a66-4892-9c8a-179f628a6219)
ionNordictrackTreadmill/assets/45473517/1551cdb3-94b0-4350-a2a9-4ce98e8b40f8)



[debug-Tue_Sep_12_08_32_27_2023.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/12587008/debug-Tue_Sep_12_08_32_27_2023.log)

**Comment by cagnulein** [comment]
I can't see the metrics so it means that the companion can't read them. Can you try to follow these steps https://github.com/cagnulein/qdomyos-zwift/issues/1591#issuecomment-1664105559 ?

**Comment by activereality** [comment]
Do you want me to select the Grand Tour Pro Device in the qz-companion app on the treadmill? or leave it at `other`?

**Comment by cagnulein** [comment]
gran tour pro. of course follow also the other steps. thanks

**Comment by activereality** [comment]
command not found found: adb - from both mac and windows terminals

**Comment by cagnulein** [comment]
you can download adb from here
https://github.com/cagnulein/QZCompanionNordictrackTreadmill/archive/refs/heads/master.zip
inside the installpackage folder

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 12 set 2023 alle ore 15:57 Aaron Christiano <
***@***.***> ha scritto:

**Comment by activereality** [comment]
install package/adp (application) does not seem to attempt to install anything - ran as admin as well. (windows). the command still not recognized. I also pulled a fresh copy of the master.zip and tried to run the adp app from there, same result.

**Comment by cagnulein** [comment]
you don't have to install anything, it's a portable executable.
Just go into the directory from a command line shell and run the adb command from the installpackage subfolder

Show me a screenshot of the error in case

**Comment by activereality** [comment]
oh i was running from the file directory window - not from cli

**Comment by activereality** [comment]
ok, ran that from PS. where do i `enable adb debug for qz companion`? Is that from the command line after adb install, from the qz-companion app on the treadmill, or from the qz app on 'device-x' (ie phone, tablet)?

**Comment by cagnulein** [comment]
@activereality in the developer settings of the tablet's treadmill

**Comment by activereality** [comment]
did you mean in Treadmill/Developer Options - Set the `Select debug app` to qz companion?
images attached:

![IMG_3422](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/45473517/e6a31a5c-9e0c-4641-a475-06dd503943a5)
![IMG_3420](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/45473517/e550ccf7-b096-41f1-8cc9-c28e3f19562a)

**Comment by activereality** [comment]
good deal - restarting the machine now - then will attempt to reconnect and send you the next debug txt

**Comment by cagnulein** [comment]
Sounds good.
I will be out for a couple of hours, so i hope to check it again later or
tomorrow

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 12 set 2023 alle ore 16:53 Aaron Christiano <
***@***.***> ha scritto:

**Comment by activereality** [comment]
debug file attached:

[debug-Tue_Sep_12_09_58_43_2023.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/12587926/debug-Tue_Sep_12_09_58_43_2023.log)

**Comment by cagnulein** [comment]
quickly checked but i don't see anything at all. but it seems like it's not
the right debug log.

could you please do it again?

Il giorno mar 12 set 2023 alle 17:01 Aaron Christiano <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
i'm checking from the mobile and i can't see any message but maybe it's
better to look at it from a pc.
i will let you know tomorrow

Il giorno mar 12 set 2023 alle 17:17 Aaron Christiano <
***@***.***> ha scritto:

**Comment by activereality** [comment]
good deal - ty sir

**Comment by cagnulein** [comment]
Confirmed, I can't see anymore the messages from the companion. All the steps were ok of the link? I'm intereseted in the "grant" command output for example
Let me know

**Comment by activereality** [comment]
what 'Grant' command are you referring to?

**Comment by cagnulein** [comment]
this one 

`grant the permission with adb shell pm grant org.cagnulein.qzcompanionnordictracktreadmill android.permission.READ_LOGS from a mac or a pc`

**Comment by activereality** [comment]
oh - that needs to be run _after_ the adb application from installPackage?

**Comment by activereality** [comment]
if so - am i to run `adb shell pm grant org.cagnulein.qzcompanionnordictracktreadmill android.permission.READ_LOGS` from cli?

**Comment by activereality** [comment]
hmm, i am running it with `.\adb` trying the other now

**Comment by cagnulein** [comment]
please share a screenshot

**Comment by activereality** [comment]
alright - from cmdPrompt, i got this after running adb and then the grant command:
`adb shell pm grant org.cagnulein.qzcompanionnordictracktreadmill android.permission.READ_LOGS
* daemon not running; starting now at tcp:5037
* daemon started successfully
adb.exe: no devices/emulators found`

**Comment by activereality** [comment]
is there something else i need to start first?

**Comment by activereality** [comment]
going to cycle power to the treadmill

**Comment by cagnulein** [comment]
> * adb.exe: no devices/emulators found`

means adb is not enabled in the treadmill

**Comment by activereality** [comment]
not seeing an ADB option in settings/system/developer options - what path is this supposed to be located at and what is the specific name i am looking for in that path?

**Comment by cagnulein** [comment]
actually should be here 

https://user-images.githubusercontent.com/45473517/267369571-e6a31a5c-9e0c-4641-a475-06dd503943a5.jpeg

but I can't see it. So i guess your treadmill doesn't support this feature.

Ok plan b. Let's try to set the device in the companion as "c1750". Then restart the treadmill and send me again a debug log from qz.
Thanks

**Comment by activereality** [comment]
[debug-Wed_Sep_13_09_23_47_2023.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/12598651/debug-Wed_Sep_13_09_23_47_2023.log)

**Comment by cagnulein** [comment]
mmm still the same. Could you please go into the companion app, press the dump log button and send me a picture of the text box in the companion?

**Comment by activereality** [comment]
![IMG_3426](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/45473517/a979fbf9-3511-48d7-b452-41117695ef07)
![IMG_3424](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/45473517/e2a73578-9db8-47d2-b9e7-54ebf81344b1)

**Comment by cagnulein** [comment]
can you share here the 2023-09-13 file?

Il giorno mer 13 set 2023 alle 16:56 Aaron Christiano <
***@***.***> ha scritto:

**Comment by activereality** [comment]
What file? debug from qz? or am i attempting to download a file from the treadmill companion app?

**Comment by activereality** [comment]
good deal - how do i get to that file - and then get it transferred to my local pc?

**Comment by cagnulein** [comment]
you can download a file browser like cx file explorer from the treadmill
browser

Il giorno mer 13 set 2023 alle 17:53 Aaron Christiano <
***@***.***> ha scritto:

**Comment by activereality** [comment]
Downloaded and installed that file explorer. Where is that file located?

**Comment by cagnulein** [comment]
/sdcard/.wolflogs

Il giorno gio 14 set 2023 alle 22:44 Aaron Christiano <
***@***.***> ha scritto:

**Comment by activereality** [comment]
Alright. I had to enable see hidden files. I have found the wolf logs. Not seeing a way to send these txt files though.

**Comment by activereality** [comment]
Not the best share haha. 

![image](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/45473517/e1d5456a-431d-42cd-8c7f-dd0a60bb1576)

![image](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/45473517/a6b2be9e-2a69-4049-8d4c-d9d7fd64075e)

**Comment by cagnulein** [comment]
i'm interested in lines with "changed".

for example changed kph to ...

Il giorno sab 16 set 2023 alle 00:29 Aaron Christiano <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
Ok last possibility: does your treadmill tablet have a usb port?

**Comment by cagnulein** [comment]
@activereality are you still interested?
