### ISSUE TITLE
certificate issue

### ISSUE THREAD

**Issue by IzzySoft** [cagnulein/QZCompanionNordictrackTreadmill#61]
What happened to your signing key, @cagnulein? My updater just rejected your latest APK:

> "org.cagnulein.qzcompanionnordictracktreadmill_84.apk" is signed by a key that is not allowed:
cf44dcb5ef1e1231bddd4194a4b8b245d1aec5cb217affba0414cb1ea5bf326d

Looks like you switched to a (different) debug key. Unfortunately you also forgot to increase `versionCode`, so the wrongly signed APK replaced the correct one, in effect making your app invisible in my repo as if it would not be listed.

For details on the certificate check, please see [How to keep your key safe and what measures to take for the event of loss?](https://f-droid.org/2023/09/03/reproducible-builds-signing-keys-and-binary-repos.html#lessons-learned-2-how-to-keep-your-key-safe-and-what-measures-to-take-for-the-event-of-loss)

**Comment by cagnulein** [comment]
strange the apk is built from the CI here on github. I will check it

Il giorno lun 16 ott 2023 alle 20:53 Izzy ***@***.***> ha
scritto:

**Comment by IzzySoft** [comment]
Hope the CI doesn't create a new cert on each run? I've enabled strict checking in my repo only recently, must have been shortly after your last release before the current one. Pretty much looks like that's the case:

3.4

```
Signer #1 certificate DN: C=US, O=Android, CN=Android Debug
Signer #1 certificate SHA-256 digest: dc50eabd6ffdfe074ab34dbab84f14c387eb515727e55869ec20294c6b9bdc30
Signer #1 certificate SHA-1 digest: c48df6ea3b1f163c64410a844f7fa33d38a1cf13
Signer #1 certificate MD5 digest: 67595633c68496686e6955871d111b82
Signer #1 key algorithm: RSA
```

3.5

```
Signer #1 certificate DN: C=US, O=Android, CN=Android Debug
Signer #1 certificate SHA-256 digest: 1d54590357354bb2f65018ef785386d9bbb402c45b38fc310136b83340a54d80
Signer #1 certificate SHA-1 digest: 99c2d0c5f1116cf4e44d23ba2b461787cb4ed319
Signer #1 certificate MD5 digest: 86f94417ddf4544e45c0a75a50b2e730
Signer #1 key algorithm: RSA
```

3.6

```
Signer #1 certificate DN: C=US, O=Android, CN=Android Debug
Signer #1 certificate SHA-256 digest: cf44dcb5ef1e1231bddd4194a4b8b245d1aec5cb217affba0414cb1ea5bf326d
Signer #1 certificate SHA-1 digest: bc27fcecdbfe77375ac2172be752f5be1533ac92
Signer #1 certificate MD5 digest: 9865386893c85e5cb72f990957865338
Signer #1 key algorithm: RSA
```

That makes updates impossible for the average Jane & Joe.

Btw: any plans to switch to a release key, and drop the debug flag?

**Comment by cagnulein** [comment]
yes i guess the CI does this, so you have this issue from the begin, right?


Il giorno lun 16 ott 2023 alle 21:06 Izzy ***@***.***> ha
scritto:

**Comment by IzzySoft** [comment]
That could be, yes – but I only noticed once strict checking was enabled. Given the APK size, your app is among those where I kept the latest release(s) and dropped older ones that had "offending keys".

**Comment by IzzySoft** [comment]
So did you find the culprit, @cagnulein? I see another release with the next debug key :cry:

**Comment by cagnulein** [comment]
no i didn't check yet, it's on my todo list but i have more urgent things
now :(

Il giorno ven 20 ott 2023 alle 01:10 Izzy ***@***.***> ha
scritto:

**Comment by IzzySoft** [comment]
I see. Then I'll disable updates here for now and restore the last version with the matching certificate (to get rid of the continuous warning whenever I build an index here). Please keep me updated about progress.

**Comment by cagnulein** [comment]
Thanks, I will.

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 20 ott 2023 alle ore 09:43 Izzy ***@***.***> ha
scritto:

**Comment by IzzySoft** [comment]
My monthly reminder popped up again, so I hope you don't mind the ping: Any progress made?

**Comment by cagnulein** [comment]
hi thanks, nope, not yet. autumn and winter are busy seasons for an indoor
workout app :)

Il giorno mer 1 nov 2023 alle 17:32 Izzy ***@***.***> ha
scritto:

**Comment by IzzySoft** [comment]
OK, understood :wink: Hope you don't mind another ping when my updater reminds me again (Dec 1st), should it not be resolved by then?

**Comment by cagnulein** [comment]
absolutely! please keep it :)

Il giorno mer 1 nov 2023 alle 21:20 Izzy ***@***.***> ha
scritto:

**Comment by IzzySoft** [comment]
Oof… your bot is faster than you as it doesn't need sleep… You might need to tell it that it made the wrong decision with adding that label :wink:

**Comment by cagnulein** [comment]
done ;)

**Comment by IzzySoft** [comment]
Thanks! As my "update bot" again fetched a release with the wrong signature: what are the chances we get this solved before new years eve – or did your "autumn and winter" above mean you won't make it before spring? I had set your app to "static" (which means "monthly checks" instead of daily ones, to have a reminder), but it starts to get a little annoying :wink:

**Comment by cagnulein** [comment]
sorry but i don't have time for this now, as i said these months (yes i
mean till march) are a nightmare for me.

if you want you can remove it until i will fix it

thanks again

Il giorno ven 1 dic 2023 alle 21:26 Izzy ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
eheheh ok mid april sounds fine to me!
thanks for understanding, much appreciated
Have a great weekend!

Il giorno ven 1 dic 2023 alle 21:36 Izzy ***@***.***> ha
scritto:

**Comment by IzzySoft** [comment]
You too – and done!

**Comment by cagnulein** [comment]
@IzzySoft i'm working on this on these days. I will keep you updated!

**Comment by IzzySoft** [comment]
Eh… my reminder popped up again and confused me. Guess we simply forgot to close this issue – and I can remove the reminder? Or did I miss something? Proper cert seems in place now. (checks the linked PR) Yeah, looks like I just forgot to remove the reminder. Closing here then; should I indeed have missed something, feel free to reopen :wink:

And thanks again!
