### ISSUE TITLE
Proform Studio Bike Pro Incompatibility

### ISSUE THREAD

**Issue by lukewolpert** [cagnulein/QZCompanionNordictrackTreadmill#63]
I am unable to get anything but zeros from QZ with the proform studio bike pro (NOT the studio bike pro 22, but rather, the one with the 10” screen and only 22 resistance levels) after following the Readme exactly. 

I see the “22” model listed as an option in the qz-companion android app, but not the “non-22” studio bike pro. I have tried selecting the studio bike pro 22 in the companion app, and I have also tried selecting “other” in the companion app, but in both cases, I get zeros from QZ.

I would like to contribute to this project by solving this issue for myself and future users, but this is a little different than the dev work I do professionally… Any recommended reading material I should start with? Or could you point me to which files in the repo are most likely to be relevant here, and/or where the bike tablet’s file system is most likely getting written to with the cadence/resistance/etc. data? Thanks in advance.

**Comment by cagnulein** [comment]
hi @lukewolpert first of all try to set the device on the companion to c1750 and restart the bike, let me know if it's better. otherwise we will go with another trick

**Comment by lukewolpert** [comment]
Hey @cagnulein thanks for your response. I have followed your suggestion, but unfortunately still get zeros. Any other ideas?

**Comment by cagnulein** [comment]
yes sure, the gran tour trick. Follow this https://github.com/cagnulein/qdomyos-zwift/issues/1591#issuecomment-1664105559

**Comment by lukewolpert** [comment]
@cagnulein Thanks! I was able to get real-time statistics after following those steps, but only when I have the bike's IP address set in the *treadmill* settings for "Nordictrack 2950 IP". It does not work if I instead set the IP address in the *bike* settings under "TDF Companion IP". Should I be concerned about this? I'm not sure if this means it's going to think I'm on a treadmill and thus give me inaccurate numbers.

Secondly, how can I setup automatic resistance? This bike has digital resistance, so I figure it should be possible. My purpose in purchasing this bike is to build a setup where I can set a wattage I want to ride at, and have the bike automatically adjust resistance in response to speed changes in order to keep me at that particular wattage. I have QZ running on an iPhone and Swift running on an iPad, but I also have Windows PCs and other devices I can make use of, if necessary. I read on reddit that I might be able to create a custom route in zwift that keeps me at a particular wattage, and then export that workout to QZ and do everything from QZ without swift? Is that the best approach? Thanks in advance.

**Comment by cagnulein** [comment]
> Thanks! I was able to get real-time statistics after following those steps, but only when I have the bike's IP address set in the _treadmill_ settings for "Nordictrack 2950 IP". It does not work if I instead set the IP address in the _bike_ settings under "TDF Companion IP". Should I be concerned about this? I'm not sure if this means it's going to think I'm on a treadmill and thus give me inaccurate numbers.

Great! For the issue let's check if you have same problem even with the last beta. 
send me an email to roberto.viola83 at gmail.com indicating this ticket and if you are on android or iOS and I will send you it. 





> Secondly, how can I setup automatic resistance? This bike has digital resistance, so I figure it should be possible. My purpose in purchasing this bike is to build a setup where I can set a wattage I want to ride at, and have the bike automatically adjust resistance in response to speed changes in order to keep me at that particular wattage (I understand that the wattage won't be accurate without a power meter, but that's fine with me as long as it's consistent). I have QZ running on an iPhone and Swift running on an iPad, but I also have Windows PCs and other devices I can make use of, if necessary. I read on reddit that I might be able to create a custom route in zwift that keeps me at a particular wattage, and then export that workout to QZ and do everything from QZ without swift? Is that the best approach? Thanks in advance.

For auto resistance on iOS for this kind of bike I'm working on it on the task [#1721](https://github.com/cagnulein/qdomyos-zwift/pull/1732)

For Windows instead is already available. In order to have it running download the windows version from here https://github.com/cagnulein/qdomyos-zwift/suites/17739244097/artifacts/1015870996 , setup it for your bike (so you can also see if the bike ip setting here works) and then also enable the adb setting in the proform settings. In order to work, adb must be working on the bike.

Let me know
