### ISSUE TITLE
NordicTrack EXP 10i / QZ on iOS - Setting speed/inc not working

### ISSUE THREAD

**Issue by Aspvik** [cagnulein/QZCompanionNordictrackTreadmill#66]
Hi!
Just installed QZ Companion on a NordicTrack EXP 10i treadmill using the browser method (method 2). I also bought the iOS QZ app. Settings read fine from companion/treadmill, but I'm not able to set speed or incline from the phone. My main motivation for using QZ are the Training programs, which obviously is not working.

- In the QZ Companion I've tried both "Other" and "EXP 7i treadmill", both options allows the QZ app to read settings.
- On the iOS app I had to set the IP of the treadmill on the 1950 IP setting for it to start working (reading).

I don't have a windows computer, but I have both macos and linux.

What can I do to help fix the issue?

**Comment by cagnulein** [comment]
hi! when you press the plus button on the speed tile on qz do you see a touchscreen reaction on the treadmill tablet?

**Comment by Aspvik** [comment]
Hi. No reaction on the tablet. By looking at som other issues I understand that the app works by simulating clicks on the touch screen? I can add that the interface for controlling inc / speed on the latest iFit are vertical sliders, if that matters.

**Comment by cagnulein** [comment]
> By looking at som other issues I understand that the app works by simulating clicks on the touch screen?

yes



> I can add that the interface for controlling inc / speed on the latest iFit are vertical sliders, if that matters.

yes for sure they have to be enabled.



> No reaction on the tablet.

ok so it means that we need to use the adb method. Are you able to connect to adb from your pc or mac to the treadmill?

**Comment by Aspvik** [comment]
I will try later this evening. Currently at work.

Basically you want me to uninstall the companion app, and then reinstall it using the adb method?

**Comment by cagnulein** [comment]
nope no need to reinstall it. just try to check if adb method works (for example doing an adb connect <ip>)

**Comment by Aspvik** [comment]
I have adb installed on my mac now.
I'm getting a response when pinging the treadmill.
However `adb connect <IP>` gives:
`failed to connect to '192.168.50.69:5555': Connection refused`

**Comment by cagnulein** [comment]
Perfect send me an email to roberto.viola83 at gmail.com indicating this ticket and I will send you the new beta for iOS that will handle adb command on iOS. Then we will test it and we will have only to calibrate the coordinates of your touchscreen

Let me know

**Comment by Aspvik** [comment]
A little update: I followed the steps in the .bat file, and now I'm getting touch reactions on the screen. Seems like they are just off a little.

I'll send you an email.

**Comment by Aspvik** [comment]
![IMG_1446](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/13474155/18b60ebe-f975-48c3-b541-bb84d5884890)
I'm a little curious to how this might work. You see that the sliders are so large that the cover the nearby speed/inc buttons.

**Comment by cagnulein** [comment]
> A little update: I followed the steps in the .bat file, and now I'm getting touch reactions on the screen. Seems like they are just off a little.
> 
> 
> 
> I'll send you an email.

sent! enable the adb remote setting in the proform nordictrack setting and reboot qz

what I expect from this beta is that you can see a reaction in the touchscreen when you press the plus/minus button. don't mind about the coordinates, they will be wrong for sure, if it works i will add your coordinates

**Comment by cagnulein** [comment]
> ![IMG_1446](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/13474155/18b60ebe-f975-48c3-b541-bb84d5884890)
> 
> I'm a little curious to how this might work. You see that the sliders are so large that they cover the nearby speed/inc buttons.

yes it's the same for all the nordictrack devices, don't worry it will work with the right coordinates, have faith in me :)

**Comment by Aspvik** [comment]
Okey. I have the beta installed now. What next?

**Comment by cagnulein** [comment]
i wrote here https://github.com/cagnulein/QZCompanionNordictrackTreadmill/issues/66#issuecomment-1806843579

**Comment by Aspvik** [comment]
Sorry, didn't see that.
If I enable developer mode and usb debugging on the treadmill, and adb remote on the iphone; the screen reacts when clicking the + or - on the iPhone (inc only. +/- speed nothing happens).

Some additional info:
- This happened also before I installed the iOS beta you sent me. Except then I didn't active adb remote on the iPhone.
- It seems that the coordinates are different in the beta than they were before.

**Comment by cagnulein** [comment]
that's perfect!
so if it works also with adb remote off it means that we need just to set
the right coordinates in the companion
i will add them on monday

Il giorno sab 11 nov 2023 alle 19:27 Rune Aspvik ***@***.***>
ha scritto:

**Comment by Aspvik** [comment]
You know I have been trying so much, it's difficult to say exactly the config I had before. But one question: Is it suppose to only work in privileged mode with usb debugging enabled? That's the only way I've been getting reactions in the touch panel.

As for the coordinates I've been playing around and at least I can tell you that on this treadmill the inc is on X=100, and the speed is on X=1180.

The bottom of the lowest inc (-3%) is at Y=660
The bottom of the lowest speed (1km/t) is at Y=600

**Comment by cagnulein** [comment]
> You know I have been trying so much, it's difficult to say exactly the config I had before. But one question: Is it suppose to only work in privileged mode with usb debugging enabled? 

yes

> As for the coordinates I've been playing around and at least I can tell you that on this treadmill the inc is on X=100, and the speed is on X=1180.
> 
> 
> 
> The bottom of the lowest inc (-3%) is at Y=660
> 
> The bottom of the lowest speed (1km/t) is at Y=600

could you also check highest one for both?

**Comment by Aspvik** [comment]
I will get the highest points for you tomorrow. Kids are sleeping next to the treadmill now.

For me getting into privileged mode and enabling usb debugging every time I go for a run is a bit to much hassle. Hopefully in the future there will be a simpler way. Good luck with the project :)

**Comment by cagnulein** [comment]
> I will get the highest points for you tomorrow. Kids are sleeping next to the treadmill now.

ehehe i'm in the same boat with my daughter 

> 
> For me getting into privileged mode and enabling usb debugging every time I go for a run is a bit to much hassle. Hopefully in the future there will be a simpler way. Good luck with the project :)

i guess i miswrote: you don't need everytime, you need the first time only. it should keep them

**Comment by Aspvik** [comment]
Okey, I understand. Good :)

Is this how it works (more or less): The iOS app talks to the companion app via HTTP requests, and then the companion app triggers touch events on top of the iFit app?

**Comment by cagnulein** [comment]
exactly

Il giorno sab 11 nov 2023 alle 21:05 Rune Aspvik ***@***.***>
ha scritto:
