### ISSUE TITLE
Proform Pro C10U - resistance & companion issues

### ISSUE THREAD

**Issue by sheffieldhometech** [cagnulein/QZCompanionNordictrackTreadmill#67]
[debug-Thu_Nov_16_17_56_59_2023.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/13382644/debug-Thu_Nov_16_17_56_59_2023.log)
[debug-Thu_Nov_16_17_38_17_2023.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/13382645/debug-Thu_Nov_16_17_38_17_2023.log)
[debug-Thu_Nov_16_17_55_45_2023.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/13382646/debug-Thu_Nov_16_17_55_45_2023.log)

Backstory : brand new bike arrived yesterday - got it all working with companion (except for resistance control) 
Tried a few times but struggled to get adb to trigger touch events from iOS. USB debugging reset itself (to off) on reboot.

today I updated some features through ifit admin. And the companion wouldn’t connect to the iOS app. Did a factory reset on bike - started again and still wouldn’t connect. 

Any ideas let me know.

See debug files for no connection from companion to iOS qz-fitness

**Comment by cagnulein** [comment]
yes I don't see any frames at all.
Are you sure that the bike is well connected to the network? same wifi
channel? can you ping the bike from the phone?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 16 nov 2023 alle ore 20:47 sheffieldhometech <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
> did “connect” briefly with strange behaviour - tiles would increase with no bike input logs here…
> [debug-Fri_Nov_17_08_59_16_2023.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/13389836/debug-Fri_Nov_17_08_59_16_2023.log)

ok i can see here some messages

`Fri Nov 17 08:59:17 2023 1700211557567 Debug: /Users/cagnulein/qdomyos-zwift/src/nordictrackifitadbbike.cpp void nordictrackifitadbbike::processPendingDatagrams() Message ::  "[28] 695260 17:41:02.3511 [Trace:FitPro] Changed Watts to: 35"`

so the companion and the network is definitely working but the main issue I guess it's the ifit app that it's not logging all the time.

So we need to follow this workaround https://github.com/cagnulein/qdomyos-zwift/issues/1591#issuecomment-1664105559

Let me know!

**Comment by sheffieldhometech** [comment]
- [ X] install the companion

- [X ] set the grand tour pro device in the companion
- [ X] grant the permission with adb shell pm grant org.cagnulein.qzcompanionnordictracktreadmill android.permission.READ_LOGS from a mac or a pc
- 
- [ ] enable adb debug for qz companion
- [ ] restart the companion

Cannot see the adb debug option in qz companion?

The tiles are not updating or changing at all - 0s on all tiles

**Comment by cagnulein** [comment]
> Cannot see the adb debug option in qz companion?

it's in the developer setting of the proform tablet.

**Comment by sheffieldhometech** [comment]
![IMG_8479](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/116870217/ff1dbb4b-09d7-4934-b735-4d7789673b3c)

nothing in debug section that catches my eye

**Comment by cagnulein** [comment]
"select debug app" that one

**Comment by sheffieldhometech** [comment]
[debug-Fri_Nov_17_11_03_53_2023.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/13390894/debug-Fri_Nov_17_11_03_53_2023.log)

nice - tiles are back to updating. All working as before - except resistance just reads 0. (This was working previously with your beta iOS app)

**Comment by cagnulein** [comment]
probably the newest ifit update doesn't send the resistance value anymore. You can try to check yourself while you're riding

run a 

`adb shell logcat -b all -d`

check about "Changed Resistance", I guess there is nothing unfortunately :(

**Comment by sheffieldhometech** [comment]
11-17 12:14:38.868  1792  1792 V mono-stdout: [1] [Trace:Workout] User initiated Resistance change from 1 to 8

Any good?

I could revert to factory settings.....or return the bike and try with a different one

**Comment by cagnulein** [comment]
are there any other string similar to this when you change the resistance? if so I can add this too! Let me know!

**Comment by sheffieldhometech** [comment]
looks like different thing when **physical resistance buttons** pressed:

11-17 12:37:05.684  1792  1919 V mono-stdout: [4] [Trace:FitPro] KeyCode observed: [KeyObj Code:Resistance12, RawKeyCode:18446744073709551485, TimePressed:94, TimeHeld:70]

**touch event resistance** change:

11-17 12:37:10.929  1792  1792 V mono-stdout: [1] [Trace:Workout] User initiated Resistance change from 12 to 5
11-17 12:37:10.932  1792  1920 V mono-stdout: [5] [Trace:FitnessConsole] Clamped Resistance from 5 to 5.

11-17 12:37:10.932  1792  1920 V mono-stdout: BitField: Resistance
11-17 12:37:10.932  1792  1920 V mono-stdout: FitnessValue: Resistance
11-17 12:37:11.036  1792  3779 V mono-stdout: [28] [Trace:Benchmark] AverageTimer "ResistanceTimer": 100.18 millis over 4 samples. Completed Resistance change from 12 to 5

11-17 12:37:11.036  1792  3779 V mono-stdout: [28] [Trace:FitPro] Changed Resistance to: 5
11-17 12:37:11.036  1792  3779 V mono-stdout: [28] [Trace:FitnessConsole] ReadWriteDataCmd completed with success = True


this is from ctrl+f in the terminal on mac

if there is a way to log for a longer time I could get all the data (rawkeycode) from all of the physical buttons which may be helpful.

let me know if i can help best way possible.

**Comment by cagnulein** [comment]
sure run 

`adb shell logcat -b all > log.txt`

and do all the tests.

Then press CTRL-C and we should have a complete scenario!
That's so interesting!

**Comment by sheffieldhometech** [comment]
[log.txt](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/13391993/log.txt)

Ok - this looks good thanks!

I went all the way up to 25 - pushing each physical button - and then back down to 2 (smaller value of buttons).

I then went up to 25 in jumps using the touch controls - and back down to 1 using touch.

**Comment by cagnulein** [comment]
@sheffieldhometech in this log I saw that qz companion send already the resistance

```
11-17 12:53:17.494  1432  1432 I QZ:Service: 11-17 12:47:25.397  1792  4002 V mono-stdout: [34] [Trace:FitPro] Changed Resistance to: 0
11-17 12:53:18.659  1432  1432 I QZ:Service: 11-17 12:53:17.494  1432  1432 I QZ:Service: 11-17 12:47:25.397  1792  4002 V mono-stdout: [34] [Trace:FitPro] Changed Resistance to: 0
11-17 12:53:19.846  1432  1432 I QZ:Service: 11-17 12:53:18.659  1432  1432 I QZ:Service: 11-17 12:53:17.494  1432  1432 I QZ:Service: 11-17 12:47:25.397  1792  4002 V mono-stdout: [34] [Trace:FitPro] Changed Resistance to: 0
11-17 12:53:21.024  1432  1432 I QZ:Service: 11-17 12:53:20.690  1792  3778 V mono-stdout: [27] [Trace:FitPro] Changed Resistance to: 2
11-17 12:53:22.235  1432  1432 I QZ:Service: 11-17 12:53:21.024  1432  1432 I QZ:Service: 11-17 12:53:20.690  1792  3778 V mono-stdout: [27] [Trace:FitPro] Changed Resistance to: 2
11-17 12:53:23.394  1432  1432 I QZ:Service: 11-17 12:53:22.235  1432  1432 I QZ:Service: 11-17 12:53:21.024  1432  1432 I QZ:Service: 11-17 12:53:20.690  1792  3778 V mono-stdout: [27] [Trace:FitPro] Changed Resistance to: 2
11-17 12:53:24.557  1432  1432 I QZ:Service: 11-17 12:53:24.260  1792  3779 V mono-stdout: [28] [Trace:FitPro] Changed Resistance to: 4
11-17 12:53:25.748  1432  1432 I QZ:Service: 11-17 12:53:24.557  1432  1432 I QZ:Service: 11-17 12:53:24.260  1792  3779 V mono-stdout: [28] [Trace:FitPro] Changed Resistance to: 4
11-17 12:53:26.910  1432  1432 I QZ:Service: 11-17 12:53:26.452  1792 11913 V mono-stdout: [55] [Trace:FitPro] Changed Resistance to: 6
11-17 12:53:28.116  1432  1432 I QZ:Service: 11-17 12:53:26.910  1432  1432 I QZ:Service: 11-17 12:53:26.452  1792 11913 V mono-stdout: [55] [Trace:FitPro] Changed Resistance to: 6
11-17 12:53:29.272  1432  1432 I QZ:Service: 11-17 12:53:28.369  1792 11913 V mono-stdout: [55] [Trace:FitPro] Changed Resistance to: 8
11-17 12:53:30.439  1432  1432 I QZ:Service: 11-17 12:53:29.272  1432  1432 I QZ:Service: 11-17 12:53:28.369  1792 11913 V mono-stdout: [55] [Trace:FitPro] Changed Resistance to: 8
11-17 12:53:31.653  1432  1432 I QZ:Service: 11-17 12:53:30.439  1432  1432 I QZ:Service: 11-17 12:53:29.272  1432  1432 I QZ:Service: 11-17 12:53:28.369  1792 11913 V mono-stdout: [55] [Trace:FitPro] Changed Resistance to: 8
11-17 12:53:32.810  1432  1432 I QZ:Service: 11-17 12:53:31.937  1792  4002 V mono-stdout: [34] [Trace:FitPro] Changed Resistance to: 12
11-17 12:53:34.045  1432  1432 I QZ:Service: 11-17 12:53:33.847  1792  2036 V mono-stdout: [19] [Trace:FitPro] Changed Resistance to: 15
11-17 12:53:35.202  1432  1432 I QZ:Service: 11-17 12:53:34.045  1432  1432 I QZ:Service: 11-17 12:53:33.847  1792  2036 V mono-stdout: [19] [Trace:FitPro] Changed Resistance to: 15
11-17 12:53:36.419  1432  1432 I QZ:Service: 11-17 12:53:36.034  1792  2035 V mono-stdout: [18] [Trace:FitPro] Changed Resistance to: 18
11-17 12:53:37.584  1432  1432 I QZ:Service: 11-17 12:53:36.419  1432  1432 I QZ:Service: 11-17 12:53:36.034  1792  2035 V mono-stdout: [18] [Trace:FitPro] Changed Resistance to: 18
11-17 12:53:38.808  1432  1432 I QZ:Service: 11-17 12:53:38.227  1792  1920 V mono-stdout: [5] [Trace:FitPro] Changed Resistance to: 21
11-17 12:53:39.962  1432  1432 I QZ:Service: 11-17 12:53:38.808  1432  1432 I QZ:Service: 11-17 12:53:38.227  1792  1920 V mono-stdout: [5] [Trace:FitPro] Changed Resistance to: 21
11-17 12:53:41.138  1432  1432 I QZ:Service: 11-17 12:53:40.143  1792  1920 V mono-stdout: [5] [Trace:FitPro] Changed Resistance to: 25
11-17 12:53:42.298  1432  1432 I QZ:Service: 11-17 12:53:41.138  1432  1432 I QZ:Service: 11-17 12:53:40.143  1792  1920 V mono-stdout: [5] [Trace:FitPro] Changed Resistance to: 25
11-17 12:53:43.502  1432  1432 I QZ:Service: 11-17 12:53:42.298  1432  1432 I QZ:Service: 11-17 12:53:41.138  1432  1432 I QZ:Service: 11-17 12:53:40.143  1792  1920 V mono-stdout: [5] [Trace:FitPro] Changed Resistance to: 25
11-17 12:53:44.675  1432  1432 I QZ:Service: 11-17 12:53:43.511  1792 11913 V mono-stdout: [55] [Trace:FitPro] Changed Resistance to: 21
11-17 12:53:45.890  1432  1432 I QZ:Service: 11-17 12:53:45.418  1792 11913 V mono-stdout: [55] [Trace:FitPro] Changed Resistance to: 18
11-17 12:53:47.066  1432  1432 I QZ:Service: 11-17 12:53:45.890  1432  1432 I QZ:Service: 11-17 12:53:45.418  1792 11913 V mono-stdout: [55] [Trace:FitPro] Changed Resistance to: 18
11-17 12:53:48.267  1432  1432 I QZ:Service: 11-17 12:53:47.321  1792  5848 V mono-stdout: [39] [Trace:FitPro] Changed Resistance to: 15
11-17 12:53:49.450  1432  1432 I QZ:Service: 11-17 12:53:48.978  1792  3778 V mono-stdout: [27] [Trace:FitPro] Changed Resistance to: 12
11-17 12:53:50.655  1432  1432 I QZ:Service: 11-17 12:53:49.450  1432  1432 I QZ:Service: 11-17 12:53:48.978  1792  3778 V mono-stdout: [27] [Trace:FitPro] Changed Resistance to: 12
11-17 12:53:51.827  1432  1432 I QZ:Service: 11-17 12:53:50.882  1792  4002 V mono-stdout: [34] [Trace:FitPro] Changed Resistance to: 10
11-17 12:53:53.011  1432  1432 I QZ:Service: 11-17 12:53:52.251  1792  2035 V mono-stdout: [18] [Trace:FitPro] Changed Resistance to: 8
11-17 12:53:54.175  1432  1432 I QZ:Service: 11-17 12:53:53.011  1432  1432 I QZ:Service: 11-17 12:53:52.251  1792  2035 V mono-stdout: [18] [Trace:FitPro] Changed Resistance to: 8
11-17 12:53:55.345  1432  1432 I QZ:Service: 11-17 12:53:54.260  1792  4002 V mono-stdout: [34] [Trace:FitPro] Changed Resistance to: 6
11-17 12:53:56.524  1432  1432 I QZ:Service: 11-17 12:53:55.896  1792  1987 V mono-stdout: [10] [Trace:FitPro] Changed Resistance to: 4
11-17 12:53:57.742  1432  1432 I QZ:Service: 11-17 12:53:57.539  1792  1995 V mono-stdout: [13] [Trace:FitPro] Changed Resistance to: 2
11-17 12:53:58.919  1432  1432 I QZ:Service: 11-17 12:53:57.742  1432  1432 I QZ:Service: 11-17 12:53:57.539  1792  1995 V mono-stdout: [13] [Trace:FitPro] Changed Resistance to: 2
11-17 12:54:00.082  1432  1432 I QZ:Service: 11-17 12:53:58.919  1432  1432 I QZ:Service: 11-17 12:53:57.742  1432  1432 I QZ:Service: 11-17 12:53:57.539  1792  1995 V mono-stdout: [13] [Trace:FitPro] Changed Resistance to: 2
11-17 12:54:01.258  1432  1432 I QZ:Service: 11-17 12:54:00.238  1792  3779 V mono-stdout: [28] [Trace:FitPro] Changed Resistance to: 1
11-17 12:54:02.491  1432  1432 I QZ:Service: 11-17 12:54:01.258  1432  1432 I QZ:Service: 11-17 12:54:00.238  1792  3779 V mono-stdout: [28] [Trace:FitPro] Changed Resistance to: 1
11-17 12:54:03.683  1432  1432 I QZ:Service: 11-17 12:54:02.710  1792  1926 V mono-stdout: [6] [Trace:FitPro] Changed Resistance to: 8
11-17 12:54:04.860  1432  1432 I QZ:Service: 11-17 12:54:04.356  1792  3779 V mono-stdout: [28] [Trace:FitPro] Changed Resistance to: 14
11-17 12:54:06.044  1432  1432 I QZ:Service: 11-17 12:54:04.860  1432  1432 I QZ:Service: 11-17 12:54:04.356  1792  3779 V mono-stdout: [28] [Trace:FitPro] Changed Resistance to: 14
11-17 12:54:07.230  1432  1432 I QZ:Service: 11-17 12:54:06.091  1792 11913 V mono-stdout: [55] [Trace:FitPro] Changed Resistance to: 15
11-17 12:54:08.448  1432  1432 I QZ:Service: 11-17 12:54:07.361  1792  4002 V mono-stdout: [34] [Trace:FitPro] Changed Resistance to: 16
11-17 12:54:09.653  1432  1432 I QZ:Service: 11-17 12:54:09.374  1792  5848 V mono-stdout: [39] [Trace:FitPro] Changed Resistance to: 25
11-17 12:54:10.847  1432  1432 I QZ:Service: 11-17 12:54:09.653  1432  1432 I QZ:Service: 11-17 12:54:09.374  1792  5848 V mono-stdout: [39] [Trace:FitPro] Changed Resistance to: 25
11-17 12:54:12.017  1432  1432 I QZ:Service: 11-17 12:54:10.847  1432  1432 I QZ:Service: 11-17 12:54:09.653  1432  1432 I QZ:Service: 11-17 12:54:09.374  1792  5848 V mono-stdout: [39] [Trace:FitPro] Changed Resistance to: 25
11-17 12:54:13.261  1432  1432 I QZ:Service: 11-17 12:54:12.017  1432  1432 I QZ:Service: 11-17 12:54:10.847  1432  1432 I QZ:Service: 11-17 12:54:09.653  1432  1432 I QZ:Service: 11-17 12:54:09.374  1792  5848 V mono-stdout: [39] [Trace:FitPro] Changed Resistance to: 25
11-17 12:54:14.425  1432  1432 I QZ:Service: 11-17 12:54:13.261  1432  1432 I QZ:Service: 11-17 12:54:12.017  1432  1432 I QZ:Service: 11-17 12:54:10.847  1432  1432 I QZ:Service: 11-17 12:54:09.653  1432  1432 I QZ:Service: 11-17 12:54:09.374  1792  5848 V mono-stdout: [39] [Trace:FitPro] Changed Resistance to: 25
11-17 12:54:15.659  1432  1432 I QZ:Service: 11-17 12:54:15.349  1792  2036 V mono-stdout: [19] [Trace:FitPro] Changed Resistance to: 8
11-17 12:54:16.819  1432  1432 I QZ:Service: 11-17 12:54:15.659  1432  1432 I QZ:Service: 11-17 12:54:15.349  1792  2036 V mono-stdout: [19] [Trace:FitPro] Changed Resistance to: 8
11-17 12:54:18.055  1432  1432 I QZ:Service: 11-17 12:54:16.819  1432  1432 I QZ:Service: 11-17 12:54:15.659  1432  1432 I QZ:Service: 11-17 12:54:15.349  1792  2036 V mono-stdout: [19] [Trace:FitPro] Changed Resistance to: 8
11-17 12:54:19.225  1432  1432 I QZ:Service: 11-17 12:54:18.055  1432  1432 I QZ:Service: 11-17 12:54:16.819  1432  1432 I QZ:Service: 11-17 12:54:15.659  1432  1432 I QZ:Service: 11-17 12:54:15.349  1792  2036 V mono-stdout: [19] [Trace:FitPro] Changed Resistance to: 8
11-17 12:54:20.413  1432  1432 I QZ:Service: 11-17 12:54:19.789  1792  1926 V mono-stdout: [6] [Trace:FitPro] Changed Resistance to: 1
11-17 12:54:21.595  1432  1432 I QZ:Service: 11-17 12:54:20.413  1432  1432 I QZ:Service: 11-17 12:54:19.789  1792  1926 V mono-stdout: [6] [Trace:FitPro] Changed Resistance to: 1
11-17 12:54:22.773  1432  1432 I QZ:Service: 11-17 12:54:21.595  1432  1432 I QZ:Service: 11-17 12:54:20.413  1432  1432 I QZ:Service: 11-17 12:54:19.789  1792  1926 V mono-stdout: [6] [Trace:FitPro] Changed Resistance to: 1
11-17 12:54:23.947  1432  1432 I QZ:Service: 11-17 12:54:22.773  1432  1432 I QZ:Service: 11-17 12:54:21.595  1432  1432 I QZ:Service: 11-17 12:54:20.413  1432  1432 I QZ:Service: 11-17 12:54:19.789  1792  1926 V mono-stdout: [6] [Trace:FitPro] Changed Resistance to: 1
```

didn't you get in the main QZ app during the test?

**Comment by sheffieldhometech** [comment]
I didn't have the app open on my phone during that test (i had laptop on my knee)- so i cannot confirm or deny this.

I did just check again and the iOS tiles (beta edition) do not update with resistance changes. just remains on '1'.

**Comment by sheffieldhometech** [comment]
[log.txt](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/13392442/log.txt)
[debug-Fri_Nov_17_13_39_33_2023.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/13392448/debug-Fri_Nov_17_13_39_33_2023.log)


see attached logs  -the tiles did update this time! but it wasn't perfect. quite a few resistances were skipped on the tiles. id say it worked about 60% of the time.... did the same as before..up and down the resistance buttons - then the same with the touch slider.

**Comment by cagnulein** [comment]
did you hit all the resistance values or were you skipping them?

I'm seeing these steps

```
Current Resistance: 0
Current Resistance: 1
Current Resistance: 2
Current Resistance: 4
Current Resistance: 6
Current Resistance: 8
Current Resistance: 15
Current Resistance: 18
Current Resistance: 21
Current Resistance: 25
Current Resistance: 12
Current Resistance: 6
Current Resistance: 2
Current Resistance: 8
Current Resistance: 12
Current Resistance: 18
Current Resistance: 25
Current Resistance: 8
Current Resistance: 4
Current Resistance: 1
```

which one are missing in your opinion? I need just one so i can verify it in both logs. Thanks!

**Comment by sheffieldhometech** [comment]
So with the buttons I didn't skip any. I went from 0 >2>4>6>8>10>12>15>18>21>25>21>18>15>12>10>8>6>4>2
![IMG_8480](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/116870217/653dc17c-65fc-4d8b-b705-6aff7f3c5598)


With the slider its harder to be precise so I definitely missed some and jumped much more.

```
//Buttons here
Current Resistance: 0
Current Resistance: 1
Current Resistance: 2
Current Resistance: 4
Current Resistance: 6
Current Resistance: 8
Current Resistance: 15
Current Resistance: 18
Current Resistance: 21
Current Resistance: 25
Current Resistance: 12
Current Resistance: 6
Current Resistance: 2
//touch screen slider from here
Current Resistance: 8
Current Resistance: 12
Current Resistance: 18
Current Resistance: 25
Current Resistance: 8
Current Resistance: 4
Current Resistance: 1
```

It looks like resistance of 10 was missed on way up and way down - so maybe that is a good one to investigate!

**Comment by cagnulein** [comment]
ok seems to be here

11-17 13:40:34.967  1792  5848 V mono-stdout: [39] [Trace:FitPro] Changed
Resistance to: 10

let's try find out why the companion is not parsing it!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 17 nov 2023 alle ore 15:19 sheffieldhometech <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
new companion
https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.3.19/QZCompanionNordictrackTreadmill.apk

Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 17 nov 2023 alle ore 15:28 cagnulein ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
got the issue! i'm fixing it now!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 17 nov 2023 alle ore 15:23 cagnulein ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
ok let me know, in case send me a adb log and i will check it, i did a
single line mod but maybe i did it wrong

Il giorno ven 17 nov 2023 alle 17:19 sheffieldhometech <
***@***.***> ha scritto:

**Comment by sheffieldhometech** [comment]
wait for new version before sending logs? or do you want adb logs from 3.3.19?

**Comment by cagnulein** [comment]
the 3.3.19 is the one with the fix, github made confusion. so yes please send me the log (i will probably not able to check them today anymore but I don't think I did it wrong)

**Comment by sheffieldhometech** [comment]
Ok - this is strange behaviour....
Resistance matches PERFECTLY when adb connected from mac to bike & logging with your logging script.
Resistance matches ~95% when adb connected from mac & not logging script
Resistance matches poorly when "adb kill-server" run on mac.

ADB logs wouldn't be much use as you will see perfect resistance matching.
I have attached QZ logs from entire testing session (not sure how useful)

If this can be sorted (keeping adb alive without mac) would be great to adjust Resistance from QZ tile (& zwift etc)

**Comment by cagnulein** [comment]
so there was an improvement from the previous one?

Il giorno ven 17 nov 2023 alle 18:14 sheffieldhometech <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
> Ok - this is strange behaviour.... Resistance matches PERFECTLY when adb connected from mac to bike & logging with your logging script. Resistance matches ~95% when adb connected from mac & not logging script Resistance matches poorly when "adb kill-server" run on mac.
> 
> ADB logs wouldn't be much use as you will see perfect resistance matching. I have attached QZ logs from entire testing session (not sure how useful)
> 
> If this can be sorted (keeping adb alive without mac) would be great to adjust Resistance from QZ tile (& zwift etc)

did you upload other logs? i can't see them

**Comment by sheffieldhometech** [comment]
[debug-Fri_Nov_17_16_47_10_2023.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/13395104/debug-Fri_Nov_17_16_47_10_2023.log)
sorry - here

**Comment by cagnulein** [comment]
ok i will check in the next days. pizza time now :)

Il giorno ven 17 nov 2023 alle 19:00 sheffieldhometech <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
> Resistance matches PERFECTLY when adb connected from mac to bike & logging with your logging script.
> Resistance matches ~95% when adb connected from mac & not logging script
> Resistance matches poorly when "adb kill-server" run on mac.

let me try to understand this better: when you're talking about the "logging script" are you talking about `"adb shell logcat -b all > log.txt"` ?

if so, what I can do, it's what [@samkenw](https://github.com/samkenw) asked here https://github.com/cagnulein/QZCompanionNordictrackTreadmill/issues/65#issuecomment-1817484359 so running the same thread that you run in the mac, in the QZ directly without using the companion.

let me know if it's the case!

**Comment by sheffieldhometech** [comment]
Yes you have understood correctly.

On another note - what exercise bike do you use?
Not totally happy with this ProForm C10U so I will probably return it.
Very happy to give you as many logs as you need up until that point

It sounds like running an app directly on the bike's tablet to communicate with zwift would be a very neat solution.

**Comment by cagnulein** [comment]
> Yes you have understood correctly.

ok perfect, I will proceed with that modification in the next days

> On another note - what exercise bike do you use?

TDF 4



> Not totally happy with this ProForm C10U so I will probably return it.

so bad to hear this, why if I could ask?



> It sounds like running an app directly on the bike's tablet to communicate with zwift would be a very neat solution.

actually qz can run directly on the tablet with the adb method.

**Comment by sheffieldhometech** [comment]
Great  -you do amazing work! 

Thankyou - maybe I will get this - but proform customer service has now put me off proform bikes - Wow. 
Maybe I will try echelon? looks like they have good success with QZ?

The bike was poor quality - it was clearly a budget option. old android 7 tablet slow to boot. It wouldn't last me more than 2 years

**Comment by cagnulein** [comment]
yes for sure echelon are cheap but good option, remember to buy one without a tablet :)
