### ISSUE TITLE
X32i issue with changing Speed/Incline from QZ Fitness android app

### ISSUE THREAD

**Issue by guerillagorilla** [cagnulein/QZCompanionNordictrackTreadmill#68]
I have an x32i (which I assume is a NTL39019 version - since it is an older unit).  I have successfully the QZCompanion app on the tread mill and have it configured for X32iNTL39019 Treadmill.  I have also installed the QZ Fitness Android apk and enabled Norditrack 10 and Treadmill Speed Forcing in the Settings -> Treadmill Option.    

Once the treadmill rebooted, I performed a manual workout to check connectivity.  I see the following:

- Values are read on the QZ Fitness app for both speed (though off by about .6mph) and incline
- When I modify the speed or incline manually, I see the values reflected
- When I attempt to change the values from QZ Fitness app, there is no change observed.  I have enabled both "Show taps" & "Pointer Location" in Developer Options but no changes are observed

When manually sending "input swipe 100 200 300 400 200" in adb shell, I can see the changes on the screen as expected - just no output from QZ Fitness App.

I have included logs and screenshots for assistance.
[QZ_Logs.zip](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/13443375/QZ_Logs.zip)

I assume it's probably something simple since I see previous tickets for the x32i and my guess is config within the QZ Fitness App.  Let me know if there's anything I can do to help resolve this>

Love your work so far!

**Comment by cagnulein** [comment]
Thanks I will check this tomorrow

Il giorno mer 22 nov 2023 alle 19:40 guerillagorilla <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
ok perfect, with QZ are you on android or ios?

**Comment by guerillagorilla** [comment]
Ah, sorry forgot to mention.  QZ is installed on Android.

**Comment by guerillagorilla** [comment]
After joining the beta, upgrading QZ to v2.14.0 and restarting the treadmill.  I am still able to connect and see the data received but unable to see any swipes when changing Speed or Inclination on QZ.  One thing I noticed is that, as with the previous version, though I am getting data I see "Connecting..." underneath the Pause/Stop button on the main screen in QZ.  I see data received so not sure if this is an issue or not.

My QZ settings are as follows:
- Treadmill Settings -> Treadmill Speed Forcing (True)
- Treadmill Settings -> Proform/Norditrack Options -> Norditrack 10 (True) 
- Treadmill Settings -> Proform/Norditrack Options -> Norditrack 2950 IP (10.0.0.125)
- Treadmill Settings -> Proform/Norditrack Options -> ADB Remote (True)

Just to double check, I can still see lines with "input swipe 100 200 300 400 200" in adb shell.

Logs attached with changes showing QZ button attempts + manual input from the me pressing speed/incline on the screen of the treadmill:
[QZ_logs.zip](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/13452008/QZ_logs.zip)

**Comment by cagnulein** [comment]
> upgrading QZ to v2.14.0

do you mean upgrading from? you should see version 2.16.23

> though I am getting data I see "Connecting..." underneath the Pause/Stop button on the main screen in QZ. I see data received so not sure if this is an issue or not.

yeah for wifi devices, that label is useless, it's about bluetooth ones

could you please create a debug log from QZ https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F ?

**Comment by guerillagorilla** [comment]
Got it, and thanks!  QZ must not have updated correctly from the Google Play store.  I checked again this morning and saw there was a new version to upgrade to - I upgraded successfully and see 2.16.22 (not 2.16.23).  I don't there's a way in the Play store to download a specific version.  I guess I could download the nightly release from qdomyos-zwift releases, let me know if you think it will help.

Tested again with this new version (2.16.22) and collected additional logs from QZ.   In this version speed all data is read as expected.  There is a change here in sending from QZ:

- I can still not send any speed updates from QZ or see changes on screen that indicates a reception of data to the iFit window
- For incline, I can see sporadic changes but only when lowering the incline.  It's not consistent when pressing it that the keyswipe is observed on screen (or change is made) .  When pressing increase incline there is no input observed or change on incline.

QZ log below:
[debug-Fri_Nov_24_10_24_49_2023.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/13460743/debug-Fri_Nov_24_10_24_49_2023.log)

**Comment by guerillagorilla** [comment]
A couple more comments here.  

I see in the log you are sending input swipes so I copied those input swipes from the logs and restarted the a manual start.  When sending the input swipes I read from the logs to the treadmill via ADB, they are clearly sent to iFIT and both up/down, and speed/incline changes are observed.

It seems as though QZ is attempting to send the input swipe coordinates but they never make it to the iFIT screen.  Only via ADB shell am I able to see any changes

**Comment by cagnulein** [comment]
ok thanks, I wil check it asap, I'm actually overwhelmed by tasks here :(

**Comment by cagnulein** [comment]
ok 

> It seems as though QZ is attempting to send the input swipe coordinates but they never make it to the iFIT screen. Only via ADB shell am I able to see any changes

if so are you able to take a bug report from your phone so i can check if the adb connection from your phone to your treadmill is ok? i guess that's the issue

**Comment by guerillagorilla** [comment]
[Device_logcat.txt](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/13467614/Device_logcat.txt)
[treadmill_logcat.txt](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/13467615/treadmill_logcat.txt)

Attached are both treadmill and UE (device) logcat logs.  After connection and reception of speed/incline on device from treadmill, I attempted to send speed or incline and am not seeing the swipes again.  In device logscat log I can see  input swipe being sent but then "sendCmmand ADB is not connect"

2023-11-26 12:38:28.107 21094-21184 qDomyos-Zwift           org.cagnulen.qdomyoszwift            D  " >> input swipe 75 718 75 704 200"
2023-11-26 12:38:28.107 21094-21184 QZ:AdbRemote            org.cagnulen.qdomyoszwift            D  sendCommand false input swipe 75 718 75 704 200
2023-11-26 12:38:28.107 21094-21184 QZ:AdbRemote            org.cagnulen.qdomyoszwift            E  sendCommand ADB is not connected!

**Comment by cagnulein** [comment]
yes that's the issue. Is it possible that you have already 1 adb connection from the mac/pc to the treadmill? As far as I know only one device is allowed at a time.
is the adb port of the treadmill 5555?

**Comment by ahuffman** [comment]
I have the same issue on an x22i where I receive the info in the QZ android app, but am unable to control the treadmill via the app.

**Comment by ahuffman** [comment]
no, I didn't try anything with adb, but did enable adb usb debugging, rebooted the treadmill, and tried again with no change.  I have identical settings to what @guerillagorilla mentioned in QZ app.  

Just to note, my iFit system is fully updated to latest system version.

**Comment by cagnulein** [comment]
for sure we need to go with the adb method since ifit is blocking the
classic method. give it a try

Il giorno mer 29 nov 2023 alle 18:46 Andrew J. Huffman <
***@***.***> ha scritto:

**Comment by ahuffman** [comment]
Sorry, which part would you like me try on my end, happy to help out solving this.

**Comment by cagnulein** [comment]
@ahuffman let's first the adb method with the qz beta. are you on android or ios?

**Comment by ahuffman** [comment]
Android.  I'll sign up for the beta and give it a shot

**Comment by cagnulein** [comment]
ok enable the adb remote setting under the nordictrack treadmill section.
what we should see is a touchscreen event on your treadmill if you change
the inclination or speed on qz
let me know

Il giorno mer 29 nov 2023 alle 19:48 Andrew J. Huffman <
***@***.***> ha scritto:

**Comment by noaa-rfss** [comment]
Just an update here from my side - I upgraded to 2.16.22 and at first saw the same issue with the previous version, however after rebooting everything (device & treadmill) I was strangely able to both receive the data from the treadmill on speed and incline as well as control speed/incline using the buttons on my device.

I mentioned before that I saw a difference before on speed where it was .6 off...This is because I'm an idiot and forgot to change it to mph 🤣.  After sorting that out, every thing works correctly between treadmill and android device.

Now to figure out how to get zwift to control the incline/speed for me so I do have to manually do it...

let me know if you want or need more logs from my side as a baseline for this version.

**Comment by guerillagorilla** [comment]
Just an update here from my side - I upgraded to 2.16.22 and at first saw the same issue with the previous version, however after rebooting everything (device & treadmill) I was strangely able to both receive the data from the treadmill on speed and incline as well as control speed/incline using the buttons on my device.

I mentioned before that I saw a difference before on speed where it was .6 off...This is because I'm an idiot and forgot to change it to mph 🤣.  After sorting that out, every thing works correctly between treadmill and android device.

Now to figure out how to get zwift to control the incline/speed for me so I do have to manually do it...

Let me know if you want or need more logs from my side as a baseline for this version.

**Comment by ahuffman** [comment]
No luck on 2.16.24.  I turned on debug logs in the QZ app, but not sure where they get put on the device to upload them.  Could you please let me know where?

**Comment by cagnulein** [comment]
@ahuffman were you be able with this build?

**Comment by cagnulein** [comment]
you need to uninstall first the play store one and then install this one
it's a trial of 15 minutes that I can unlock for tou, send me an email to
roberto.viola83 at gmail.com

Il giorno ven 1 dic 2023 alle 23:11 Andrew J. Huffman <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
@ahuffman any news?
