### ISSUE TITLE
Installation failed on Norditrack T12.0

### ISSUE THREAD

**Issue by vauhallan** [cagnulein/QZCompanionNordictrackTreadmill#7]
Hi,
Installation fails with ADB script (connection refused) with USB debug mode at on.
It is also impossible to install the APK directly by downloading it from the tablet browser integrated into the treadmill.
The tablet is in Android Lollipop version in my treadmill Norditrack T12.0
Any idea ?
In dadvance, thanks a lot for your help.

**Comment by cagnulein** [comment]
could you please post all the log? are you using this version https://github.com/cagnulein/QZCompanionNordictrackTreadmill/tree/master/InstallPackage ?

**Comment by cagnulein** [comment]
which error do you have installing it directly?

**Comment by vauhallan** [comment]
Here the logs : 


Log generated at 14:51:07,42 16/10/2022 for IP 192.168.1.234 
 
Pinging 192.168.1.234 ... 

Pinging 192.168.1.234 with 32 bytes of data:
Reply from 192.168.1.234: bytes=32 time=63ms TTL=64

Ping statistics for 192.168.1.234:
    Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 63ms, Maximum = 63ms, Average = 63ms
 
Connecting to treadmill via ADB ... 
 
disconnected everything
* daemon not running; starting now at tcp:5037
* daemon started successfully
cannot connect to 192.168.1.234:5555: No connection could be made because the target machine actively refused it. (10061)

**Comment by cagnulein** [comment]
maybe adb over ip is not available on your tablet. can you try with the adb push function?

**Comment by vauhallan** [comment]
Adb connect failed from a linux devices (impossbile to go to phush fonction)
root@rpi2:~# adb connect 192.168.1.234:5555
failed to connect to '192.168.1.234:5555': Connection refused

Do you have an apk installed on Android Lollipop ? I can download it directly from tablet's browser....

**Comment by cagnulein** [comment]
> Adb connect failed from a linux devices (impossbile to go to phush fonction)
> root@rpi2:~# adb connect 192.168.1.234:5555
> failed to connect to '192.168.1.234:5555': Connection refused

use the usb cable instead of the ip

> Do you have an apk installed on Android Lollipop ? I can download it directly from tablet's browser....

what's happen when you install it? what does it show?

**Comment by vauhallan** [comment]
> > Adb connect failed from a linux devices (impossbile to go to phush fonction)
> > root@rpi2:~# adb connect 192.168.1.234:5555
> > failed to connect to '192.168.1.234:5555': Connection refused
> 
> use the usb cable instead of the ip
> 
> > Do you have an apk installed on Android Lollipop ? I can download it directly from tablet's browser....
> 
> what's happen when you install it? what does it show?

The error message is parse error : there was a problem parsing the package

**Comment by cagnulein** [comment]
@vauhallan just to be sure, are you sure you're using the apk contained here https://github.com/cagnulein/QZCompanionNordictrackTreadmill/tree/master/InstallPackage ?

**Comment by victorypoint** [comment]
Wireless ADB is tricky with some tablets. Can you confirm your computer and your tablet are connected via WiFi to same wireless router and not one to wifi and other to Ethernet,?

**Comment by vauhallan** [comment]
> Wireless ADB is tricky with some tablets. Can you confirm your computer and your tablet are connected via WiFi to same wireless router and not one to wifi and other to Ethernet,?

Yes confirmed. Same SSID wifi and same network

**Comment by vauhallan** [comment]
> @vauhallan just to be sure, are you sure you're using the apk contained here https://github.com/cagnulein/QZCompanionNordictrackTreadmill/tree/master/InstallPackage ?

Yes

**Comment by vauhallan** [comment]
> @vauhallan did you try using the USB cable?

Yes without success: 
1- No device list displays on "adb.exe devices "
2- No new device entry on "Device Manager" (PC)

For your information concerning tablet : 
Model number : AOSP on Drone
Android version : 5.1.1
Kernel Version : 3.4.39
Bulld number : 20180301

**Comment by cagnulein** [comment]
are you sure that developer options and adb are enabled in the tablet settings? (stupid questions I know) @vauhallan

**Comment by victorypoint** [comment]
If you can do ADB via a USB cable and wireless, there are many Reddit posts with suggestions to try such as this one - https://stackoverflow.com/questions/37267335/android-studio-wireless-adb-error-10061. Hopefully there is something in there that will help.

**Comment by vauhallan** [comment]
> are you sure that developer options and adb are enabled in the tablet settings? (stupid questions I know) @vauhallan

YEs on developper mode and USB debugging....

**Comment by cagnulein** [comment]
did you check the @victorypoint thread? @vauhallan

**Comment by victorypoint** [comment]
I've just added an additional file to the install package at https://github.com/cagnulein/QZCompanionNordictrackTreadmill/tree/master/InstallPackage. I was having trouble establishing an ADB connection to a couple of my Android phones. The solution was to establish an ADB connection with USB cable connected first (the additional AdbWinUsbApi.dll file is required) to establish a trust. Then all subsequent ADB connections over Wifi worked.

Within the Install Package folder, use the following sequence to try a connection with USB cable connected:

ping [IP of Android device]
adb disconnect
adb kill-server
adb connect [IP of Android device]
adb devices -l

Hope this may help you @vauhallan

**Comment by vauhallan** [comment]
Installation successful with method 2 (witch adb).
Before and after treadmill power cycle, the application launch failed with following message : 
Unfortunately ,  QZ Companion Norditrack Treadmill has stopped

**Comment by cagnulein** [comment]
hi @vauhallan I need a debug report to understand which is the issue. Also did you allow all the permission to the companion in the tablet settings?

**Comment by nreichenbach** [comment]
Hello, On a Nordictrack S10i, i have the same problem than @vauhallan 
![IMG_8519](https://user-images.githubusercontent.com/63663168/202899514-58f6d466-1f3e-4cb8-92ad-488d9c0853af.jpeg)
![IMG_8520](https://user-images.githubusercontent.com/63663168/202899517-383c9a2e-f56d-4d87-84b5-546e973b98b4.jpeg)

**Comment by cagnulein** [comment]
@nreichenbach are you sure you are using this apk https://github.com/cagnulein/QZCompanionNordictrackTreadmill/commit/390da38810f2c7082b8ee955bea11d73af3023b6 ?

**Comment by nreichenbach** [comment]
![IMG_0416](https://user-images.githubusercontent.com/63663168/202908463-e49ce111-8133-4974-968d-36fe8577f3c0.jpeg)

**Comment by cagnulein** [comment]
ok @nreichenbach could you provide a adb logcat?

**Comment by nreichenbach** [comment]
@cagnulein , sorry i don't know how to do it ? im on OSX

**Comment by cagnulein** [comment]
@nreichenbach check here for install adb on mac https://www.xda-developers.com/install-adb-windows-macos-linux/

**Comment by nreichenbach** [comment]
Ty, but the problem, i have an iMac 27" which is far away from my bike and i don't have a connection and long usb cable

**Comment by nreichenbach** [comment]
Ty, but sorry i have an iMac 27" far away from my bike and i don't have and long usb cable and i don't have Wireless debugging on my Android.

**Comment by cagnulein** [comment]
@nreichenbach adb logcat or a bug report directly from the tablet is needed in order to understand the issue

i don't know if your tablet can take a bug report

let me know

**Comment by cagnulein** [comment]
@nreichenbach @vauhallan i should have fixed this with the last apk. could you please try it?

**Comment by vauhallan** [comment]
> @nreichenbach @vauhallan i should have fixed this with the last apk. could you please try it?

The installation is working file now .
But I have a issue concerning the choice of my treadmill. I can’t validate my choice .
![Uploading D435D7E8-F0FA-4D97-BA37-3094ED58714C.jpeg…]()

**Comment by vauhallan** [comment]
![BCCDA9F1-D98D-4F52-9396-C3F5B9D848D6](https://user-images.githubusercontent.com/7457545/210754344-e69f099b-d08c-4543-acdc-334fbdad90f0.jpeg)
