### ISSUE TITLE
2021 NordicTrack 2950 QZ Controls Not Working

### ISSUE THREAD

**Issue by jsenitza** [cagnulein/QZCompanionNordictrackTreadmill#71]
Hopefully not duplicating something as I'm new to this app / community. But I have the QZ Companion app running successfully on my 2021 Nordic Track 2950 and I'm able to receive speed and incline stats on my iPhone through the QZ app but the controls don't work on speed or incline. I've tried a few different things on trying to get this to work but nothing seems to be working yet.

I'm on a mac so I did manually run the adb install / monkey / grant permission steps - everything seems to be working outside of the controls in the QZ app now. 

Thanks in advance for the help! Let me know what I can provide to help.

**Comment by cagnulein** [comment]
ok let me know if you need help!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 5 gen 2024 alle 01:35 Jacob Senitza ***@***.***>
ha scritto:
