### ISSUE TITLE
Unable to get priviliged mode, unable to install QZ Companion.

### ISSUE THREAD

**Issue by droomurray** [cagnulein/QZCompanionNordictrackTreadmill#72]
NordicTrack X9i unable to find a method to get in to privlaged mode so unable to install QZ Companion.

This unit has updated so it basically no longer has iFit - so any tap screen methods don't seem valid ?
This unit does not have a reset button, just a USB port.

App version - 2.19.5
Part number - 356444
Firmware Version - 3.3.0722.1.0.5.1.9 
Brainboard Version - 141
Display ICON Part number - 365339

Using safe mode was able to determine that ...

Android version 2.2 ?
model number sec_smdkv210
Kernel version 2.6.32.9

In safe mode I have been able to transfer the QZ Companion APK but because its in safe mode I can not launch or install.

**Comment by cagnulein** [comment]
@victorypoint could you help us on this?

android version 2.2 @droomurray it seems a very old one. I guess you shouldn't need to use the qzcompanion at all.

In QZ app, remove the 2950 ip setting and put it instead on the Proform IP setting and restart qz

Let me know!

Attach a debug log https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F if it still doesn't work

**Comment by droomurray** [comment]
oooo now I do feel a bit silly, I do NOT need the companion app after all by using the other IP setting !

**Comment by cagnulein** [comment]
so it works?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 5 gen 2024 alle ore 13:52 Drew Murray <
***@***.***> ha scritto:

**Comment by droomurray** [comment]
So when I use the machine manually I now see the data via IP on the QZ fitness App and can change speed / incline of the machine from the App.

My actual aim is to get the machine working via QZ Fitness to talk to my ipad so I can do the iFit workouts - as I use iFit on my 3 other macines (rower, cross trainer and bike) 

BUT 

I have just read I think I will need to run either QZ fitness or iFit on an Android device i.e. using iPhone and iPad wont work ?

**Comment by cagnulein** [comment]
i didn't develop the ifit treadmill bridge, only for bike.
It involves a lot of effort and only few people wants this unfortunately.
If you can wait I will develop it, but not before than this summer i guess. I'm literally overwhelmed by QZ users requests unfortunately

**Comment by cagnulein** [comment]
can you also update your comment on reddit about this? it will be helpful for a lot of people that wants to run zwift instead

**Comment by droomurray** [comment]
I think the reason they are not many requests is not many people understand what this means.

They are lots of treadmills like mine where ifit is no longer possible, with a bridge this would restore that and be significant value.

I will write up my findings, but what would it take to get that bridge done earlier, PLEASE

**Comment by cagnulein** [comment]
> I will write up my findings, but what would it take to get that bridge done earlier, PLEASE

sure I just need time. QZ is only an hobby for me and I have a family and a job like anyone else :)

Please contribute to the project to patreon or buy me a coffee to keep this alive. I can't afford to keep this online only with the app cost on the store (apple and italian laws takes away more than 85% of the revenuee, so i just got some cents from the app)

**Comment by droomurray** [comment]
For sure and if you need anyone to test / provide logs then I am more than happy to help - I am a freelance IT consultant but work more in networks and infrastructure than code etc.

My need from this is recovery from a back injury with the plan to "walk and run it off" in 2024 - running the treadmill on manual is so BORING.

Just signed up for Patron for you - keep up the great work (around life commitments) !

**Comment by cagnulein** [comment]
thanks! ping me about this in the next weeks!

**Comment by cagnulein** [comment]
anyway give it a try to zwift with qz, it's free and it's very well done!

**Comment by cagnulein** [comment]
also you can use the training program and the PID HR function in QZ if you want use it standalone!

**Comment by droomurray** [comment]
Will try that out for sure, am I right that Kinomap / any other trainer software will now work via  QZ Fitness ?

**Comment by cagnulein** [comment]
yes!
