### ISSUE TITLE
Can’t open qzcompanion.apk file on s22i

### ISSUE THREAD

**Issue by Ukben85** [cagnulein/QZCompanionNordictrackTreadmill#74]
Hi, I’ve downloaded the qz companion .apk on my s22i. When I click on it a grey bubble pops up saying ‘can’t open file’. Is there a setting that needs changing or anything else I can try?
Thanks in advance for any help or support
![IMG_1561](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/155910741/932c00c2-e45d-43d5-92a2-ca8d94554b60)

**Comment by cagnulein** [comment]
@Ukben85 you need to use the fv file manager to install it

let me know

**Comment by Ukben85** [comment]
Thanks @cagnulein that really helped!
