### ISSUE TITLE
nordiktrak T6.5si control

### ISSUE THREAD

**Issue by sorel123** [cagnulein/QZCompanionNordictrackTreadmill#75]
Have t6.5si talking now with qz companion 3.3.27. On iFit 2.2.9.378 (annoyingly slow) and board version 83. Qz - qdomyos-swift 2.16 (iOS). I don't have speed or incline control, currently set to use t6.5s in companion. Will have to upload log on another comment.

**Comment by sorel123** [comment]
[logcat.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/13865172/logcat.log)
[logcat.txt](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/13865173/logcat.txt)

**Comment by cagnulein** [comment]
check this and report it back
https://github.com/cagnulein/QZCompanionNordictrackTreadmill/wiki/Troubleshooting#i-cant-control-the-speedinclinationresistance-of-my-treadmillbike


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 8 gen 2024 alle 19:50 sorel123 ***@***.***> ha
scritto:

**Comment by sorel123** [comment]
Maybe I missed something. When I hit +/- for both speed and incline it registers on the screen and asks if I want to pause. I did a dump log while the workout was on and that's what I uploaded. Was there something else I was supposed to try or upload?

**Comment by cagnulein** [comment]
no it's ok. do you enable the speed and incline slider on the ifit app?

**Comment by cagnulein** [comment]
@sorel123 Any news?
