### ISSUE TITLE
Installed QZ companion on Proform studio bike but doesn’t seem to be linking with QZ app on iphone

### ISSUE THREAD

**Issue by abmorrison** [cagnulein/QZCompanionNordictrackTreadmill#76]
I was able to figure out how to get to the privileged view on my proform studio pro bike and use the browser while in the privileged view to download this companion as an APK file. When I open the companion, it has a list of various treadmills and bikes, and I selected the profrom studio bike pro 22, but there was nothing else that could be done apart from that.  I paid for and download the QZ app for my iPhone.  I plugged in the proform bike IP address in the TDF companion IP section, and restarted the app.  It does not appear that the app registers the bike?  If I start to pedal nothing happens.  The app also says it’s connected to my Apple Watch but isn’t displaying my HR.  Beyond this, I connected to Zwift as outlined in the YouTube video, but it doesn’t register and notes a “connection error” when I try to start a ride.  Am I missing a key step to get my bike linked with the app and then with Zwift?

**Comment by cagnulein** [comment]
ok let's start from the beginning. metrics from the bike

follow this and let me know https://github.com/cagnulein/QZCompanionNordictrackTreadmill/wiki/Troubleshooting#i-installed-the-companion-app-but-i-cant-see-any-data-on-my-qz-app

**Comment by abmorrison** [comment]
That seemed to get the QZ app linked to my bike for cadence, calories, and a few other metrics but now the Zwift app isn’t identifying any paired devices for power.

**Comment by cagnulein** [comment]
that's a great step forward! are you using zwift on another device? for example ipad or apple tv? you need one device for qz and one for zwift 

i'm going to bed now (italy here), let's resume this tomorrow

**Comment by cagnulein** [comment]
any news @abmorrison

**Comment by abmorrison** [comment]
I was finally able to get everything to connect opening your app on my phone and the ZWIFT app on my iPad, however my person on the ZWIFT app wasn’t pedaling as fast as I was - it was registering movement but at half the speed I was actually pedaling.  Any ideas?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cagnulein** [comment]
great! so first of all are the wattage from qz the same of zwift?

**Comment by cagnulein** [comment]
@abmorrison any news?
