### ISSUE TITLE
MANAGE_EXTERNAL_STORAGE

### ISSUE THREAD

**Issue by IzzySoft** [cagnulein/QZCompanionNordictrackTreadmill#77]
My scanners improved engine just sent me this report:

    repo/org.cagnulein.qzcompanionnordictracktreadmill_108.apk declares risky permissions: android.permission.MANAGE_EXTERNAL_STORAGE

As this permission is rather considered "risky" and reserved to file managers and such, may I ask if it's really needed here – and if so, what for? Maybe SAF (Storage Access Framework) would be sufficient for file system access?

**Comment by IzzySoft** [comment]
> since the user that it's installing this he's aware about the fact that it's hacking his tablet

Someone installing Magisk, Xposed etc) also is aware of that :wink: So IMHO *especially* with such risks, one should not add more risks on top.

Granted, I have no idea of the specific Android flavor on this particular device.But as you don't know if that permission is really needed, could you please verify? I mean, if it's as simple as not declaring that permission, and everything still works all the same, maybe that's worth the little effort? I'm no Android dev, so I cannot tell how much work it would otherwise be to e.g. switch from "direct file access" to SAF – but from the reports I received from other apps, I got the idea it is not too much.

**Comment by cagnulein** [comment]
Thanks a lot!


Il giorno ven 19 gen 2024 alle 17:43 Izzy ***@***.***> ha
scritto:
