### ISSUE TITLE
Nordictrack X14i -  incline off

### ISSUE THREAD

**Issue by Ellec13** [cagnulein/QZCompanionNordictrackTreadmill#79]
Hi! So I've got the the x14i set up with the companion and app. Incline and speed work, sort of with the following treadmill options, 2940, x11i x22i. You can change the tiles on the app and auto with zwift or peleton works. Speed is pretty on point and incline is okay around 1 or 2 but then starts jumping up pretty high beyond that like at 2 it jumps to 4 and then to 9 and then to 25ish.

This machine is somewhere between the x11i and x22i. (14inch screen so I'm assuming the dimensions of the touch events are just not fully corresponding for this screen size). 

I used the adb-screenshot.bat  in the install package and I'm attaching them here.  I've uploaded 2 images since the first one was covering the decline numbers.

The app is amazing, really great work on it!

![Sun01-28-2024@9-51-19 18](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/157979243/72942e16-ae66-4284-916d-83217687f3f4)
![Sun01-28-2024@9-58-12 21](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/157979243/4e8299ae-598b-4a80-85af-735dc18801a7)

**Comment by cagnulein** [comment]
great! i will try to add this tomorrow! thanks!

**Comment by cagnulein** [comment]
i added the profile for this treadmill now but the resulting equation for the incline is the same of the x22i so i guess the inclination slider is not linear. 

So I guess you have to map it and then we can create a formula.
You can use these steps: https://github.com/cagnulein/QZCompanionNordictrackTreadmill/issues/78#issuecomment-1913791222

the actual formula that i'm using for you is

```
                        x1 = 75;
                        y2 = (int) (785 - (11.304347826086957 * (reqInclination + 6)));                                                
```

let me know if something is unclear!

**Comment by Ellec13** [comment]
Hi! So if I’m processing this correctly I need to do 
adb shell input swipe [75 785 75 y 200] and figure out the y based on the formula above. So 785 - y2 formula for every incline jump. what is the 200 at the end?

For me the best setting is the 2950 ( speed to 19)
All the speeds work. All the declines work up to -5. So -5 -4 -3 -2 -1 0 1 3 6 9 25.5.  I can try the x22i setting and see what happens with the incline based on the app currently since you said it’s the same formula.

I will probably be able to get to this in a few days. Thanks for looking into this appreciate it.

**Comment by cagnulein** [comment]
> Hi! So if I’m processing this correctly I need to do 
> 
> adb shell input swipe [75 785 75 y 200] and figure out the y based on the formula above. So 785 - y2 formula for every incline jump. 

Exactly 

>what is the 200 at the end?

The delay if I remember correctly, leave as it is 

> 
> 
> 
> For me the best setting is the 2950 ( speed to 19)

Noted

> 
> All the speeds work. All the declines work up to -5. So -5 -4 -3 -2 -1 0 1 3 6 9 25.5.  I can try the x22i setting and see what happens with the incline based on the app currently since you said it’s the same formula.
> 
> 

Ok the best will be having the y value for EVERY possible incline value 

> 
> I will probably be able to get to this in a few days. Thanks for looking into this appreciate it.
> 
> 

No rush!

> 
> 
> 
>

**Comment by Ellec13** [comment]
Hi! Sorry for the delay. So mapped it out, had a bit of trouble getting a baseline for 0 since my starting point for 0 wasn't 785. Ran ./adb shell input swipe through every half incline and this is what worked for me. It seems to jump every 6ish give or take on a few. -6 to 40 listed below with the inclination listed after 200. For speed the 2950 (19 speed) setting is what works perfectly. Let me know if anything is unclear. Thanks and appreciate it.

75 785 75 856 200  -6
75 785 75 850 200 -5.5
75 785 75 844 200 -5
75 785 75 838 200 -4.5
75 785 75 832 200 -4
75 785 75 826 200 -3.5
75 785 75 820 200 -3
75 785 75 814 200 -2.5
75 785 75 808 200 -2
75 785 75 802 200 -1.5
75 785 75 796 200 -1
75 785 75 785 200 -0.5
75 785 75 783 200 0
75 785 75 778 200 0.5
75 785 75 774 200 1
75 785 75 768 200 1.5
75 785 75 763 200 2
75 785 75 757 200 2.5
75 785 75 751 200 3
75 785 75 745 200 3.5
75 785 75 738 200 4
75 785 75 731 200 4.5
75 785 75 724 200 5
75 785 75 717 200 5.5
75 785 75 710 200 6
75 785 75 703 200 6.5
75 785 75 696 200 7
75 785 75 691 200 7.5
75 785 75 689 200 8
75 785 75 684 200 8.5
75 785 75 677 200 9
75 785 75 671 200 9.5
75 785 75 665 200 10
75 785 75 658 200 10.5
75 785 75 651 200 11
75 785 75 645 200 11.5
75 785 75 638 200 12
75 785 75 631 200 12.5
75 785 75 624 200 13
75 785 75 617 200 13.5
75 785 75 610 200 14
75 785 75 605 200 14.5
75 785 75 598 200 15
75 785 75 593 200 15.5
75 785 75 587 200 16
75 785 75 581 200 16.5
75 785 75 575 200 17
75 785 75 569 200 17.5
75 785 75 563 200 18
75 785 75 557 200 18.5
75 785 75 551 200 19
75 785 75 545 200 19.5
75 785 75 539 200 20
75 785 75 533 200 20.5
75 785 75 527 200 21
75 785 75 521 200  21.5
75 785 75 515 200 22
75 785 75 509 200 22.5
75 785 75 503 200 23
75 785 75 497 200 23.5
75 785 75 491 200 24
75 785 75 485 200 24.5
75 785 75 479 200 25
75 785 75 473 200 25.5
75 785 75 467 200 26
75 785 75 461 200 26.5
75 785 75 455 200 27
75 785 75 449 200 27.5
75 785 75 443 200 28
75 785 75 437 200 28.5
75 785 75 431 200 29
75 785 75 425 200 29.5
75 785 75 418 200 30
75 785 75 412 200 30.5
75 785 75 406 200 31
75 785 75 400 200 31.5
75 785 75 394 200 32
75 785 75 388 200 32.5
75 785 75 382 200 33
75 785 75 375 200 33.5
75 785 75 369 200 34
75 785 75 363 200 34.5
75 785 75 357 200 35
75 785 75 351 200 35.5
75 785 75 345 200 36
75 785 75 338 200 36.5
75 785 75 332 200 37
75 785 75 326 200 37.5
75 785 75 320 200 38
75 785 75 314 200 38.5
75 785 75 308 200 39
75 785 75 302 200 39.5
75 785 75 295 200 40

**Comment by cagnulein** [comment]
ok perfect i will try to add this in the next days!

**Comment by cagnulein** [comment]
@Ellec13 perfect! new build for you https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.3.37/QZCompanionNordictrackTreadmill.apk

select the x14i device!
Let me know!

**Comment by cagnulein** [comment]
> Hi, I hope you had a good weekend! So I installed it. Speed works perfectly but the incline is still off.  When I push the + on the tile it works like this -5,-4,-3,-2,-1,0,1,2,3,9,25.
> 
> 

Is the incline from the qz tile is correct and match the treadmill? It's strange I just put your coordinates in the code.

> 
> The other weird thing is the companion on the x14i setting works with the android app which is the beta version but not with the IOS app which is not beta. when I push the tiles with this setting (X14i) on IOS nothing happens even with speed. (This could be normal?)


Send me an email to Roberto.viola83 at Gmail.com indicating this ticket and I will send you the beta on ios as well

**Comment by Ellec13** [comment]
yes the the tiles on the app match the whatever incline I set on on the treadmill or if I use the app to make changes the tile shows whatever incline the treadmill is jumping to.

**Comment by cagnulein** [comment]
i guess i found the reason.
actually i'm treating the Y2 coordinate like a pure number but probably i have to use it as an offset.

for example, if you set the incline to 5 and you try to go 9 with your line` 75 785 75 677 200 9` what's happen?

**Comment by cagnulein** [comment]
ok so i have to use them as an offset. ok got it, i will try to change the implementation. I will let you know when I will be ready to test it again. Thanks

**Comment by Ellec13** [comment]
no rush!

**Comment by cagnulein** [comment]
i did the patch https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.3.38/QZCompanionNordictrackTreadmill.apk

i hope it will work

**Comment by Ellec13** [comment]
Hi! I will have some time to test this out tomorrow. I will let you know once I do.

**Comment by cagnulein** [comment]
Sounds good, thanks!


Il giorno mer 7 feb 2024 alle 19:04 Ellec13 ***@***.***> ha
scritto:

**Comment by Ellec13** [comment]
Hi so bad news turned on the treadmill this am I have a black screen happening, so I can't test it, since I can't select the x14i setting in the app. I know the unit is powering on and I know stuff is happening with the tablet because I can connect via ADB, install the new companion and the treadmill and qz app still functions. Do you know a way I could select the x14i setting in the app with adb? I'm afraid to do a hard reset in case it's the screen since I wouldn't be able to connect to the internet. If you have any thoughts or advice let me know. Will keep you posted on if I can get the screen back and test.

**Comment by cagnulein** [comment]
i can check the correct device is selected using the command

adb logcat  -f

and share the output.

anyway the treadmill is going to the manual workout by default? otherwise it's impossible to test

What a bad luck!

**Comment by Ellec13** [comment]
hi yes can get into manual mode by pressing the start button and the treadmill functions when I type that command I get this . Option -f needs an argument
Usage: logcat [options] [filterspecs]
options include:
  -s              Set default filter to silent. Equivalent to filterspec '*:S'
  -f <file>, --file=<file>               Log to file. Default is stdout
  -r <kbytes>, --rotate-kbytes=<kbytes>
                  Rotate log every kbytes. Requires -f option
  -n <count>, --rotate-count=<count>
                  Sets max number of rotated logs to <count>, default 4
  --id=<id>       If the signature id for logging to file changes, then clear
                  the fileset and continue
  -v <format>, --format=<format>
                  Sets log print format verb and adverbs, where <format> is:
                    brief help long process raw tag thread threadtime time
                  and individually flagged modifying adverbs can be added:
                    color descriptive epoch monotonic printable uid
                    usec UTC year zone
                  Multiple -v parameters or comma separated list of format and
                  format modifiers are allowed.
  -D, --dividers  Print dividers between each log buffer
  -c, --clear     Clear (flush) the entire log and exit
                  if Log to File specified, clear fileset instead
  -d              Dump the log and then exit (don't block)
  -e <expr>, --regex=<expr>
                  Only print lines where the log message matches <expr>
                  where <expr> is a Perl-compatible regular expression
  -m <count>, --max-count=<count>
                  Quit after printing <count> lines. This is meant to be
                  paired with --regex, but will work on its own.
  --print         Paired with --regex and --max-count to let content bypass
                  regex filter but still stop at number of matches.
  -t <count>      Print only the most recent <count> lines (implies -d)
  -t '<time>'     Print most recent lines since specified time (implies -d)
  -T <count>      Print only the most recent <count> lines (does not imply -d)
  -T '<time>'     Print most recent lines since specified time (not imply -d)
                  count is pure numerical, time is 'MM-DD hh:mm:ss.mmm...'
                  'YYYY-MM-DD hh:mm:ss.mmm...' or 'sssss.mmm...' format
  -g, --buffer-size                      Get the size of the ring buffer.
  -G <size>, --buffer-size=<size>
                  Set size of log ring buffer, may suffix with K or M.
  -L, --last      Dump logs from prior to last reboot
  -b <buffer>, --buffer=<buffer>         Request alternate ring buffer, 'main',
                  'system', 'radio', 'events', 'crash', 'default' or 'all'.
                  Multiple -b parameters or comma separated list of buffers are
                  allowed. Buffers interleaved. Default -b main,system,crash.
  -B, --binary    Output the log in binary.
  -S, --statistics                       Output statistics.
  -p, --prune     Print prune white and ~black list. Service is specified as
                  UID, UID/PID or /PID. Weighed for quicker pruning if prefix
                  with ~, otherwise weighed for longevity if unadorned. All
                  other pruning activity is oldest first. Special case ~!
                  represents an automatic quicker pruning for the noisiest
                  UID as determined by the current statistics.
  -P '<list> ...', --prune='<list> ...'
                  Set prune white and ~black list, using same format as
                  listed above. Must be quoted.
  --pid=<pid>     Only prints logs from the given pid.
  --wrap          Sleep for 2 hours or when buffer about to wrap whichever
                  comes first. Improves efficiency of polling by providing
                  an about-to-wrap wakeup.

filterspecs are a series of 
  <tag>[:priority]

where <tag> is a log component tag (or * for all) and priority is:
  V    Verbose (default for <tag>)
  D    Debug (default for '*')
  I    Info
  W    Warn
  E    Error
  F    Fatal
  S    Silent (suppress all output)

'*' by itself means '*:D' and <tag> by itself means <tag>:V.
If no '*' filterspec or -s on command line, all filter defaults to '*:V'.
eg: '*:S <tag>' prints only <tag>, '<tag>:S' suppresses all <tag> log messages.

If not specified on the command line, filterspec is set from ANDROID_LOG_TAGS.

If not specified with -v on command line, format is set from ANDROID_PRINTF_LOG
or defaults to "threadtime"

**Comment by cagnulein** [comment]
ops sorry

adb logcat -d

**Comment by Ellec13** [comment]
it didn't pump out a log file but I save the terminal output?

[TerminalSavedOutput.zip](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14211483/TerminalSavedOutput.zip)

**Comment by Ellec13** [comment]
I figure it out here are the logs.

Thanks!

[x14i_log.zip](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14211554/x14i_log.zip)

**Comment by Ellec13** [comment]
you are so fast with the responses. I will try to run a Remote Desktop and keep you posted.

**Comment by Ellec13** [comment]
hi I was able to access the screen with scrcpy and adb and change the device to the correct one. unfortunately the incline still jumps to the exact same numbers as before. I installed it from the GitHub repo marked last night which I'm assuming is the updated apk. if you are out of ideas on how to make this one work one no worries seems like it might just not work. 

Thanks!

**Comment by cagnulein** [comment]
I never quit! If you are with me of course :)

In case let's try to debug this.
This is my current script

```
x1 = 75;
y1Inclination = x14i_inclination_lookuptable(ZService.lastInclinationFloat);
y2 = y1Inclination - x14i_inclination_lookuptable(reqInclination);

private int x14i_inclination_lookuptable(double reqInclination) {
        int y2 = 0;
        if (reqInclination == -6) { y2 = 856; }
        else if (reqInclination == -5.5) { y2 = 850; }
        else if (reqInclination == -5) { y2 = 844; }
        else if (reqInclination == -4.5) { y2 = 838; }
        else if (reqInclination == -4) { y2 = 832; }
        else if (reqInclination == -3.5) { y2 = 826; }
        else if (reqInclination == -3) { y2 = 820; }
        else if (reqInclination == -2.5) { y2 = 814; }
        else if (reqInclination == -2) { y2 = 808; }
        else if (reqInclination == -1.5) { y2 = 802; }
        else if (reqInclination == -1) { y2 = 796; }
        else if (reqInclination == -0.5) { y2 = 785; }
        else if (reqInclination == 0) { y2 = 783; }
        else if (reqInclination == 0.5) { y2 = 778; }
        else if (reqInclination == 1) { y2 = 774; }
        else if (reqInclination == 1.5) { y2 = 768; }
        else if (reqInclination == 2) { y2 = 763; }
        else if (reqInclination == 2.5) { y2 = 757; }
        else if (reqInclination == 3) { y2 = 751; }
        else if (reqInclination == 3.5) { y2 = 745; }
        else if (reqInclination == 4) { y2 = 738; }
        else if (reqInclination == 4.5) { y2 = 731; }
        else if (reqInclination == 5) { y2 = 724; }
        else if (reqInclination == 5.5) { y2 = 717; }
        else if (reqInclination == 6) { y2 = 710; }
        else if (reqInclination == 6.5) { y2 = 703; }
        else if (reqInclination == 7) { y2 = 696; }
        else if (reqInclination == 7.5) { y2 = 691; }
        else if (reqInclination == 8) { y2 = 689; }
        else if (reqInclination == 8.5) { y2 = 684; }
        else if (reqInclination == 9) { y2 = 677; }
        else if (reqInclination == 9.5) { y2 = 671; }
        else if (reqInclination == 10) { y2 = 665; }
        else if (reqInclination == 10.5) { y2 = 658; }
        else if (reqInclination == 11) { y2 = 651; }
        else if (reqInclination == 11.5) { y2 = 645; }
        else if (reqInclination == 12) { y2 = 638; }
        else if (reqInclination == 12.5) { y2 = 631; }
        else if (reqInclination == 13) { y2 = 624; }
        else if (reqInclination == 13.5) { y2 = 617; }
        else if (reqInclination == 14) { y2 = 610; }
        else if (reqInclination == 14.5) { y2 = 605; }
        else if (reqInclination == 15) { y2 = 598; }
        else if (reqInclination == 15.5) { y2 = 593; }
        else if (reqInclination == 16) { y2 = 587; }
        else if (reqInclination == 16.5) { y2 = 581; }
        else if (reqInclination == 17) { y2 = 575; }
        else if (reqInclination == 17.5) { y2 = 569; }
        else if (reqInclination == 18) { y2 = 563; }
        else if (reqInclination == 18.5) { y2 = 557; }
        else if (reqInclination == 19) { y2 = 551; }
        else if (reqInclination == 19.5) { y2 = 545; }
        else if (reqInclination == 20) { y2 = 539; }
        else if (reqInclination == 20.5) { y2 = 533; }
        else if (reqInclination == 21) { y2 = 527; }
        else if (reqInclination == 21.5) { y2 = 521; }
        else if (reqInclination == 22) { y2 = 515; }
        else if (reqInclination == 22.5) { y2 = 509; }
        else if (reqInclination == 23) { y2 = 503; }
        else if (reqInclination == 23.5) { y2 = 497; }
        else if (reqInclination == 24) { y2 = 491; }
        else if (reqInclination == 24.5) { y2 = 485; }
        else if (reqInclination == 25) { y2 = 479; }
        else if (reqInclination == 25.5) { y2 = 473; }
        else if (reqInclination == 26) { y2 = 467; }
        else if (reqInclination == 26.5) { y2 = 461; }
        else if (reqInclination == 27) { y2 = 455; }
        else if (reqInclination == 27.5) { y2 = 449; }
        else if (reqInclination == 28) { y2 = 443; }
        else if (reqInclination == 28.5) { y2 = 437; }
        else if (reqInclination == 29) { y2 = 431; }
        else if (reqInclination == 29.5) { y2 = 425; }
        else if (reqInclination == 30) { y2 = 418; }
        else if (reqInclination == 30.5) { y2 = 412; }
        else if (reqInclination == 31) { y2 = 406; }
        else if (reqInclination == 31.5) { y2 = 400; }
        else if (reqInclination == 32) { y2 = 394; }
        else if (reqInclination == 32.5) { y2 = 388; }
        else if (reqInclination == 33) { y2 = 382; }
        else if (reqInclination == 33.5) { y2 = 375; }
        else if (reqInclination == 34) { y2 = 369; }
        else if (reqInclination == 34.5) { y2 = 363; }
        else if (reqInclination == 35) { y2 = 357; }
        else if (reqInclination == 35.5) { y2 = 351; }
        else if (reqInclination == 36) { y2 = 345; }
        else if (reqInclination == 36.5) { y2 = 338; }
        else if (reqInclination == 37) { y2 = 332; }
        else if (reqInclination == 37.5) { y2 = 326; }
        else if (reqInclination == 38) { y2 = 320; }
        else if (reqInclination == 38.5) { y2 = 314; }
        else if (reqInclination == 39) { y2 = 308; }
        else if (reqInclination == 39.5) { y2 = 302; }
        else if (reqInclination == 40) { y2 = 295; }
        return y2;        
    }
```

so for example if are on inclination 3 and you want to go to inclination 10 the script send the command

`adb shell input swipe 75 751 75 86 200`

but I guess i'm doing this right the worked line for this should be

`adb shell input swipe 75 751 75 665 200`

can you try both and confirm?

thanks!

**Comment by Ellec13** [comment]
Yes I'm in, I just didn't want you to keep putting time into it. With the screen not working this app has been a life saver. 

adb shell input swipe 75 751 75 86 200 - from 3 this goes to incline 40

adb shell input swipe 75 751 75 665 200 - from 3 this goes to incline 10

:)

**Comment by cagnulein** [comment]
perfect! let me fix this so!

**Comment by cagnulein** [comment]
done! https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.3.39/QZCompanionNordictrackTreadmill.apk



> Yes I'm in, I just didn't want you to keep putting time into it.

it's rare to find someone like you, so that's why I like to work on this!

**Comment by Ellec13** [comment]
I really appreciate the effort. I installed. Declines work until 5 then then the touch must be too low on the screen because it goes to the pause screen. inclines work 1, 2, 3, 9, 25 and then I can't come back down from there. Also when I try to go down from 3 it jumps up to 9 lol. and then using the tile to go down from 9 jumps to 25. From -5 to 2 functions normally up and down

**Comment by cagnulein** [comment]
when you change the incline do you still see the right actual value on qz?
can you try to attach a debug log from the issue? it's really making me
mad!
https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 9 feb 2024 alle 15:23 Ellec13 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
Ok I will check the log ASAP, pizza time here in Italy :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 9 feb 2024 alle 18:00 Ellec13 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@Ellec13 i checked the log and I don't see any traces of QZ companion changing incline, so this made me thinking about that maybe you have the adb remote setting enabled in qz in the nordictrack treadmill setting? if so can you please turn it off? Let me know

**Comment by Ellec13** [comment]
Hi yes it’s on. If I turn it off I can’t control the incline from the tiles on android beta but I still see the speed and incline. In iOS beta whether it’s on of off I can’t control the tiles but if it’s on I see the correct incline and speed. If it’s off it’s shows zero on everything. If I downgrade to the Jan 7 akp on the 2950 setting the iOS app is working but I’d need to reinstall that one again and test with adb remote toggled on and off to see if I have control from the tiles if it’s off.

**Comment by cagnulein** [comment]
ok so now i'm understanding everything! with that on you are using qz to send the inclination and the speed control!

so I have to do the modification there!

Ok i will do in the next days!
Thanks!

**Comment by Ellec13** [comment]
haha so sorry that might have been useful information from the start, I didn't even think about that. No rush and enjoy the weekend!

Appreciate it!

**Comment by cagnulein** [comment]
Have a great weekend too!


Il giorno sab 10 feb 2024 alle 15:11 Ellec13 ***@***.***> ha
scritto:

**Comment by Ellec13** [comment]
okay one more note for you in case its helpful, so I reinstalled the jan 7 apk and the iso app and android app work on the 2950 setting with out adb remote turned on.

attaching logs, no need to look at this now! 
[testlog.zip](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14229572/testlog.zip)

**Comment by cagnulein** [comment]
ok i'm sending you a new ios version where i added the x14i on the nordictrack combobox on the nordictrack treadmill settings.
Select the x14i and be sure adb remote is turned on.
Restart qz and try again, speed should be same as before but inclination now has the new lookup table
Let me know!

**Comment by Ellec13** [comment]
Guess what it works!!!  Almost perfect, the only issue I'm finding is I can't go up from 7.5 to 8 using the tiles but if I use the button on the tread to go up to 8 then I can go up the rest of the inclines using the tiles. I don't think this is a big deal, it works really well beyond that tiny glitch.  

I'm just so excited it's working! Great job on this.  Thanks!

**Comment by cagnulein** [comment]
amazing!
i guess i found the issue for the 7.5 glitch

in your table i see

```
75 785 75 691 200 7.5
75 785 75 689 200 8
```

but the difference is only 2 pixel, it seems low. can you try this again and report back? I want to fix this also! we did the 99% i want the 100% :D

**Comment by Ellec13** [comment]
You are a perfectionist! 

75 785 75 689 200 8  works via adb swipe but there is a range within a few pixels that will work. 

75 785 75 687 200  will also work for incline 8

75 785 75 683 (instead of 684 will work for 8.5) if we want to make sure the pixel count isn't too low between incline step ups. Thanks!

**Comment by cagnulein** [comment]
Sent a new one!
Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 12 feb 2024 alle ore 17:32 Ellec13 ***@***.***>
ha scritto:

**Comment by Ellec13** [comment]
Haha now with the tiles it jumps from 7.5 to 8 but won’t jump from 8 to 8.5. I think it’s probably the same issue as before with the pixel count being too low between step ups. 

75 785 75 683 (instead of 684 will work for 8.5) that way there are 4 pixel between each step. 

I did a peloton work out and the auto inclines/ speeds worked perfectly. Can’t wait to try with zwift. It is was amazing!

**Comment by cagnulein** [comment]
done i will send it asap

**Comment by Ellec13** [comment]
And it's perfect! Everything is working as it should! Thank you so much for getting this working!

**Comment by cagnulein** [comment]
That's great to hear!
I'm leaving this open in case you will find something else!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 15 feb 2024 alle ore 14:17 Ellec13 ***@***.***>
ha scritto:

**Comment by Ellec13** [comment]
hi I'm so sorry but I did notice something. I can't really pinpoint what causes it to happen. I noticed it durning a free Zwift run (not a work out) that the speed was randomly changing. I did try a zwift work out and noticed the same thing with the speed jumping (really motivates you to run fast LOL).  Sometimes really speeding up, sometimes slows down. I think it happens during incline changes but not always. I tried to replicate it doing just a manual treadmill run with the tiles and some times adjusting the incline would cause it to speed up (the incline is still going to the correct incline) or adjusting the speed would change the incline ( speed would go to the correct speed). It's so strange. It also doesn't happen at the same speeds or incline all the time with using the tile. qz corresponds with the correct reading on the treadmill as well.

**Comment by Ellec13** [comment]
adding logo but I wonder if you need the logs from the actual app since its adb remote. let me know

[logs.zip](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14316338/logs.zip)

**Comment by cagnulein** [comment]
Ok I will chdck this but yes a debug log from qz would be helpful too

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 16 feb 2024 alle 22:54 Ellec13 ***@***.***> ha
scritto:

**Comment by Ellec13** [comment]
hi more logs from the haunted treadmill. Test 3 is all logs from the tread and QZ app incline testing. Test 4 is only from the qz app (I forgot to play with speed in the first one and show how that affects things). It's very strange.
[Test3_4.zip](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14319521/Test3_4.zip)

**Comment by cagnulein** [comment]
@Ellec13 so even in the only qz scenario, you are seeing that incline is also changing speed? so what I should look in the log is that when you change inclination, the speed changes too?

**Comment by Ellec13** [comment]
yes using the QZ app tiles I change the incline and the speed sometimes changes. The QZ app reflects the changes that happen in the tiles matching the speed and incline on the tread. It doesn't happen all the time a specific incline and doesn't happen for every incline change. This also happened with the speed tiles sometimes using the qz app. I'm wondering if it has something to do with the offset you implemented  before we realized it using adb remote. I'm not a developer so just throwing ideas out.

For example test 3

5.5 incline - speed went to 2.9
8.5 incline - speed went to 15.5
7.5 incline - speed went to 14.5
9.5 inline then dropped randomly to incline 4.6 - speed went to 4.5

However if test again I can't replicate the same results. 

No rush, it's the weekend! Appreciate all the effort you've put into this.

**Comment by cagnulein** [comment]
got the issue! you have the training program random enabled! disable it in
the training program settings in qz!
let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 17 feb 2024 alle ore 21:01 Ellec13 ***@***.***>
ha scritto:

**Comment by Ellec13** [comment]
YES that was it. Everything is perfect no more haunted treadmill, did a run no more issues. Wow I feel dumb! So many parts of this app I haven't even explored yet.

Thank you so much! Please close this issue off so I can't bug you anymore.

**Comment by cagnulein** [comment]
glad to hear it!
