### ISSUE TITLE
Incline and speed support for Nordictrack C1750 2020

### ISSUE THREAD

**Issue by jhholen** [cagnulein/QZCompanionNordictrackTreadmill#81]
Nordictrack C1750 with 10" screen needs mapping for adjustment of speed and incline.

Controls added to the screen and I can see touch events on the screen when changing speed in the app.

Please let me know if I can contribute with anything. 

![IMG_4708](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/6086258/c80d32d8-b7f7-4e94-b5b5-03c276170fa1)

**Comment by jhholen** [comment]
Never mind - forgot to edit type the app.

**Comment by cagnulein** [comment]
@jhholen So it's already OK?

**Comment by jhholen** [comment]
Speed works fine and adding incline works.
But lowering incline dosent work to me. No action on the mill.

**Comment by cagnulein** [comment]
Could you please share a debug log with the issue https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

**Comment by jhholen** [comment]
[Uploading debug-Fri_Feb_2_18_32_10_2024.log…]()

**Comment by cagnulein** [comment]
Wait the finish of the upload before commenting, the file is truncated

**Comment by jhholen** [comment]
[debug-Fri_Feb_2_18_32_10_2024.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14143379/debug-Fri_Feb_2_18_32_10_2024.log)

Better?

BTW: what is the latest Version of IFIT that works with the qz app?

**Comment by cagnulein** [comment]
Thanks I will check it ASAP

I don't know about the ifit version, it depends on the specific model. You
have to try

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 2 feb 2024 alle 18:43 Jarl-Håvard Holen <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
Can you try setting 1 to inclination step in the treadmill settings in qz?

I guess the issue is about 0.5 step

By the way which device are you using in the companion?

**Comment by jhholen** [comment]
Tried setting incline step to 1, without any luck.

Today it does not work at all. Probably not related to the change, but more due to reboot of the machine.

Using iOS.

**Comment by cagnulein** [comment]
i mean the device selected on the companion.

anyway yes try to reboot it and check that the adb setting is still enabled

**Comment by jhholen** [comment]
I have selected C1750 2021.
Where do I check the adb setting?

**Comment by cagnulein** [comment]
didn't you follow this
https://github.com/cagnulein/QZCompanionNordictrackTreadmill
 ?

anyway if it was working before without the adb , yes i suggest to only
reboot the treadmill

Roberto Viola
Software engineer and open source enthusiast
http://roberto viola.cloud <http://robertoviola.cloud>



Il giorno sab 3 feb 2024 alle 18:30 Jarl-Håvard Holen <
***@***.***> ha scritto:

**Comment by jhholen** [comment]
Yes, I did.

Will try that and report back.

**Comment by cagnulein** [comment]
ok also remove the gateway setting from the wifi setting of the treadmill so ifit will not try to fix themself

**Comment by jhholen** [comment]
What gateway setting?

See now that iFit has updated itself automatically...

**Comment by cagnulein** [comment]
@jhholen in the wifi settings of the treadmill don't you see the ip and the gateway? share me a screenshot of them

**Comment by jhholen** [comment]
![IMG_4717](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/6086258/371edafe-5183-41a2-ba67-98acd73fda67)

[debug-Sun_Feb_4_09_00_37_2024.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14155952/debug-Sun_Feb_4_09_00_37_2024.log)

But I can see now that ifit has updated. Can that be related?

**Comment by cagnulein** [comment]
Yes it could be. That's why I'm always asking to reset the factory reset and removing the gateway immediately so ifit will not update itself

**Comment by jhholen** [comment]
Where is the gateway process described?

**Comment by cagnulein** [comment]
Actually nowhere but you can find here in the tickets there are some
comments about this.

Did you find the wifi settings of the treadmill?

I'm on a family meeting now, I will help you in the next hours if you can't
find it

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 4 feb 2024 alle 12:52 Jarl-Håvard Holen <
***@***.***> ha scritto:

**Comment by jhholen** [comment]
Just reset the treadmill now, and reinstalled the app.
C1750 selected.

The speed works, but the steps are off. Increments by 0.2 instead of 0.5.

Incline works sort of the first three clicks. Setting is set to one, but incline changes by two. Minus also increases incline. After three clicks it dosent work anymore.

See attached video.


https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/6086258/634de117-8f33-4303-92f3-25d2b1c2aa1c



Data flows right.

**Comment by cagnulein** [comment]
Ok so I need to map your device, use this https://github.com/cagnulein/QZCompanionNordictrackTreadmill/blob/master/InstallPackage/adb-screenshot.bat

**Comment by jhholen** [comment]
On a Mac only. 

Possible to rewrite to bash?

**Comment by cagnulein** [comment]
Check here
https://github.com/cagnulein/QZCompanionNordictrackTreadmill/blob/master/InstallPackage/adb-screenshot-mac.sh


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 4 feb 2024 alle 21:57 Jarl-Håvard Holen <
***@***.***> ha scritto:

**Comment by jhholen** [comment]
Rewrote it myself. Screenshot added.

![2024-02-04@22-06-31](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/6086258/89196254-9dd1-44bf-9ea0-905ab8ea1149)

**Comment by cagnulein** [comment]
Ok I will add this in the next days

**Comment by cagnulein** [comment]
@jhholen new apk https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.3.36/QZCompanionNordictrackTreadmill.apk

let me know if the formula is right now, otherwise we need to test it with adb to find the right coefficents.
let me know!

**Comment by cagnulein** [comment]
ok so I need help from you.
You need to create a formula yourself testing directly on the treadmill.
Are you able to to so?

you have to use the 

adb shell input swipe 

command 

with the coordinates

you can check here the formula that I added for you https://github.com/cagnulein/QZCompanionNordictrackTreadmill/commit/c884a174fcd8f900a55288162d38f2cbb45ce644#diff-f6d77d1e4eb75018758ba6c75c8ba2c8e817dd8a5d5790ae376f74b0a4dddd92

Let me know if you have any questions!

**Comment by jhholen** [comment]
Sure! 

Can you give me an example command with coordinates?

`adb shell input swipe 1234` ?

**Comment by cagnulein** [comment]
for the inclination, for example

adb shell input swipe x1 y1Inclination x1 y2 200

where

x1 = 75

y1Incliantion is the start point of the current inclination value calculated in pixel coordinates. I-m calculating this in this way now 594 - (int) ((QZService.lastInclinationFloat -3) * 19.83); The QZService.lastInclinationFloat is the actual inclination grade collect from the treadmill

y2 i'm calculating it in this way now y1Inclination - (int) ((reqInclination - QZService.lastInclinationFloat) * 19.83); the reqinclination is the value in grade that you want to set to the treadmill

let me know

**Comment by jhholen** [comment]
Was going to configure the setup now, but the screen on my treadmill once again goes white after a few days without use.
This has happened three times lately, and the solution looks to be either reset the machine or update iFit. 

Known issue?

**Comment by cagnulein** [comment]
Never heard it.

Anyway you can use this method to bypass the screen
https://github.com/cagnulein/QZCompanionNordictrackTreadmill/issues/79#issuecomment-1934430677


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 13 feb 2024 alle 17:59 Jarl-Håvard Holen <
***@***.***> ha scritto:

**Comment by jhholen** [comment]
Thank you, but the issue is related to the iFit app. I can navigate the
Android interface, restart the app and close. But iFit ends up in a white
screen each time.

From: Roberto Viola ***@***.***> ***@***.***>
Reply: cagnulein/QZCompanionNordictrackTreadmill
***@***.***>
***@***.***>
Date: 13 February 2024 at 18:01:45
To: cagnulein/QZCompanionNordictrackTreadmill
***@***.***>
***@***.***>
CC: Jarl-Håvard Holen ***@***.***> ***@***.***>, Mention
***@***.***> ***@***.***>
Subject:  Re: [cagnulein/QZCompanionNordictrackTreadmill] Incline and speed
support for Nordictrack C1750 2020 (Issue #81)

Never heard it.

**Comment by cagnulein** [comment]
argh this is new. maybe you can try to install a different ifit apk version?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 13 feb 2024 alle 18:08 Jarl-Håvard Holen <
***@***.***> ha scritto:

**Comment by jhholen** [comment]
Did a reset and did some testing.

Can the issue be that the speed start with 1,3,5,7,9,11 and then changes to 12,14,16,18,20,22? 
Wont the formula then be off?

Same goes for incline: -3, -1, 0, 2, 4, 5, 7, 8, 10, 12, 13, 15.
![2024-02-13@18-20-14](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/6086258/fcd60d36-64b7-4160-b348-46dca8b15119)

**Comment by cagnulein** [comment]
Could be, are you able to change the formula So?
You can start trying to change the speed value starting from 1 to any new speed and creating a table like the user did in the link that I just sent

**Comment by cagnulein** [comment]
Looks great!
I will add it tomorrow!


Il giorno mar 20 feb 2024 alle 17:03 Jarl-Håvard Holen <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
new build ready, let me know
https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.3.40/QZCompanionNordictrackTreadmill.apk


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 20 feb 2024 alle 17:36 cagnulein ***@***.***> ha
scritto:

**Comment by jhholen** [comment]
Thanks! Tried it now, and it is way off. Same issue as before, where incline works the first few tests. Then I goes incremental from 1.5, 2, 3, 5 and off the chart.

Speed never works at all. Is it possible to see logs on what the values was at each test?

**Comment by cagnulein** [comment]
sure qz companion is logging on adb logcat

your function was only for y2 , i use the same maps for y1. is it right?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 21 feb 2024 alle 20:36 Jarl-Håvard Holen <
***@***.***> ha scritto:

**Comment by jhholen** [comment]
I really dont get how this works.

I now testet this command twice: adb shell input swipe 75 528 75 486 200

Starting from 0, first time it goes to 2 and if I trigger it again at that position it goes to 4?

**Comment by cagnulein** [comment]
Probably ifit reacts to a slide to any position .

they are just x1 y1 x2 y2 coordinates

that's why i asked to create a complete formula because i can't test with
your very specific tablet

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 22 feb 2024 alle 17:39 Jarl-Håvard Holen <
***@***.***> ha scritto:

**Comment by cagnulein** [comment]
@jhholen any news?
