### ISSUE TITLE
x22i update coordinates

### ISSUE THREAD

**Issue by brymon68** [cagnulein/QZCompanionNordictrackTreadmill#82]
Hi @cagnulein  - 

I was emailing you earlier about controls in QZ app not controlling / updating x22i. I was able to find a windows box and run adb-screenshot.bat.

See attached. 

![Sat02-03-2024@13-24-30 21](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/8397405/3419399c-a982-47da-ba95-5b20812cb445)

**Comment by cagnulein** [comment]
hi i can't see the sliders here. did you enabled them?

**Comment by brymon68** [comment]
Apologies @cagnulein . I enabled them in the phone initially, not in the treadmill. Here is attached screenshot with sliders enabled. Still unable to control but perhaps I just need to reset treadmill? 

![Sat02-03-2024@13-34-37 21](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/8397405/19e26ae7-cd90-41c0-8810-78334891100a)

**Comment by cagnulein** [comment]
do you still see touch event in wrong positions? if so, no i just to add your coordinates.

i'm going to bed now

**Comment by brymon68** [comment]
@cagnulein  - I do not see any touch events at all on the treadmill screen when I interact with the QZ app (speed, inclination)

**Comment by cagnulein** [comment]
did you see it before? i thought you said that a something popup on the treadmill when you tried to change speed or inclination on qz. this is crucial

**Comment by brymon68** [comment]
Yes I did see that popup prior to enabling sliders. Now I no longer see any touch events or popups

**Comment by cagnulein** [comment]
ok go into the developers settings of the treadmill and you can enable a setting to visual showing the touch events 

then try again qz so we will be sure about this

let me know

**Comment by brymon68** [comment]
Got it figured out @cagnulein. My issue was I had incorrect treadmill selected in QZ app even though I had the correct one selected in companion app on Treadmill. Apologies for the confusion!

I noticed in README the instructions do not state to select the treadmill: 

> Now that QZ Companion is installed and running on your treadmill or bike, it’s time to configure QZ to communicate with QZ Companion. 
Configure QZ to communicate with QZ Companion. On your 2nd QZ device (Windows PC or laptop, Android phone or tablet, or iOS iPhone or iPad), open QZ and go to Settings. Expand Treadmill or Bike Options, Proform/NordicTrack Options, and enter the treadmill or bikes IP address under NordicTrack 2950 IP and hit OK. Exit and relaunch QZ to activate the change. If done correctly, QZ will display live data tiles to indicate it is communicating directly with QZ Companion on 

I can submit a PR to state "Select your treadmill and "enter the treadmill or bikes IP address under NordicTrack 2950 IP "

Let me know, I'm happy to contiribute. Also happy to add my bash script that I adapted from adb-screenshot.bat. Let me know!

**Comment by cagnulein** [comment]
sure absolutely!

so now you are able to see them but they are still on a wrong position?

**Comment by brymon68** [comment]
Everything is working with QZ and companion. Just need to test zwift. I'll close this issue and will get PR submitted. I'll also test zwift

**Comment by cagnulein** [comment]
amazing news! thanks!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 4 feb 2024 alle ore 18:01 Bryce Montano <
***@***.***> ha scritto:
