### ISSUE TITLE
Support for ProForm Pro 5000 Treadmill

### ISSUE THREAD

**Issue by mattvv** [cagnulein/QZCompanionNordictrackTreadmill#84]
Hi Roberto!

I have a ProForm Pro 5000 device that had it's front buttons under the screen fail (pressing 2 goes to 10), and while it's out of warranty I was looking for a way to control it remotely and found this nifty little app - Thank you for the absolutely insane amount of work on this - One I get things up and running I'm excited to have buttons to control the speed on my phone, but also try out auto-resistance.

I followed the instructions to install companion app and got to

```Now that QZ Companion is installed and running on your treadmill or bike, it’s time to configure QZ to communicate with QZ Companion.```

At this step, i entered my treadmill's IP and started a ifit manual mode workout, I tried each ProForm Model and none of them showed the speed or could change the setting.

I ran a few steps to capture Debug Logs but it looks like on my iOS device I didn't get the qmydos folder in FIles. I did take a look at the Debug Log on the treadmill side - annd fro what I can tell it goes

Service run
There is no File in the folder

Let me know if theres anything I can find to help get this one linked to QZ

**Comment by cagnulein** [comment]
Hi @mattvv thanks!
Could you show me what you see on the file app? a debug log is required to understand what's the issue
Thanks

**Comment by cagnulein** [comment]
@mattvv any news?
