### ISSUE TITLE
No response to QZ input on x22i treadmill 

### ISSUE THREAD

**Issue by lthown** [cagnulein/QZCompanionNordictrackTreadmill#85]
Ok, I followed the troubleshooting steps and I do not get any response on the treadmill when I press tile input in QZ. I do have the sliders enabled, joined the beta on Android and even selected X22i in the new menu. I have ADB remote enabled and I even turned on show input touches in the treadmill Dev options.
![Screenshot_20240214_212830](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/750471/7a9debd7-8ab7-4bcd-be5c-0d42329f9fe4)

**Comment by cagnulein** [comment]
Are you able to connect to adb from your pc?

**Comment by lthown** [comment]
I was able to use the bat file and ADB to install the companion app. I haven't tried running commands manually via ADB since then but I'm happy to try any specific ones.

**Comment by cagnulein** [comment]
Try for example to run

adb shell input swipe 100 200 300 400 200

And let me know if you see a touch reaction

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 15 feb 2024 alle 06:55 Chris Bair ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
> OK, that was weird - I had to revoke debugging authorizations a few times and disable and re-enable debugging and then I finally got it to connect to an ADB console and take commands. The command you suggested brought up a controls screen on the treadmill. Cool.
> 
> I was then able to exit out of ADB on my laptop and go into QZ on my android device and now the speed and inclination tile controls are working. Manually messing with those seems to work great.
> 

Great!

> A couple of questions:
> 
> I didn't see it specified in [this page about the XML tags ](https://robertoviola.cloud/2023/11/20/exploring-the-versatility-of-qz-app-your-gateway-to-a-tailored-fitness-experience/) but what unit of measure is the speed tag? is that KPH? Is there a way to get it to mi/h like I'm using on the tile view in QZ?

xml is in KPH. There is a ticket about setting the unit but for now is in KPH. 

> 
> Does the XML program ignore the warm-up/cool down on the treadmill?


QZ doesn't know about this (neither do I :) ). What is it?

> 
> When it says "Program has been loaded correctly, press start to begin!" on my android device - does that mean press start on the treadmill? I'm operating under the assumption that in order for QZ to do anything I have to start a manual workout and be on the manual workout screen

You have to press twice the start button on qz to engage the program or once if the play button was already blinking red (pause mode)

> 
> Is there a way to have QZ trigger the cool down or end workout on the treadmill? Pressing the STOP button near the tiles on my android device does not seem to cause any effect on the treadmill.

Again i don't know what is it. Is it a special mode on the treadmill tablet?

**Comment by lthown** [comment]
OK, I'll use math to convert to KPH, no biggie.

To confirm though - I do need to be in the manual workout screen on the treadmill before starting anything in QZ, correct?

On this treadmill, when you start a manual workout it defaults to a 3 minute "warm-up" at 1 mile/hour. there's a button to end the warm-up and then you're into the main workout screen

you can also trigger a cool down which defaults to 10 minutes and slowly reduces speed, that can be ended at any time to stop the workout (see attached video)

One last thing for this report =) I'm not sure what the integration with this treadmill is supposed to support but I do not see the heart rate monitor data from the treadmill in the QZ tiles and the fan control on the treadmill does not do anything in QZ. no data is sent and the tile does not control the fan on the treadmill.

https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/750471/a3482ae9-0733-4468-86d9-9d25047cde5d

**Comment by lthown** [comment]
During the warm-up/cool down I do see the speed and inclination in QZ and I'm able to change them on the treadmill using QZ

Yes I can - to be clear I believe what you are requesting is that I use my laptop to connect to the treadmill ADB, then I'll run the following:

adb logcat -c (clears the log)
adb logcat -f X22i_fan_and_HR.log (saves logcat to local file on windows machine)

Then I'll fire up a manual workout on the treadmill with the hear rate monitor active. I'll adjust the fan speed, end the warm-up early, adjust the speed and inclination for fun, start cool down, end the workout

Stop logcat capture. (Control+C). 

Would you prefer I email the logs?

**Comment by cagnulein** [comment]
yes perfect! it's a pleasure working with people like you :)

you can attach the log compressed here, thanks! (so i keep a trace of every mod that I'm doing)

**Comment by lthown** [comment]
OK, logcat attached. Oddly it looks like QZ Companion is getting the heart rate data, it's just not passing it on to my Android device.

[X22i_fan_and_HR.zip](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14305294/X22i_fan_and_HR.zip)

**Comment by cagnulein** [comment]
Easy fix for this! Are you on the beta on android?
https://play.google.com/apps/testing/org.cagnulen.qdomyoszwift

Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 16 feb 2024 alle 04:20 Chris Bair ***@***.***>
ha scritto:

**Comment by lthown** [comment]
Yep, I'm on the beta.

BTW I did mess with the fan, speed, incline, speaker volume, and did the warm up and cool down process during that period.

If you need it I can grab the wolf and ifit logs from the treadmill, I have Total commander with the network drive plugin installed so I can move stuff on and off easily.

**Comment by cagnulein** [comment]
i guess a debug log from qz could be sufficient  now
https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

i will check again the previous log in the meantime

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 16 feb 2024 alle 04:35 Chris Bair ***@***.***>
ha scritto:

**Comment by lthown** [comment]
Debug from QZ is attached. 

every time I turn off the treadmill, in order to connect to ADB I have to disable and reenable debugging in the developer settings of the treadmill.

[debug-Thu_Feb_15_20_59_41_2024.zip](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14305654/debug-Thu_Feb_15_20_59_41_2024.zip)

**Comment by cagnulein** [comment]
got the issue, this treadmill is logging it in a slightly different way. i
will fix this later today
thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 16 feb 2024 alle 05:05 Chris Bair ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
done! https://github.com/cagnulein/qdomyos-zwift/actions/runs/7927097435

Google is very slow in these days, reviewing the app on the store, even the beta ones. For this reason, in order to check right now if the patch that I did is right, you can use the android build in the link (check at the bottom of the page in about 1 hour). In order to test it you need first to remove the current QZ version on your phone, install the one that you downloaded.
This version is a 15 minutes trial (you can restart it as many times as you want) and I can unlock it if you want, send me an email to roberto.viola83@gmail.com mentioning this ticket and that you are on android.
Let me know if you have any questions

**Comment by cagnulein** [comment]
hi @lthown any news?
