### ISSUE TITLE
Incline for TDF 10.0 bike

### ISSUE THREAD

**Issue by ignacioF1** [cagnulein/QZCompanionNordictrackTreadmill#86]
Hi! Tested TDF 10.0 bike, resistance works great, but incline is missing. Are you planning to add it? Many thanks!

**Comment by cagnulein** [comment]
do you mean resistance reading or control? @ignacioF1

**Comment by ignacioF1** [comment]
Hi @cagnulein I mean control.

**Comment by cagnulein** [comment]
follow this and report back https://github.com/cagnulein/QZCompanionNordictrackTreadmill/wiki/Troubleshooting#i-cant-control-the-speedinclinationresistance-of-my-treadmillbike

thanks!

**Comment by ignacioF1** [comment]
Taking a look at this code, I can see that only the resistance is set but not the inclination. If you need my help for the coordinates, just let me know. Thanks.

**Comment by cagnulein** [comment]
yes if you can do a PR with the inclination coordinates will be great! @ignacioF1

**Comment by ignacioF1** [comment]
@cagnulein Following the example of the resistance, here is the inclination formula:

if (device == _device.tdf10) {						
x1 = 74;
y2 = (int) (-12.499 * reqInclination + 482.2);
}

So for the extremes it should be:
20 degrees -> 232
-10 degrees -> 607

Thanks!

**Comment by cagnulein** [comment]
thanks i will implement ASAP!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 27 feb 2024 alle 21:25 Ignacio ***@***.***> ha
scritto:

**Comment by cagnulein** [comment]
@ignacioF1 are you able to connect via adb to the bike? if so i will do the mod directly on the qz main app. are you on android or ios with the main qz app?

**Comment by ignacioF1** [comment]
@cagnulein It would be better for me if you can update this app, as I'm downloading it to the bike with a flashdrive. I'm using IOS. Thanks!

**Comment by cagnulein** [comment]
ok i'm doing the mod, i will send you the new link

**Comment by ignacioF1** [comment]
@cagnulein it works excellent! Now it would be great to have both resistance and inclination together.
Thanks!

**Comment by cagnulein** [comment]
amazing! One question: the bike doesn't change the resistance when the inclination changes? I thought so

**Comment by ignacioF1** [comment]
Yes, only inclination working when I select the new model.

**Comment by cagnulein** [comment]
no i mean, doesn't the inclination also affect the resistance? don't you feel the resistance changing when the inclination does? on my proform bike works in this way.

**Comment by ignacioF1** [comment]
No, in the logs it says that the resistance is being changed, but it changes the inclination. I thought you did it on purpose to test it.

**Comment by cagnulein** [comment]
Yes but I'm saying another thing :)

When a proform changes the inclination, it change the % grade but it also affects the resistance too. So, try riding in this way, when the inclination goes up, do you feel more effort? if so, we don't need to set also the resistance because the bike is already doing so (like my proform bike does)

**Comment by ignacioF1** [comment]
No, the resistance is being untouched. If I select the previous model it only varies the resistance.
Shouldn´t it be like the treadmills with speed and incline? If I selected one of those I notice it is receiving both, although the controls are in a different part of the screen of course.

**Comment by cagnulein** [comment]
@ignacioF1 don't mind about what you see on the screen, check what you feel on the legs! No it doesn't work like the treadmill. Proform wrote the firmware in a a way that inclination affects both grade and resistance. So please do the test and for example, just with ifit ride to 0% grade and then ride to 15% grade, do you feel the difference on the legs?

**Comment by cagnulein** [comment]
> Yes, I understand, it does.

ok perfect, thanks for the confirmation :)



> But what if there is no incline and the resistance should change? For example zwift´s training sessions? It would be great to have both if it is possible.

simply change the tdf setting in the companion. It's the fastest way to do so :)

The perfect scenario would be that QZ will inform the companion to use the resistance if it's an erg workout or the inclination if it's a free ride, but for now just swap the setting, easy peasy :)

**Comment by ignacioF1** [comment]
Excellent! Many thanks!
