### ISSUE TITLE
Can’t control speed/incline of Proform pro 2000

### ISSUE THREAD

**Issue by eddyg17** [cagnulein/QZCompanionNordictrackTreadmill#88]
Hi,
I’ve enabled the sliders in the app (which wasn’t on before) and now when I press the speed button on the QZ app a touch input appears on the treadmill. So I assume you just need to add my coordinates as mentioned on the troubleshooting page. 
Let me know what you need. 
Thanks for your help,
Ed

**Comment by eddyg17** [comment]
Just realised the sliders weren’t on the treadmill screen. Now they are it does control them but it’s not correct. The incline jumps straight to 2 when you press it but then does go up and down by 0.5. If you keep going down it doesn’t decline (mine goes  to -3). 
As for speed, it’s all over the place, sometimes jumps up by 1.1, sometimes goes straight from 4 to 13. Reducing speed doesn’t seem to work most of the time. Thanks again.

**Comment by cagnulein** [comment]
ok share me a screenshot of your ifit interface using the adb screenshot script in the installfolder package and I will add it!

**Comment by eddyg17** [comment]
Thank you. Here it is..


![26-02-2024@11-54-35 21](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/34176514/e83ea1ee-0c30-486b-ae48-0cf0b4bc62d3)

**Comment by cagnulein** [comment]
@eddyg17 are you able to do something similar to this for you treadmill https://github.com/cagnulein/QZCompanionNordictrackTreadmill/issues/81#issuecomment-1954538261 ? for both speed and inclination. You can also test the coordinates with the adb shell input swipe command described on the same topic.

Let me know if it's something that you can do!

**Comment by cagnulein** [comment]
@eddyg17 Any news?
