### ISSUE TITLE
NordicTrack T6.5Si speed and incline tiles not responding 

### ISSUE THREAD

**Issue by Mrcholliday** [cagnulein/QZCompanionNordictrackTreadmill#90]
NordicTrack T6.5Si speed and incline not automatically updating from zwift. 

I can adjust the speed and incline manually and this shows on the tiles 

I have checked everything. How do I find out the coordinates you need

**Comment by cagnulein** [comment]
hi @Mrcholliday first of all follow this https://github.com/cagnulein/QZCompanionNordictrackTreadmill/wiki/Troubleshooting#i-cant-control-the-speedinclinationresistance-of-my-treadmillbike

Let me know

**Comment by cagnulein** [comment]
hi @Mrcholliday any news?
