### ISSUE TITLE
ProForm Studio Bike Not Receiving Metrics 

### ISSUE THREAD

**Issue by SamStrife** [cagnulein/QZCompanionNordictrackTreadmill#91]
Hello, I have a [Proform Studio Bike](https://homegymsupply.co.uk/products/proform-smart-power-10-studio-bike-pro) that I've been trying to get to work but am not having much luck. 

I have followed the steps in the guide but cannot get any of the tile in the app to work, they constantly say 0 and nothing I've tried seems to fix that. 

I've followed the steps in [the troubleshooting section](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/wiki/Troubleshooting#i-installed-the-companion-app-but-i-cant-see-any-data-on-my-qz-app) but still nothing. I will say that the point asking me to "Set the device in the companion app to C1750 and restart the bike/treadmill." confused me as I do not see that option on the phone app and the C170's are all treadmills on the bike options (I don't know if that matters).

I'm worried it's something silly I'm doing, like setting the wrong model in the apps. I've included photos below of all my screens and settings in case it's something there. 

Any help/guidance is appreciated, thank you for the app and support!

**Photos:**
[Bike App Screen](https://imgur.com/uTOAjCS)
[Phone App Screen](https://imgur.com/M1ii1kl)

**Comment by cagnulein** [comment]
hi the problem is on your qz settings. the ip must be set in the tdf companion ip not the tdf4 ip. so remove the ip completely from the tdf4 and press ok and put it in the companion setting and press ok and restart qz.
Let me know

**Comment by SamStrife** [comment]
Thanks for the quick response! Unfortunately, that didn't resolve the issue either, still get nothing on the companion app metrics.

**Comment by cagnulein** [comment]
share a debug log and I will check what's the issue https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

Busy day, so I will probably check this tomorrow

**Comment by SamStrife** [comment]
[Log attached](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14431785/debug-Wed_Feb_28_09_37_44_2024.log) - I'll raise a bug ticket as well, as per the link. 

There's no rush, I appreciate the help however long it takes!
