### ISSUE TITLE
NordicTrack Commercial 2450 (old version - NTL17221)

### ISSUE THREAD

**Issue by domhys** [cagnulein/QZCompanionNordictrackTreadmill#92]
Hi, I've been able to connect and transmit speed from the treadmill to Zwift. Now I'm trying to make Zwift workouts control the treadmill's speed. Touches are registered on screen and speed is being changed, but the set speed doesn't always reflect the speed from Zwift. So I guess the problem is with the coordinates. Please advise which device should be selected in the companion app (or if it's necessary for you to create a new one). I'm attaching a screenshot of my treadmill. Thanks a lot!
![screenshot](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/12382229/76e42449-f760-426e-b105-59d094b86f72)

**Comment by cagnulein** [comment]
Hi, for zwidt speed control you need the windows version of qz. Are you using it?

also for the coordinates: if you do a static test without zwift, are you able to change the speed from qz directly without issues?

**Comment by domhys** [comment]
I'm able to change the speed directly from qz and I'm able to change the speed from Zwift, but it changes to wrong values no matter the method. I can see that the touches are registered correctly on the treadmill's tablet, but I guess they are performed in a slightly wrong places

**Comment by cagnulein** [comment]
ok i will check the coordinates tomorrow. thanks

**Comment by domhys** [comment]
Thank you!

**Comment by cagnulein** [comment]
@domhys checked. I guess the coordinates are wrong because the OP https://github.com/cagnulein/qdomyos-zwift/issues/2052 he didn't finish the test job. So let's resume this!

so check this https://github.com/cagnulein/qdomyos-zwift/issues/2052#issuecomment-1935892548
are you able to find the right math formula using adb from your pc?

**Comment by domhys** [comment]
Hi again @cagnulein , sorry for the late response. I've been playing with speed swipes from the attached comment. I wasn't able to modify the formula yet, but I've tested a lot of different speeds, so you may be able to work it out sooner. I selected 2450 in the companion app and here are my findings:

speedFrom -> speedTo: adb_command (your formula result gives speed)
for example in 2.0 -> 3.0 752/753 means that both these values work correctly

2.0 -> 2.9: adb shell input swipe 1845 779 1845 754 200
2.0 -> 3.0: adb shell input swipe 1845 779 1845 752/753 200 (your formula 751 gives 3.1)
2.0 -> 3.1: adb shell input swipe 1845 779 1845 750/751 200
2.0 -> 4.0: adb shell input swipe 1845 779 1845 726/727 200 (your formula 722 gives 4.2)
2.0 -> 5.0: adb shell input swipe 1845 779 1845 699/700 200 (your formula 693 gives 5.3)
2.0 -> 6.0: adb shell input swipe 1845 779 1845 673/674 200 (your formula 664 gives 6.4)
2.0 -> 8.0: adb shell input swipe 1845 779 1845 620/621 200 (your formula 607 gives 8.5)
2.0 -> 10.0: adb shell input swipe 1845 779 1845 568/569 200 (your formula 607 gives 10.7)
2.0 -> 12.5: adb shell input swipe 1845 779 1845 502/503 200 (your formula 477 gives 13.5)
2.0 -> 15.0: adb shell input swipe 1845 779 1845 436/437 200 (your formula 405 gives 16.2)
2.0 -> 17.5: adb shell input swipe 1845 779 1845 370/371 200 (your formula 333 gives 18.9)
2.0 -> 20.0: adb shell input swipe 1845 779 1845 304/305 200 (your formula 261 gives 21.7)
2.0 -> 22: adb shell input swipe 1845 779 1845 252/253 200 (your formula 203 gives 22 but out of scale)
 
10.0 -> 2.0: adb shell input swipe 1845 568 1845 779 200
20.0 -> 5.0: adb shell input swipe 1845 305 1845 700 200 (it seems the same numbers work both ways)

I will leave the incline for later as I'm always at 0 anyways. Let me know if you need any more speed tests.
Thanks for the help

**Comment by cagnulein** [comment]
done! let me know https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.3.42/QZCompanionNordictrackTreadmill.apk

**Comment by cagnulein** [comment]
@domhys any news?
