### ISSUE TITLE
No data received from QZ app for Nordictrack commercial 2450

### ISSUE THREAD

**Issue by sweetrosie** [cagnulein/QZCompanionNordictrackTreadmill#93]
I've factory reset my treadmill and installed companion via adb, it's running on my treadmill fine, and USB debug is enabled. I've purchased the QZ app from the playstore and put the ip in the 2950 ip field. Nordictrack 10 is selected by default but I've tried selecting every Nordictrack device one at a time and putting the ip in the 2950 or Proform fields but nothing works. On my phone there's no QZ folder under Documents. On the companion app I've tried selecting C1750 or Grand Tour Pro app and nothing works. Our router isn't blocking anything. I've connected and executed "adb shell pm grant org.cagnulein.qzcompanionnordictracktreadmill android.permission.READ_LOGS". I've attached the logs. Please advise. Thanks.
[2024-03-10_logs.txt](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14551972/2024-03-10_logs.txt)

**Comment by cagnulein** [comment]
Hi @sweetrosie are you on android 14 with qz? If so you need the beta from here https://play.google.com/apps/testing/org.cagnulen.qdomyoszwift

Let me know

**Comment by sweetrosie** [comment]
Thanks! I tried the beta version but I'm still not receiving any data from the treadmill.

**Comment by cagnulein** [comment]
the beta was for giving you the possibility to share a debug log from qz otherwise i can't help you

**Comment by sweetrosie** [comment]
Ah ok. Please see the file.
[debug-Sun_Mar_10_14_52_26_2024.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14577659/debug-Sun_Mar_10_14_52_26_2024.log)

**Comment by cagnulein** [comment]
ok perfect the connection between the companion and qz is perfect. are you able to run a "adb logcat" from your pc? what we have to see there is that when you change the speed or the inclination, a line with "changed" word should appear in realtime there.

Are you able to do this test?

**Comment by cagnulein** [comment]
great! let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 12 mar 2024 alle 20:35 SweetRosie ***@***.***>
ha scritto:

**Comment by sweetrosie** [comment]
[log.txt](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14577974/log.txt)
Let me know if this helps.

**Comment by cagnulein** [comment]
are the right changes?

![image](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/48216/42ad8092-cc4e-48d7-b6ef-b88f95591525)

**Comment by sweetrosie** [comment]
Yes

**Comment by cagnulein** [comment]
so also the companion should be able to do the same. did you set also the
gran pro tour in the companion device selections and restarted the
treadmill?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 12 mar 2024 alle 21:05 SweetRosie ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
ok so i need the log from the companion as well. if you press on the log
button on the companion i can see what's wrong. actually the companion just
does the same of the adblog cat that you run.

the log will be written on the root folder of the treadmill

are you able to dump it? do all of this during a workout

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 12 mar 2024 alle 21:41 SweetRosie ***@***.***>
ha scritto:

**Comment by sweetrosie** [comment]
I tried using adb-debug.bat to get the log but it won't work this time. Says failed to connect. I can take a few pictures? Anything specific I need to look for?

**Comment by sweetrosie** [comment]
[logcat.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14578777/logcat.log)

**Comment by cagnulein** [comment]
it  gives me a 404

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 12 mar 2024 alle 22:21 SweetRosie ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
same thing. are you able to open from the link?
i will check it tomorrow from a pc

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 12 mar 2024 alle 22:24 SweetRosie ***@***.***>
ha scritto:

**Comment by sweetrosie** [comment]
[log.txt](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14578836/log.txt)

**Comment by sweetrosie** [comment]
[logcat.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14578844/logcat.log)

**Comment by sweetrosie** [comment]
still not working. one sec

**Comment by sweetrosie** [comment]
[logcat.txt](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14578858/logcat.txt)

**Comment by sweetrosie** [comment]
something is wrong with Github. The previous file is showing the same error too. Try this https://drive.google.com/file/d/1_f5dftStBL1csdq2o3yea_zGCHwQLwIL/view?usp=drive_link

**Comment by cagnulein** [comment]
Request access, thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 12 mar 2024 alle ore 22:31 SweetRosie <
***@***.***> ha scritto:

**Comment by sweetrosie** [comment]
Granted access. The files in the comments are no longer showing errors so you should be able to view it now too.

**Comment by cagnulein** [comment]
ok so i checked and for the speed i saw this

```
03-12 16:57:18.065  7745  7874 V mono-stdout: [15] [Trace:FitnessConsole] Kph changed from 1.6 to 3.21
03-12 16:57:39.434  7745  7874 V mono-stdout: [15] [Trace:FitPro] Changed KPH to: 3.21
```

so 3.21 it's the only value got from the companion. so it seems that it's not loggin them sometimes?

what's the difference, on your opinion, between the test that you did without the qz app (with the logcat directly) and this one?

**Comment by sweetrosie** [comment]
The logcat from my computer was done when I was in the workout with the workout screen but the dump I had to switch to the companion app and click on the dump button and that's the only difference. But that's after I adjusted the speed so it shouldn't matter?

**Comment by cagnulein** [comment]
so in this case which value did you see on QZ? was it matching the 3.21 kp/h?

**Comment by sweetrosie** [comment]
It was not matching the speed of the treadmill. The speed was showing 1mph and incline was 0 as shown in the screenshot

**Comment by cagnulein** [comment]
so 3.21 kp/h was the right one? 
could I ask another test? could you please use the windows version of qz just to check it.
download it from here https://github.com/cagnulein/qdomyos-zwift/releases/download/nightly/windows-msvc2019-binary-no-python.zip
set your treadmill ip in the same setting and enable also the adb remote setting and restart qz. leave the qz app on the phone turned off.

Let me know the result!

**Comment by sweetrosie** [comment]
no, I changed the speed a few times and that was just one of the speeds.
I tried the Windows version and it's not showing any data. All tiles are 0's.
[debug-Wed_Mar_13_18_38_45_2024.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14594569/debug-Wed_Mar_13_18_38_45_2024.log)

**Comment by cagnulein** [comment]
ok for the windows version this is the error

`Wed Mar 13 18:39:12 2024 1710369552975 Debug: devices\bluetooth.cpp void __cdecl bluetooth::debug(const class QString &) "adb << OUT cannot connect to 192.168.86.224:5555: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (10060)\r\n"`

maybe you need to reboot it

instead for



> no, I changed the speed a few times and that was just one of the speeds.

this means that it doesn't seems to log all the speed changes. Let's see if the windows version is better

Let me know

**Comment by cagnulein** [comment]
@sweetrosie any news?
