### ISSUE TITLE
Nordictrack x32i incline control from qz not consistent

### ISSUE THREAD

**Issue by msvklr** [cagnulein/QZCompanionNordictrackTreadmill#94]
Hi there,
So QZ reads data as expected, and I can control the treadmill from the app (android) but for inclinations it behaves not as expected, goes from 1%-2%-3% and then 9% and 25% with each single click, and I can't lower it from there.

x32i is not available from the drop down Proform/Nordictrack options, so I set Nordictrack 10, maybe that's the issue? Which model should I chose?

**Comment by cagnulein** [comment]
hi @msvklr yes that's the issue

i need a screenshot from your ifit interface 

there is a batch file to collect it in the install package folder. are you able to share the screenshot here?

**Comment by msvklr** [comment]
There it is. 
![14 03 2024@20-04-31,55](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/12996473/0b51af57-66f5-42f1-aa66-eb160ecd5b99)

**Comment by cagnulein** [comment]
ok i will check it asap

**Comment by msvklr** [comment]
I changed to x22i and incline seem to work better, speed tho jumps in weird increments. I have it set to 1 and first it increases by 0.9 and next click by 0.1.

**Comment by cagnulein** [comment]
so i can merge the 2 of them for your treadmill profile

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 14 mar 2024 alle 20:07 msvklr ***@***.***> ha
scritto:

**Comment by msvklr** [comment]
Speed steps with the other one were also not consistent tho

**Comment by cagnulein** [comment]
hah ok

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 14 mar 2024 alle 20:12 msvklr ***@***.***> ha
scritto:

**Comment by msvklr** [comment]
Which log file should I send?

**Comment by cagnulein** [comment]
open qz and try to load your xml and generate a debug log following this
https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 14 mar 2024 alle ore 21:24 msvklr ***@***.***>
ha scritto:

**Comment by msvklr** [comment]
[debug-Thu_Mar_14_21_29_58_2024.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14607625/debug-Thu_Mar_14_21_29_58_2024.log)

**Comment by cagnulein** [comment]
you forget the forcespeed tag in the lines in the xml
also enable the "treadmill speed force" in the treadmill settings to enable
the speed control (disabled by default to safety reason)
Let me know

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 14 mar 2024 alle ore 21:34 msvklr ***@***.***>
ha scritto:

**Comment by msvklr** [comment]
forcespeed solved the problem with the workout, thanks for taking your time!
Last problem left is the increment issue. Even though I have speed set as 12 in first line, it is set to 10.8 for some reason, and manual increments also randomly changes the speed by 0.9 or 0.1

**Comment by cagnulein** [comment]
yes this problem will be solved with the new coordinates. I will do it in
the next days

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 14 mar 2024 alle ore 21:58 msvklr ***@***.***>
ha scritto:

**Comment by cagnulein** [comment]
> I changed to x22i and incline seem to work better, speed tho jumps in weird increments. I have it set to 1 and first it increases by 0.9 and next click by 0.1.

when you are talking about this, are you talking about qz or qz companion? because i just checked and there is the x32i device in the companion. did you select it? is the adb remote option in qz main app disabled?

let me know

**Comment by msvklr** [comment]
I think I'm talking about QZ (qdomyos-zwift). Should I purchase QZ AI Companion in app store?

**Comment by cagnulein** [comment]
no @msvklr :) i'm talking about the QZ companion that you installed on your treadmill tablet, don't you?

**Comment by msvklr** [comment]
and on the treadmill indeed there is x32i, according to attached manual I have INT version

**Comment by cagnulein** [comment]
ok but did you set the x32i in the companion app so? 
also is the adb remote setting disabled in the qz main app under the nordictrack treadmill settings?

**Comment by msvklr** [comment]
Q: ok but did you set the x32i in the companion app so?
-- I did on the treadmill screen as in the main manual (this one is what you refer to as companion app if I understand correctly). On the phone QZ app I don't have x32i model in drop down menu.
Q: also is the adb remote setting disabled in the qz main app under the nordictrack treadmill settings?
-- I have in enabled.

**Comment by cagnulein** [comment]
> Q: also is the adb remote setting disabled in the qz main app under the nordictrack treadmill settings?
> -- I have in enabled.

what if you disable it and restart QZ? are you still able to change the inclination and speed? leave the x32i in the companion app.

**Comment by msvklr** [comment]
Gonna check it later and come back to you

**Comment by cagnulein** [comment]
@msvklr any news?
