### ISSUE TITLE
QZ with Nordic Track S15i Bike

### ISSUE THREAD

**Issue by TFlint82** [cagnulein/QZCompanionNordictrackTreadmill#95]
Hi,

I followed all the instructions at the weekend to install and run and worked perfectly. I input the bike as the S22i in the QZ companion on the bike, and just input the IP address of the bike in the TDFIP box.

Went to use it today and not connecting at all, despite nothing changing. I therefore completed a facory reset and did everything again exactly as before and still not connecting. What am I doing wrong? Installation went smoothly and very happy but not transmitting data to the app.

Thanks

**Comment by cagnulein** [comment]
hi @TFlint82 let's start providing a debug log from QZ following this so I will understand which is the issue on your side https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F
Thanks

**Comment by TFlint82** [comment]
Hi, I have tried turning following the instruction but there is no QZ folder under documents or files to share

**Comment by cagnulein** [comment]
are you on android 14? did you join the qz beta from the play store page of
qz?
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 25 mar 2024 alle ore 12:20 TFlint82 ***@***.***>
ha scritto:

**Comment by TFlint82** [comment]
I am on android 14 but not on the beta. Will that help?

**Comment by cagnulein** [comment]
You need the beta for android 14

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 25 mar 2024 alle 13:50 TFlint82 ***@***.***> ha
scritto:

**Comment by TFlint82** [comment]
Okay I've signed up for beta. Will try again and let you know how I get on

**Comment by cagnulein** [comment]
@TFlint82 any news?

**Comment by TFlint82** [comment]
Sorry not managed to try till now. So it connects, but says I'm putting out 700watts when doing zero effort

**Comment by cagnulein** [comment]
Maybe a 10x factor? Share a debug log and I  will check it https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

in the meantime you can use the watt gain setting in the advanced settings to reduce the wattageIn the meantime, you can use the bath gain setting in the advanced settings to reduce the vantage. For example, put 01 value.. For example, put 0.1

**Comment by TFlint82** [comment]
Will try that. I've found the Debug files there are quite a few as I was trying different things.
