### ISSUE TITLE
QZCompanion with Nordic Track S22i not working

### ISSUE THREAD

**Issue by rjlee** [cagnulein/QZCompanionNordictrackTreadmill#96]
Hi,

I have a Nordic Track S22i, privilege mode enabled and USB debugging enabled, on the latest version of ifit.

I've installed the companion app on the bike and have the QZ app on my iphone.  I've not been able to get any readings to sow in the iOS app however (everything is '0').  I've configured the IP of the bike in the Bike Options -> Proform/Nordic Track Options -> TDF4 IP * TDF Companion IP

I've attached the debug logs from both the iOS add and the Companion app.  Could you advise, this is the first time setting it up, so I've not had it working yet.

When clicking 'Dump log' in the companion app, you do observe messages relating to UDP broadcast request from the iOS device IP, so it does look like some communication is happening.

Thanks

[debug-Sat_Mar_23_11_01_41_2024.log.txt](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14731289/debug-Sat_Mar_23_11_01_41_2024.log.txt)

[logcat.txt](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14731286/logcat.txt)

**Comment by cagnulein** [comment]
Hi remove the ip from the tdf4 completely and press OK and restart qz
Show me a new log if you have the same error

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 23 mar 2024 alle 12:25 Robert Lee ***@***.***>
ha scritto:

**Comment by rjlee** [comment]
Thanks that resolved the issue.  I only have the 'TDF Companion IP' filled in now.

**Comment by cagnulein** [comment]
Glad it worked!
remember to rate the app on the store! It means a lot to me!
Thanks!

Il giorno sab 23 mar 2024 alle 13:43 Robert Lee ***@***.***>
ha scritto:
