### ISSUE TITLE
QZ App not adjusting treadmill from input

### ISSUE THREAD

**Issue by SonofHayduke** [cagnulein/QZCompanionNordictrackTreadmill#97]
When I press + and - buttons on QZ app tile there is no change in speed or incline. I do see an animation though

**Comment by cagnulein** [comment]
hi please share which treadmill and also do you any virtual touch events when you press the inclination or the speed plus buttons on your treadmill tablet?

**Comment by cagnulein** [comment]
x22i right? check this https://github.com/cagnulein/qdomyos-zwift/issues/2171

**Comment by SonofHayduke** [comment]
Yes x22i. I looked at the ticket you attached. I enabled ADB, that wasn't on. Still no response from QZ app when hitting + and - in tile, yes I do see a touch event.  Also attached screenshot from app, what treadmill should I choose here? I have selected mine in the companion app, but unsure what to choose here?
![Screenshot_20240407-101157](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/166322290/f1defed6-228d-408c-abfd-5503e709adf4)

**Comment by SonofHayduke** [comment]
Ok, reset app and the inputs on speed and incline tiles are now adjusting the treadmill. Still does not auto adjust incline when in Zwift though

**Comment by cagnulein** [comment]
perfect! you need the beta for this and then you need to set your zwift credentials in qz! are you on android or ios?

**Comment by SonofHayduke** [comment]
I am on android, thanks!

**Comment by cagnulein** [comment]
ok so join the beta from here https://play.google.com/apps/testing/org.cagnulen.qdomyoszwift and then update the app from the store and fill the zwift credentials 

Let me know!

**Comment by SonofHayduke** [comment]
Thanks, it worked briefly, but it was adjusting incline more than what zwift was at so I changed offset to .5
After that I can no longer get the QZ app to talk to the treadmill. Tried uninstalling app and reinstalling didn't work.

**Comment by cagnulein** [comment]
share a debug log and tomorrow i will check it (for the connection issue).
for the 0.5 you can use the zwift inclination offset, set it to -0.5 for example
let me know

**Comment by SonofHayduke** [comment]
[debug-Sun_Apr_7_14_15_58_2024.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14899039/debug-Sun_Apr_7_14_15_58_2024.log)

**Comment by cagnulein** [comment]
> After that I can no longer get the QZ app to talk to the treadmill. Tried uninstalling app and reinstalling didn't work.
> It will also sometimes connect to a bluetooth device and not force wifi

in the log, qz on the phone is not receiving any messages from the treadmill. Did you try to reboot the treadmill? Is the companion still running there?

**Comment by cagnulein** [comment]
@SonofHayduke any news?
