### ISSUE TITLE
Cannot connect via ADB on my nordictrack s15i

### ISSUE THREAD

**Issue by parzidev28** [cagnulein/QZCompanionNordictrackTreadmill#98]
Hello, I have a problem connecting via ADB to install QZ, I put the log attached with the message. I use QDomyos zwift on IOS 17.3.1 

Thanks in advance
[QZ-Companion-log.txt](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14910417/QZ-Companion-log.txt)

**Comment by cagnulein** [comment]
hi did you open adb on the tablet side?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 8 apr 2024 alle 22:13 parzidev28 ***@***.***>
ha scritto:

**Comment by parzidev28** [comment]
yes it's open

**Comment by cagnulein** [comment]
it seems not unfortunately. did you already try to reboot the treadmill?
also try a factory reset without updating the ifit app. usually helps

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 8 apr 2024 alle 22:17 parzidev28 ***@***.***>
ha scritto:

**Comment by parzidev28** [comment]
[QZ-Companion-log.txt](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14910584/QZ-Companion-log.txt)

**Comment by cagnulein** [comment]
try a reboot and in case a factory reset. qz don't have the ability to change ifit, so it could be another issue

**Comment by parzidev28** [comment]
everything is ok now, I have activated the functions as noted in QZ, I entered the IP address of the machine, but when I restart QZ I am stuck on "Connecting..." 
[QZ-Companion-log.txt](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14910646/QZ-Companion-log.txt)

**Comment by cagnulein** [comment]
going to bed now, italy here. share a debug log and i will check it
tomorrow

https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 8 apr 2024 alle 22:32 parzidev28 ***@***.***>
ha scritto:

**Comment by parzidev28** [comment]
Okay thank you, good night !

Here is the log: 
[debug-lun__avr__8_22_38_35_2024.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14910717/debug-lun__avr__8_22_38_35_2024.log)

**Comment by cagnulein** [comment]
ok a couple of things:
- remove the ip of the bike from the 2950 treadmill setting and press ok (remove it completely!)
- set the ip on the proform/nordictrack bike settings, tdf companion ip and press ok
- the connecting label is ok, that's because it's about bluetooth instead your bike is connecting using wifi
- i see the messages from the companion, but only about resistance and gears, nothing about wattage, cadence or speed. can you run a adb logcat on your pc while you're doing a workout? I would like to see if the ifit app is logging it correctly

Let me know!

**Comment by parzidev28** [comment]
here I did what you told me, but the result is the same.

[debug-mar__avr__9_09_27_58_2024.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14914963/debug-mar__avr__9_09_27_58_2024.log)
![IMG_41A43A1D5FE9-1](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/113191746/d7b664e2-09c2-4071-bbe0-2b156aa07cb5)

**Comment by parzidev28** [comment]
ok, how do I do an adb logcat? 
I specify that on the bike in the QZ app I am set to "other" given that the s15i does not appear

**Comment by cagnulein** [comment]
i mean this one 

https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/48216/af20010a-7a39-4023-91fd-bad35d4ac06b

for adb logcat use adb-debug.bat in the install package folder from the companion

**Comment by parzidev28** [comment]
Last login: Mon Apr  8 23:01:46 on ttys000
/Users/private28/Downloads/QZCompanionNordictrackTreadmill-master/InstallPackage/adb-debug-mac ; exit;
private28@MacBook-Pro-de-private28 ~ % /Users/private28/Downloads/QZCompanionNordictrackTreadmill-master/InstallPackage/adb-debug-mac ; exit;
Enter treadmill IP address: 192.168.1.41
PING 192.168.1.41 (192.168.1.41): 56 data bytes
64 bytes from 192.168.1.41: icmp_seq=0 ttl=64 time=183.446 ms
64 bytes from 192.168.1.41: icmp_seq=1 ttl=64 time=11.533 ms
64 bytes from 192.168.1.41: icmp_seq=2 ttl=64 time=12.367 ms
64 bytes from 192.168.1.41: icmp_seq=3 ttl=64 time=7.898 ms

--- 192.168.1.41 ping statistics ---
4 packets transmitted, 4 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 7.898/53.811/183.446/74.864 ms
disconnected everything
* daemon not running; starting now at tcp:5037
* daemon started successfully
failed to connect to 192.168.1.41:5555
List of devices attached
192.168.1.41:5555      offline transport_id:1

- waiting for device -

**Comment by parzidev28** [comment]
I just checked in the developer settings and it is activated

**Comment by cagnulein** [comment]
ok but it's not reachable, so try to reboot the bike. ifit is trying in all the way to block QZ so these first steps could be frustrating

**Comment by parzidev28** [comment]
I'm going to try to reset the bike and start all over again because I don't understand but now my button to lower the resistance no longer works while all the others work.

**Comment by cagnulein** [comment]
ok as i said preventing ifit to update after a reset could be a perfect solution for everything

**Comment by parzidev28** [comment]
[logcat.txt](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14915555/logcat.txt)

**Comment by parzidev28** [comment]
[logcat.txt](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14915564/logcat.txt)

**Comment by parzidev28** [comment]
now my 2 resistance buttons no longer work, I do not understand why

**Comment by cagnulein** [comment]
> now my 2 resistance buttons no longer work, I do not understand why

i guess it's completely unrelated to the companion, did you try a factory reset?



> Log with ip only in the box: TDF companion ip
> 
> [logcat.txt](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14915626/logcat.txt)

ok good news is that I can see the log. Can you share also the content of the folder \.wolflogs that the script downloaded while you were in the workout? Thanks

**Comment by parzidev28** [comment]
so for me it was a cable that was a bit unplugged...
where I can find this .wolflogs file because I can't find it in the installpackage folder

**Comment by parzidev28** [comment]
[debug-mar__avr__9_10_36_01_2024.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14915865/debug-mar__avr__9_10_36_01_2024.log)
[logcat.txt](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14915868/logcat.txt)

**Comment by cagnulein** [comment]
on mac the folder with a . in the front are hidden, so Press Command+Shift+Dot.

**Comment by cagnulein** [comment]
set the companion to the device "proform_carbon_t14"
restart the bike and let me know!

**Comment by parzidev28** [comment]
[2024-04-09_logs.txt](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14915907/2024-04-09_logs.txt)

**Comment by parzidev28** [comment]
ok I did it it's still the same

**Comment by cagnulein** [comment]
got the reason: do this

- set the grand tour pro device in the companion
- run `adb shell pm grant org.cagnulein.qzcompanionnordictracktreadmill android.permission.READ_LOGS` from your install folder
- enable adb debug for qz companion in the bike tablet setting
- restart the bike

let me know!

**Comment by parzidev28** [comment]
ok, sorry but how do I execute this command on mac?

**Comment by parzidev28** [comment]
ok I found it, but here is the message : 
Last login: Tue Apr  9 11:08:37 on ttys000
private28@MacBook-Pro-de-private28 InstallPackage % ./adb shell pm grant org.cagnulein.qzcompanionnordictracktreadmill android.permission.READ_LOGS
adb: device offline

**Comment by parzidev28** [comment]
Last login: Tue Apr  9 11:28:12 on ttys000
private28@MacBook-Pro-de-private28 InstallPackage % ./adb shell pm grant org.cagnulein.qzcompanionnordictracktreadmill android.permission.READ_LOGS
adb: no devices/emulators found
private28@MacBook-Pro-de-private28 InstallPackage % ./adb shell pm grant org.cagnulein.qzcompanionnordictracktreadmill android.permission.READ_LOGS
adb: no devices/emulators found
private28@MacBook-Pro-de-private28 InstallPackage %

**Comment by parzidev28** [comment]
ok I succeeded, it seems to work! I'm going to try with zwift and I'll let you know if everything is ok! Thanks a lot !!

**Comment by cagnulein** [comment]
that's great! let me know!

**Comment by parzidev28** [comment]
the data is transmitted well on zwift but the intensity and inclination does not change depending on zwift it remains at 0 on the bike

**Comment by parzidev28** [comment]
when I run adb screenshot it opens in vscode is this normal?
no I don't see any virtual button when I press the "+" button of the inclination in QZ and besides it doesn't change anything in QZ either

**Comment by parzidev28** [comment]
Last login: Tue Apr  9 12:21:55 on ttys000
private28@MacBook-Pro-de-private28 InstallPackage % chmod a+x adb-screenshot-mac.sh
private28@MacBook-Pro-de-private28 InstallPackage % ./adb-screenshot-mac.sh
Enter treadmill IP address: 192.168.1.41
PING 192.168.1.41 (192.168.1.41): 56 data bytes
64 bytes from 192.168.1.41: icmp_seq=0 ttl=64 time=7.303 ms
64 bytes from 192.168.1.41: icmp_seq=1 ttl=64 time=6.513 ms
64 bytes from 192.168.1.41: icmp_seq=2 ttl=64 time=11.303 ms
64 bytes from 192.168.1.41: icmp_seq=3 ttl=64 time=7.032 ms

--- 192.168.1.41 ping statistics ---
4 packets transmitted, 4 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 6.513/8.038/11.303/1.906 ms
disconnected everything
* daemon not running; starting now at tcp:5037
* daemon started successfully
failed to connect to 192.168.1.41:5555
List of devices attached
192.168.1.41:5555      offline transport_id:1

adb: device offline
adb: error: failed to get feature set: device offline
adb: device offline
private28@MacBook-Pro-de-private28 InstallPackage %

**Comment by parzidev28** [comment]
I don't understand why it just disconnects...

**Comment by cagnulein** [comment]
what did you do before to make it work?

**Comment by cagnulein** [comment]
it could be that adb stays open only for 10 minutes and it goes in timeout if no new connection are made

**Comment by parzidev28** [comment]
I restarted the bike but nothing happened, it's ok with QZ but I just can't send a command with adb

**Comment by parzidev28** [comment]
Last login: Tue Apr  9 13:11:26 on ttys000
private28@MacBook-Pro-de-private28 InstallPackage % chmod a+x adb-screenshot-mac.sh
private28@MacBook-Pro-de-private28 InstallPackage % ./adb-screenshot-mac.sh
Enter treadmill IP address: 192.168.1.41
PING 192.168.1.41 (192.168.1.41): 56 data bytes
64 bytes from 192.168.1.41: icmp_seq=0 ttl=64 time=6.006 ms
64 bytes from 192.168.1.41: icmp_seq=1 ttl=64 time=46.538 ms
64 bytes from 192.168.1.41: icmp_seq=2 ttl=64 time=93.724 ms
64 bytes from 192.168.1.41: icmp_seq=3 ttl=64 time=5.966 ms

--- 192.168.1.41 ping statistics ---
4 packets transmitted, 4 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 5.966/38.059/93.724/36.152 ms
disconnected everything
* daemon not running; starting now at tcp:5037
* daemon started successfully
connected to 192.168.1.41:5555
List of devices attached
192.168.1.41:5555      device product:argon model:MalataMediatekArgon1 device:argon transport_id:1

/sdcard/2024-04-09@13-12-19.png: 1 fil...pped. 1.9 MB/s (57959 bytes in 0.029s)
private28@MacBook-Pro-de-private28 InstallPackage %

**Comment by parzidev28** [comment]
where can i get the png image?

**Comment by cagnulein** [comment]
it's in the same install package folder. the name is the date of today

**Comment by parzidev28** [comment]
![2024-04-09@13-12-19](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/113191746/8a52c56c-c1bc-4db6-9159-bf19e933291c)

**Comment by cagnulein** [comment]
ok but i need a screenshot of your ifit screen 

also did you run also the adb input swipe command?

**Comment by parzidev28** [comment]
I had to reset the bike and do the command quickly so that it disconnects, now I tried the command to see if a virtual button appears when I change the inclination but it means "device offline" again

**Comment by cagnulein** [comment]
when you say reset you say factory reset or reboot?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 9 apr 2024 alle 13:26 parzidev28 ***@***.***>
ha scritto:

**Comment by parzidev28** [comment]
factory reset

**Comment by parzidev28** [comment]
now I still can't take a screenshot because it means this message: 
Last login: Tue Apr  9 13:27:35 on ttys000
private28@MacBook-Pro-de-private28 InstallPackage % chmod a+x adb-screenshot-mac.sh
private28@MacBook-Pro-de-private28 InstallPackage % ./adb-screenshot-mac.sh
Enter treadmill IP address: 192.168.1.41
PING 192.168.1.41 (192.168.1.41): 56 data bytes
64 bytes from 192.168.1.41: icmp_seq=0 ttl=64 time=8.965 ms
64 bytes from 192.168.1.41: icmp_seq=1 ttl=64 time=6.843 ms
64 bytes from 192.168.1.41: icmp_seq=2 ttl=64 time=4.982 ms
64 bytes from 192.168.1.41: icmp_seq=3 ttl=64 time=4.505 ms

--- 192.168.1.41 ping statistics ---
4 packets transmitted, 4 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 4.505/6.324/8.965/1.757 ms
disconnected everything
* daemon not running; starting now at tcp:5037
* daemon started successfully
failed to connect to 192.168.1.41:5555
List of devices attached
192.168.1.41:5555      offline transport_id:1

adb: device offline
adb: error: failed to get feature set: device offline
adb: device offline
private28@MacBook-Pro-de-private28 InstallPackage %

**Comment by cagnulein** [comment]
did you try to inhibit ifit updates?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 9 apr 2024 alle 13:28 parzidev28 ***@***.***>
ha scritto:

**Comment by parzidev28** [comment]
yes but then the updates start again and I can't stop them

**Comment by parzidev28** [comment]
![Capture d’écran 2024-04-09 à 13 41 33](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/113191746/bc5c985e-0fec-44a2-b828-3abbbbad8db0)

**Comment by parzidev28** [comment]
I can only send a photo taken with my iPhone, if I need a screenshot I have to reset the bike and start all over again

**Comment by parzidev28** [comment]
c'est ca que tu as besoin ?

<img width="551" alt="Capture d’écran 2024-04-09 à 13 53 57" src="https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/113191746/3f1fa889-1fe4-492f-91e5-e23678d32bb3">

**Comment by cagnulein** [comment]
> yes but then the updates start again and I can't stop them

you have to inhibit internet access to the bike's tablet from your router. are you able to do so?



> I can only send a photo taken with my iPhone, if I need a screenshot I have to reset the bike and start all over again

nope i need a photo of the ifit manual screen from the script directly because i need precise coordinates. anyway first of all adb must be determistic otherwise the solution to change the inclination from qz would not work (it's based on adb)

let me know

**Comment by parzidev28** [comment]
I think I'm going to end up buying a home trainer ^^

**Comment by cagnulein** [comment]
> I noticed that the bike was no longer connected with ADB when I restarted after this command "adb shell pm grant org.cagnulein.qzcompanionnordictracktreadmill android.permission.READ_LOGS"

this command simply grant a permission to the companion so it shouldn't create any issue at all.

anyway we can avoid to run this command if we use a PC to run QZ directly (instead of using a mobile). In this way the PC will use adb to get the metrics and to control the inclination.

before doing this 2 questions:
- do you have a pc?
- are you sure adb is working everytime without using the grant thing?

**Comment by cagnulein** [comment]
> yes I have a pc I have a macbook pro is it possible with it?

a pc or a mac? 

I developed this particula feature on PC only for now

**Comment by parzidev28** [comment]
I have a Mac and another PC running Linux

**Comment by cagnulein** [comment]
the screenshot is fine but you need to enable the slider bar in order to leave the control to qz.
for the PC i did this on Windows

**Comment by parzidev28** [comment]
I don't have windows..

**Comment by cagnulein** [comment]
> what slider bar ? I don't understand sorry

these ones for example

![image](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/48216/ca9dd99d-6d69-41c8-8025-4b4528820a90)



> I don't have windows..

so we have to understand if we really need adb to control the inclination.

i suggest to enable the https://www.youtube.com/watch?v=aO5lwGhyUuo and then click on the plus inclination tile in order to check if you can see a touch event

let me know

**Comment by parzidev28** [comment]
![2024-04-09@15-31-04](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/113191746/d84745e2-7fb7-4097-b836-61c6ac2dee30)

**Comment by cagnulein** [comment]
nope i need the one with the left and right slider as I shown in my previous screenshot. you see the sliders of inclination and kph (treadmill case). You have to enable this in the ifit settings

**Comment by parzidev28** [comment]
![2024-04-09@15-40-22](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/113191746/efc9352d-796c-4dc9-9a69-cc46108b021c)

**Comment by cagnulein** [comment]
ok that's perfect. now follow this

> i suggest to enable the https://www.youtube.com/watch?v=aO5lwGhyUuo and then click on the plus inclination tile in order to check if you can see a touch event

**Comment by parzidev28** [comment]
ok it's done, but nothing happens when I press the "+" of the inclination

**Comment by parzidev28** [comment]
I restarted the bike so that the grant command took effect and now I no longer have an adb connection, however QZ on my iPhone still receives live data when I do a workout

**Comment by cagnulein** [comment]
instead when you press the touch normally can you see the event?
if so the only way to work around this is to use adb but you have to find a way to "stabilize it". Unfortunately, I can't help you on this because every tablet is different.



> I restarted the bike so that the grant command took effect and now I no longer have an adb connection, however QZ on my iPhone still receives live data when I do a workout

yes it's correct because qz is not using adb for the metrics.

**Comment by parzidev28** [comment]
I don't see any event except the number increasing on the bike, I don't know at all how I can stabilize this adb problem..

**Comment by parzidev28** [comment]
when I press the bike button yes but not the phone button

**Comment by parzidev28** [comment]
I managed to put the adb back on, I found how to do it but I still can't control it with the phone even though adb is ok now

**Comment by parzidev28** [comment]
[logcat.txt](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14919513/logcat.txt)

**Comment by parzidev28** [comment]
I just tried with the application launched on my mac and it's the same, I can't control the inclination of the bike although ADB works correctly

**Comment by cagnulein** [comment]
> I managed to put the adb back on, I found how to do it but I still can't control it with the phone even though adb is ok now

perfect! now under the proform bike section setting, enable the adb remote setting. with this on, restart qz and when you press the incline plus button you have to see an event somewhere on the tablet

let me know!

**Comment by parzidev28** [comment]
adb still ok but nothing happens

**Comment by cagnulein** [comment]
what do you mean adb still ok? did you enable the adb remote setting as I asked?

**Comment by parzidev28** [comment]
I mean that adb is functional because I can run a log from my mac and it connects well, yes I have activated adb remote but there is still nothing when I press the "+" button

**Comment by parzidev28** [comment]
<img width="1026" alt="Capture d’écran 2024-04-09 à 16 37 46" src="https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/113191746/bcf4cf82-81e7-4b01-a1c5-58b074f1b277">

**Comment by cagnulein** [comment]
ok so now are ayou able to run the adb shell input swipe from the mac?

**Comment by parzidev28** [comment]
can you send me the command please because I can no longer find it in conversation

**Comment by cagnulein** [comment]
adb shell input swipe 100 200 300 400 200

**Comment by parzidev28** [comment]
when I put the swipe command I go from the training screen to the screen to be able to stop training

**Comment by cagnulein** [comment]
ok that's perfect! can you collect a qz debug log with a adb remote enabled
while you are pushing the plus inclination button?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 9 apr 2024 alle 18:06 parzidev28 ***@***.***>
ha scritto:

**Comment by parzidev28** [comment]
[debug-mar__avr__9_19_11_39_2024.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14921853/debug-mar__avr__9_19_11_39_2024.log)

**Comment by parzidev28** [comment]
[debug-mar__avr__9_19_12_55_2024.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/14921865/debug-mar__avr__9_19_12_55_2024.log)

**Comment by cagnulein** [comment]
i would like to send you the new ios beta. could you please send me your
email to roberto.viola83 at gmail.com

thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 9 apr 2024 alle 19:13 parzidev28 ***@***.***>
ha scritto:

**Comment by parzidev28** [comment]
ok it works!! but it only works for incline but not for resistance

**Comment by cagnulein** [comment]
amazing! yes it supposed to do so! inclination affects also the resistance!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 9 apr 2024 alle 19:52 parzidev28 ***@***.***>
ha scritto:

**Comment by parzidev28** [comment]
Okay so I have to adjust the resistance myself? we can't manage it automatically with zwift?

**Comment by cagnulein** [comment]
qz is changing automatically the inclination following zwift. on your bike,
when you change the inclination, also the resistance is affected (harder
when the inclination is higher) so we don't need to handle resistance. got
it ?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mar 9 apr 2024 alle 19:55 parzidev28 ***@***.***>
ha scritto:

**Comment by parzidev28** [comment]
ok I see, thank you very much!

**Comment by parzidev28** [comment]
great developer and very responsive! Problem resolved very quickly, thank you very much! ⭐️⭐️⭐️⭐️⭐️

**Comment by cagnulein** [comment]
you have been an amazing user too providing these feedbacks!

remember to rate the app on the store! It means a lot to me!
Thanks!
